<style>

</style>

<?php echo \Phalcon\Tag::stylesheetLink("main/css/myshopdetails.css"); ?>

<div class="row-cell">

    <div class="col-md-12">
        <img src="<?php echo $this->url->get().$image;?>" height="200px" width="800px" >
     </div>  


     <div class="col-md-12">
            <div class="panel panel-default"> 
                <div class="panel-heading">
                    My Products
                </div>

                <div class="panel-body">
                     <div class="table-responsive">
                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Product Name</th>
                                            <th>Image</th>
                                            <th>Price</th>
                                            <th>Creation</th>
                                            <th>Status</th>
                                            <th>More</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                     <?php 
                                     $count=0;
                                     foreach ($Product->items as $record) { 
                                            $count++;
                                        ?>
                                     <tbody>
                                        <tr>
                                            <td><?php echo $count; ?></td>
                                            <td><?php echo $record->product_name;?></td>
                                            
                                            <td>

                                                <?php if (!isset($record->picture)) { ?>
  
                                                    <img src="<?php echo $this->url->get().'main/images/';?>shop_banner.jpg" class="img-responsive" alt="..." height="40px" width="50px">

                                                    <?php } else { ?>

                                                    <img src="<?php echo $this->url->get().$record->picture;?>" class="img-responsive" alt="..." height="40px" width="50px">

                                                    <?php } ?>
                                            </td>


                                            <td><?php echo $record->price;?></td>
                                            <td><?php echo $record->created_at;?></td>
                                            <td><?php echo $record->status;?></td>
                                            <td>
                                                <a href="<?php echo $this->url->get("inventory/details/" . $record->id); ?>"> 
                                                    <p> Details </p>
                                                </a>
                                            </td>
                                            <td>
                                                
                                                <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>">
                                                    <i class="glyphicon glyphicon-pencil" id="pencil" ></i>
                                                </a>
                                            </td>
                                            
                                            
                                            
                                        </tr>
                                    </tbody>
                                     <?php } ?>
                                </table>
                        </div>
                    </div>
                </div>
            </div>
    </div>


        

        <div class="col-md-12">

            <ul class="pager">
                <li><?php echo "You are in page ", $Product->current, " of ", $Product->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("myshop/details/". $value ); ?>">First</a></li>

                <li><a href="<?php echo $this->url->get("myshop/details/".$value."?page=" . $Product->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("myshop/details/".$value."?page=" . $Product->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("myshop/details/".$value."?page=" . $Product->last); ?>">Last</a></li>            
            </ul>

        </div>

    </div>
    

