<style>

</style>

<?php echo \Phalcon\Tag::stylesheetLink("main/css/myshop.css"); ?>
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading" id="heading">
            My Shops
        </div>
        <div class="panel-body">
            <div class="table-responsive">

                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Shop Name</th>
                                            <th>Image</th>
                                            <th>Total Products</th>
                                            
                                            
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                     <?php 
                                     $count=0;
                                     foreach ($Shop->items as $record) { 
                                            $count++;
                                        ?>
                                     <tbody>
                                        <tr>
                                            <td><?php echo $count; ?></td>
                                            <td>
                                                <strong> 
                                                     <a href="<?php echo $this->url->get("myshop/details/" . $record->id); ?>"> 
                                                        <?php echo $record->shop_name; ?>
                                                    </a>
                                                   
                                                </strong>
                                            </td>
                                            <td>
                                                <img src="<?php echo $this->url->get().$record->shop_image;?>" height="40px" width="60px" >
                                            </td>

                                                
                                            <td>
                                                  <?php echo $temp[$record->id]; ?>
                                            </td>
                                        
                                             <td>
                                               <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>"><p>Status</p></a>
                                            </td>
                                            
                                             <td>
                                                <a href="<?php echo $this->url->get("myshop/edit/" . $record->id); ?>">
                                                    <i class="glyphicon glyphicon-pencil" id="pencil"></i>
                                                </a>
                                                <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>">
                                                    <i class="delete fa fa-trash-o fa-lg" ></i>
                                                </a>

                                            </td>
                                            
                                            
                                        </tr>
                                    </tbody>
                                     <?php } ?>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>



    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Shop->current, " of ", $Shop->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("myshop/myshop" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("myshop/myshop?page=" . $Shop->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("myshop/myshop?page=" . $Shop->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("myshop/myshop?page=" . $Shop->last); ?>">Last</a></li>            
        </ul>

    </div>

    <div class="col-md-4 col-md-offset-4">
        <div class="text-center new-button">
            <a href="<?php echo $this->url->get() . 'myshop/new'; ?>"><i class="fa fa-plus-square-o fa-5x"></i></a>   
                <h3>Add New Shop</h3>
            </a>
        </div>
    </div>


</div>