<style>
p{
	font-size: 18px;
	margin-left: 8px;
	color:green;
}


</style>

<div class="row">
    
    <div class="form-area">
	
	<?php echo $this->getContent(); ?>
	
	
	<form action="" method="post" enctype="multipart/form-data">
		<div class="row-cell">
			<div class="col-md-12">
		
				
					<?php echo $form->render("shop_name"); ?>
					<?php
					$message = $form->getMessagesFor('shop_name');
			            foreach ($message as $m) {
			                 ?>
			                 <div class="alert alert-danger form-element"><?php echo $m; ?></div>
			         <?php } ?>

			         <p >Upload Your Shop Image</p>

					<?php echo $form->render("shop_image"); ?>
					<?php
					$message = $form->getMessagesFor('shop_image');
			                foreach ($message as $m) {
			                    ?>
			                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
			            <?php } ?>

			        </br>
			             <p >Upload Your Shop Banner</p>
			        <?php echo $form->render("banner"); ?>
					<?php
					$message = $form->getMessagesFor('banner');
			                foreach ($message as $m) {
			                    ?>
			                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
			            <?php } ?>

					
					
					
					
		
		
					</br>

					
	
				<div class="btn-group btn-group-justified button-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="publish" class="btn btn-lg btn-custom green">Add New Shop</button>
                    </div>			  
                </div>
                <div class="btn-group btn-group-justified form-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="cancel" class="btn btn-lg btn-custom btn-danger">Cancel</button>
                    </div>		  
                </div>
	
	
			</div>
		</div>
	
	</form>
	
	
	</div>
	
</div>