<style>

.des{
	text-align: left;
	margin-left: 50px;
	margin-right: 40px;
}

.heading{
	color:#000;
	text-align: center;
}

.policy{
	margin-left: 50px;
	margin-right: 40px;
}

</style>


<div class="row">
	<div class="container">
		<h3 class="heading">Order and return Policy</h3>
	</div>

	<div class="container">
		<p class="policy">
			This is a complete e-commerce. Here any user can upload their product for sell. User should be registration for upload & selltheir product. Only for buyer (user) not need to verified, but if want to upload product that means create a shop then user should be verified. The verifying process is user must be uploading national ID card or passport or employee ID or Student ID Card and bank account. Only verified user uploads their product for sell. All payment will deposit site owner’s Bank Account. </p>
		<p class="policy">
			When a user want to buy a product who first place order then website want billing and shipping address, shipping method payment method. The order only confirms when payment will be received. Primarily we will include bank transfer and local card only. When receive payment in particular account then a mail send to buyer & seller. That item quantity atomically reduces from site inventory. A seller can see full inventory his own shop and view all order with status.</p>
		<p class="policy">
			After shipment the Item or product sell will change the status particle this order. Order no should be auto increment according to date month year like 0111062014 and 2nd one is 0211062014. System generated a mail send from seller to buyer when Product status changes like (after delivery the product seller should be change the order status pending to delivery).
			After receive buyer the Item who give the receiving confirmation. That is buying and selling process. After confirmation from buyer then seller can withdraw his/her payment after 7 days. Seller set his shipping method from predefines shipping method. Also seller can set delivery area.



		</p>
		
	</div>
</div>