<style>

h3.a{
	color:#000033;
	padding-top: 10px;
    padding-right: 10px;
    padding-bottom: 10px;
    padding-left: 10px;
}



.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 558px;
    width: 67.5%;
}

.seperator-dotted{
	width: 100%;
	border-bottom: 1px solid #ECECEC;
	margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}

b{
	color:#606060;
}

i{
	font-size: 18px;
}
a{
	text-decoration: none;

}
h4>a{
	font-size: 15px;
	color:#870415;
}

a{
	color:#870415;
	font-size: 15px;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}
.intro{
	color:#870415;
	padding-top: 3px;
    font-size: 15px;
}
p{
	font-size: 15px;
}

.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height:49px;
}

.left-menu{
	display:table-row;
}

.col-md-3{
	width:25%;
}

.row {
    margin-left: 3px;
    margin-right: -15px;
}
.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}

</style>

<div class="container">
</hr>
	<div class="row-cell">
		<div class="col-md-6">
        	<h4>Contact Information &ensp; &ensp; &ensp; &ensp;  &ensp;  &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp;
		        <a href="<?php echo $this->url->get("accinfo/editcontact"); ?>">
		            Edit
		        </a>
	        	
         	</h4>   
        
	        <div class="seperator-dotted">

	        </div>


     	</div>



     	<div class="col-md-6">
        	<h4>
        		Bank Account Information  &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp;
		            <a href="<?php echo $this->url->get("accinfo/editbank"); ?>">
		                Edit
		            </a>

         	</h4>   
        
	        <div class="seperator-dotted">

	        </div>


     	</div>

		
		<div class="col-md-6">

			
			<p ><b>User Name</b>       : <?php echo $data['value']->username;?></p>
			<p ><b>Email Address</b>   : <?php echo $data['value']->email;?></p>
			<p ><b>Cell Phone</b>    : <?php echo $data['value']->contact_no;?></p>
			<p ><b>Address</b>        : <?php echo $data['value']->address;?></p>
			<p ><b>Profile Picture</b> : <?php echo $data['value']->picture;?></p>

			</br>
			</br>
		</div>

		<div class="col-md-6">

			
			
			<p ><b>Account Holder</b>   : <?php echo $record['value']->account_holder_name;?></p>
			<p ><b>Account No.</b>       : <?php echo $record['value']->account_no;?></p>
			<p ><b>Bank</b>       : <?php echo $record['value']->bank_name;?></p>
			<p><b>Branch</b>   : <?php echo $record['value']->branch_name;?></p>
			<p ><b>Swift Code</b> : <?php echo $record['value']->swift_code;?></p>

			</br>
			</br>
		</div>

	</div>

</div>