<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bizmela</title>

    <!-- bootstrap integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("bootstrap/css/bootstrap.min.css"); ?>

    <!-- font-awesome integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("font-awesome/css/font-awesome.min.css"); ?>

    <!-- common css integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/main.css"); ?>
	
	  <?php echo \Phalcon\Tag::stylesheetLink("main/css/common.css"); ?>
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/start.css"); ?>

    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    


    <script type="text/javascript">
	    var baseUrl = "<?php echo $this->url->get(); ?>"
	    // alert(baseUrl);
    </script>

    <!-- jquery integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("jquery/jquery-1.11.1.min.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("jquery/jquery-migrate-1.2.1.min.js"); ?>

    <!-- bootstrap integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("bootstrap/js/bootstrap.min.js"); ?>

    <!-- common js integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/main.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.maskedinput.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.als-1.7.min.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery-ui.min.js"); ?>

    <!--CSS for range slider-->
<?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.css"); ?>
<?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.blue.css"); ?>

<?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.plastic.css"); ?>

<!--Scripts for range slider -->



<?php echo \Phalcon\Tag::javascriptInclude("main/js/jshashtable-2.1_src.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.numberformatter-1.2.3.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/tmpl.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.dependClass-0.1.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/draggable-0.1.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.slider.js"); ?>


  </head>
  <body>
    

  <!-- upper part -->
  <div class="top">
    <div class="container container-custom">    
      <div class="row">
        <div class="col-md-6 top-date top-pad bottom-pad">
          <?php $today = date("F j, Y, g:i a"); 
            echo "$today";
          ?>
        </div>
        <div class="col-md-6">
          <div class="top-menu">
            <div class="item top-pad bottom-pad">

              <?php
                            $auth = $this->session->get('auth');
                            if(!$auth){?>
                      
                            <?php }
                            else { ?>

                              <div class="intro">Welcome <?php echo $auth['name'];?></div>
                           <?php } ?>


            </div>
            <div class="item top-pad bottom-pad">
                            <?php
                            $auth = $this->session->get('auth');
                            if(!$auth){?>
                              <a href="<?php echo $this->url->get().'session/index/';?>">SignIn</a>
                            <?php }
                            else { ?>

                              <a href="<?php echo $this->url->get().'home/logout/';?>">Logout</a>
                           <?php } ?>
                            
            </div>
            <div class="item top-pad bottom-pad"><a href="/bizmela/help/index">Help & Support</a></div>
            <div class="item top-pad bottom-pad"><a>US</a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- upper part end -->
  


  <!-- search part -->
  <div class="top-search container container-custom">
    <div class="row"> 
      <div class="col-md-5 col-md-offset-4">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Enter keyword or product number">
          <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
        </div>
      </div>
      <div class="col-md-3 text-right shopping-cart">
        <span class="glyphicon glyphicon-shopping-cart"></span> 
         <span class="shopping-text">
          <a href="<?php echo $this->url->get().'index/shoppingcart/';?>">Shopping Cart</a>
         </span>  
        <span class="shopping-count arrow_box" id="my_count">
          <?php 
          if (!isset($_COOKIE['product'])) {
            # code...
            echo "0";
          }
          else{
            $cookie_count = unserialize($_COOKIE['product']); 
            //print_r($cookie_count);
            echo count($cookie_count); 
          }
          
          ?>  
        </span>
      </div>
    </div>
  </div>
  <!-- search part end -->
  

  <!-- logo part -->
  <div class="logo container container-custom">
    <div class="row">
      <div class="col-md-3">
        <a href=<?php echo $this->url->get("index/"); ?>>
          <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>icon.png"></img>
        </a>
      </div>
    </div>
  </div>
  <!-- logo part ends -->

  <script type="text/javascript">
  
    $(document).ready(function() {

     $('.cat-menu').hover(
         function () {
           //$(this).addClass("open");
            $('.dropdown-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.dropdown-menu').css({"display":"none"});
         }
     );
   });
  </script>

  <style type="text/css">
  .cat-menu table a {
    color: #000000;
    text-decoration: none;
  }
  </style>

  
  

  <!-- main menu part -->
  <div class="main-menu container container-custom">
    <div class="item best-celler"><span class="star">☆</span>Best Seller</div>
    <div class="btn-group item cat-menu">
            <span data-toggle="dropdown" class="dropdown-toggle">Categories</span>
            <ul class="dropdown-menu" style="width : 200%; margin: 0; padding-top: 5px;">
              <table class="table"><tr>
              <?php 
              use Biz_mela\Models\ProductCategory as ProductCategory;
              use Biz_mela\Models\ProductMaster as ProductMaster;
              $categories = ProductCategory::find();

               $count = 0;

               //echo "<table><tr>";
               foreach ($categories as $entry){
                $product_data = ProductMaster::find("cat_id="."'".$entry->id."'");
                echo '<td><a href="'.$this->url->get()."category/index/".$entry->id.'">'.$entry->cat_name.'&ensp;<span class="badge">'.count($product_data).'</span>'.'</a></td>';
                $count++;
                if ($count%3 == 0){
                    if($count >= count($categories))
                      echo "</tr>";

                    else
                      echo "</tr><tr>";
                }
               }

               echo "</tr></table>";

              ?>
            </ul>
    </div>
    <div class="item">Brand</div>
    <div class="item">Discount Product</div>
    <div class="item">Gift Item</div>
  </div>
  <!-- main menu part ends here -->

  <div class="seperator marg-top"></div>


  

  <?php echo $this->getContent() ?>


  
  <!-- subscription area -->
  <div class="subscribe">
    <div class="container">
      <form action="<?php echo $this->url->get("newsletter/subscription/") ?>" method="post">
      <div class="col-md-5">
        <div class="subs-text">Subscribe to our newsletter</div>
      </div>
      
      <div class="col-md-5">
        <input type="text" id="email" name="email" class="form-control input-lg" placeholder="Your mail address here..">        
      </div>
      <div class="col-md-2">
          
          <div class="btn-group btn-group-justified button-element">
                      <div class="btn-group">
                          <button type="submit" name="submit" value="publish" class="form-control input-lg btn bg-red">Submit</button>
                      </div>        
                  </div>
              
      </div>
    </form>
      
    </div>
  </div>
  <!-- subscription area ends -->
  

  <!-- payment section -->
  <div class="payment">
    <div class="container">
      <div class="col-md-12">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card1.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card2.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card3.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card4.jpg"></img>
      </div>
    </div>
  </div>
  <!-- payment section ends here -->


  <!-- footer area -->
  <div class="footer">
    <div class="container">
      <div class="col-md-3 item">
        <h3>Links</h3>
        <div><a href="<?php echo $this->url->get("sitemap/index/"); ?>" class="about">Site Map</a></div>
        <div><a href="<?php echo $this->url->get("footer/index/"); ?>" class="about">About Us</a></div>
        <div>Advanced Search</div>
        <div><a href="<?php echo $this->url->get("policy/index/"); ?>" class="about">Order and Return</a></div>
        <div><a href="<?php echo $this->url->get("contact/contact/"); ?>" class="about">Contact Us</a></div>
        
      </div>
      <div class="col-md-2 item">
        <h3>Information</h3>
        <div>New Products</div>
        <div>Top Seller</div>
        <div>Specials</div>
        <div>Manufacturers</div>
        <div>Our Store</div>
      </div>
      <div class="col-md-3 item">
        <h3>Latest Tweets : <span><img src="<?php echo $this->url->get().'main/images/';?>twitter_icon.png" class="img-responsive"></span></h3>
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua</div>
       
        
      </div>
      <div class="col-md-4 item">
        <h3>Facebook: <span><img src="<?php echo $this->url->get().'main/images/';?>facebook_icon.png" class="img-responsive"></span></h3>
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua</div>
       
        
      </div>
    </div>


    <div class="footer-seperator"></div>

    <div class="bottom-footer container">
      <div class="col-md-4 col-md-offset-1">
        <div class="item"><i class="fa fa-facebook"></i></div>
        <div class="item"><i class="fa fa-twitter"></i></div>
        <div class="item"><i class="fa fa-stack-overflow"></i></div>
        <div class="item"><i class="fa fa-css3"></i></div>
        <div class="item"><i class="fa fa-apple"></i></div>
        <div class="item"><i class="fa fa-android"></i></div>
      </div>
      <div class="col-md-7 text-center copyright">
        ©2014 Biz-mela All rights reserved.Designed and Developed By Atomix System Limited
      </div>
    </div>


  </div>
  <!-- footer area ends here -->




  </body>
</html>
