<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bizmela</title>

    <!-- bootstrap integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("bootstrap/css/bootstrap.min.css"); ?>

    <!-- font-awesome integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("font-awesome/css/font-awesome.min.css"); ?>

    <!-- common css integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/main.css"); ?>
	
	<?php echo \Phalcon\Tag::stylesheetLink("main/css/common.css"); ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    


    <script type="text/javascript">
	    var baseUrl = "<?php echo $this->url->get(); ?>"
	    // alert(baseUrl);
    </script>

    <!-- jquery integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("jquery/jquery-1.11.1.min.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("jquery/jquery-migrate-1.2.1.min.js"); ?>

    <!-- bootstrap integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("bootstrap/js/bootstrap.min.js"); ?>

    <!-- common js integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/main.js"); ?>



  </head>
  <body>
    

  <!-- upper part -->
  <div class="top">
    <div class="container container-custom">    
      <div class="row">
        <div class="col-md-6 top-date top-pad bottom-pad">
          monday,11th june 2014
        </div>
        <div class="col-md-6">
          <div class="top-menu">
            <div class="item top-pad bottom-pad">

              <?php
                            $auth = $this->session->get('auth');
                            if(!$auth){?>
                      
                            <?php }
                            else { ?>

                              <div class="intro">Welcome <?php echo $auth['name'];?></div>
                           <?php } ?>


            </div>
            <div class="item top-pad bottom-pad">
                            <?php
                            $auth = $this->session->get('auth');
                            if(!$auth){?>
                              <a href="<?php echo $this->url->get().'session/index/';?>">SignIn</a>
                            <?php }
                            else { ?>

                              <a href="<?php echo $this->url->get().'home/logout/';?>">Logout</a>
                           <?php } ?>
                            
            </div>
            <div class="item top-pad bottom-pad"><a href="/bizmela/help/index">Help & Support</a></div>
            <div class="item top-pad bottom-pad"><a>US</a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- upper part end -->
  


  <!-- search part -->
  <div class="top-search container container-custom">
    <div class="row"> 
      <div class="col-md-5 col-md-offset-4">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Enter keyword or product number">
          <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
        </div>
      </div>
      <div class="col-md-3 text-right shopping-cart">
        <span class="glyphicon glyphicon-shopping-cart"></span>  <span class="shopping-text">Shopping Cart</span>  
        <span class="shopping-count arrow_box" id="my_count">
          <?php 
          if (!isset($_COOKIE['product'])) {
            # code...
            echo "0";
          }
          else{
            $cookie_count = unserialize($_COOKIE['product']); 
            //print_r($cookie_count);
            echo count($cookie_count); 
          }
          
          ?>  
        </span>
      </div>
    </div>
  </div>
  <!-- search part end -->
  

  <!-- logo part -->
  <div class="logo container container-custom">
    <div class="row">
      <div class="col-md-3">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>icon.png"></img>
      </div>
    </div>
  </div>
  <!-- logo part ends -->
  


  <!-- main menu part -->
  <div class="main-menu container container-custom">
    <div class="item best-celler"><span class="star">☆</span>Best Seller</div>
    <div class="item">Categories</div>
    <div class="item">Brand</div>
    <div class="item">Discount Product</div>
    <div class="item">Gift Item</div>
  </div>
  <!-- main menu part ends here -->

  <div class="seperator marg-top"></div>


  

  <?php echo $this->getContent() ?>


  
  <!-- subscription area -->
  <div class="subscribe">
    <div class="container">
      
      <div class="col-md-5">
        <div class="subs-text">Subscribe to our newsletter</div>
      </div>
      <div class="col-md-5">
        <input type="text" class="form-control input-lg" placeholder="Your mail address here..">        
      </div>
      <div class="col-md-2">
        <input type="submit" class="form-control input-lg btn bg-red">        
      </div>
      
    </div>
  </div>
  <!-- subscription area ends -->
  

  <!-- payment section -->
  <div class="payment">
    <div class="container">
      <div class="col-md-12">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card1.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card2.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card3.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card4.jpg"></img>
      </div>
    </div>
  </div>
  <!-- payment section ends here -->


  <!-- footer area -->
  <div class="footer">
    <div class="container">
      <div class="col-md-3 item">
        <h3>Links</h3>
        <div>Site Map</div>
        <div>About Us</div>
        <div>Advanced Search</div>
        <div>Orders and Returns</div>
        <div>Contact Us</div>
      </div>
      <div class="col-md-2 item">
        <h3>Information</h3>
        <div>New Products</div>
        <div>Top Seller</div>
        <div>Specials</div>
        <div>Manufacturers</div>
        <div>Our Store</div>
      </div>
      <div class="col-md-3 item">
        <h3>Latest Tweets : <span><img src="<?php echo $this->url->get().'main/images/';?>twitter_icon.png" class="img-responsive"></span></h3>
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua</div>
       
        
      </div>
      <div class="col-md-4 item">
        <h3>Facebook: <span><img src="<?php echo $this->url->get().'main/images/';?>facebook_icon.png" class="img-responsive"></span></h3>
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua</div>
       
        
      </div>
    </div>


    <div class="footer-seperator"></div>

    <div class="bottom-footer container">
      <div class="col-md-4 col-md-offset-1">
        <div class="item"><i class="fa fa-facebook"></i></div>
        <div class="item"><i class="fa fa-twitter"></i></div>
        <div class="item"><i class="fa fa-stack-overflow"></i></div>
        <div class="item"><i class="fa fa-css3"></i></div>
        <div class="item"><i class="fa fa-apple"></i></div>
        <div class="item"><i class="fa fa-android"></i></div>
      </div>
      <div class="col-md-7 text-center copyright">
        ©2014 Biz-mela All rights reserved.Designed and Developed By Atomix System Limited
      </div>
    </div>


  </div>
  <!-- footer area ends here -->




  </body>
</html>
