
 <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Change Password</h3>
                    </div>
                    <div class="panel-body">
                            <?php echo $this->getContent(); ?>
                        <form action="" method="post">
                            <fieldset>
                               <!-- <?php echo $form->render("name"); ?>-->
                               <div class="form-group">
                                    <input class="form-control" placeholder="Current Password" name="current_pass" type="password"  autofocus>
                                </div>
                                <?php $message = $form->getMessagesFor('current_pass');
                                foreach ($message as $m) {?>
                                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
                                <?php }?>
                                
                               <div class="form-group">
                                    <input class="form-control" placeholder="New Password" name="new_pass" type="password"  autofocus>
                                </div>
                                <?php $message = $form->getMessagesFor('new_pass');
                                foreach ($message as $m) {?>
                                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
                                <?php }?>

                                <div class="form-group">
                                    <input class="form-control" placeholder="Confirm Password" name="confirm_pass" type="password"  autofocus>
                                </div>
                                <?php $message = $form->getMessagesFor('confirm_pass');
                                foreach ($message as $m) {?>
                                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
                                <?php }?>
                                <button type="submit" class="btn btn-lg btn-success btn-block">Change Password</button>
                                
                                <!-- Change this to a button or input when using this as a form -->
                               
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
