
<style>
p{
	color:#1BD8E9;
	font-size: 16px;
}

.foo{
	font-size: 16px;
	color:#000000;
}
h3{

	color:#FF0000
}
h2{
	color:#624949;
	font-size:40px;
	weight:60%;
}

option{
	padding-top: 16px;
    padding-right: 0px;
    padding-bottom: 16px;
    padding-left: 0px;
}

a{
	color:#870415;
}
.intro{
	color:#870415;
}
.successMessage {
    color: #339966;
    font-size: 18px;
    padding: 15px;
}

</style>




<div class="container">

	<div class="container">
		<div class="col-md-6 col-md-offset-3">
			<div class="page-header">
				<h2>Register For Bizmela</h2>
				<?php  echo $this->getContent(); ?>

			</div>

			<form action="" method="post">
                    <!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->

                
				
	                <?php
	                $message = $form->getMessagesFor('firstname');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
	                <?php echo $form->render("firstname"); ?>
				
	                <?php
	                $message = $form->getMessagesFor('lastname');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
				
					<?php echo $form->render("lastname"); ?>

					
	                <?php
	                $message = $form->getMessagesFor('username');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
	                <?php echo $form->render("username"); ?>

	                
	                <?php
	                $message = $form->getMessagesFor('cellphone');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
	                <?php echo $form->render("cellphone"); ?>


	                
	                <?php
	                $message = $form->getMessagesFor('email');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
	                <?php echo $form->render("email"); ?>

	                
	                <?php
	                $message = $form->getMessagesFor('password');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
	                <?php echo $form->render("password"); ?>

	                
	                <?php
	                $message = $form->getMessagesFor('repeatPassword');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
	                <?php echo $form->render("repeatPassword"); ?>

	                
	                <?php
	                $message = $form->getMessagesFor('address');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
	                <?php echo $form->render("address"); ?>

	                
	                <?php
	                $message = $form->getMessagesFor('dob');
	                foreach ($message as $m) {
	                    ?>
	                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
	                <?php } ?>
	                <?php echo $form->render("dob"); ?>


	                </br>

	                <div class="btn-group btn-group-justified button-element">
	                    <div class="btn-group">
	                        <button type="submit" name="submit" value="publish" class="btn btn-lg btn-custom green">Register</button>
	                    </div>			  
	                </div>
	                

            </form>



			<footer>
				</br>
				</br>
		        <p class="foo">©Bizmela 2014</p>
		    </footer>
		</div>


	</div>
</div>

