
<div class="row">
     <div style="font-size:14px;text-align:center;color:#428bca;"><h1>Brand Update</h1></div>
</div>
<div class="row">
    <div class="item-area">
        <div class="form-area">
                    
            <?php echo $this->getContent(); ?>

            <form action="" method="post">
                <!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
                 <div class="form-group">
                                    <input class="form-control" placeholder="Brand Name" name="brand_name" type="text" value="<?php echo $brand->brand_name;?>"  autofocus>
                                </div>
                <?php $message = $form->getMessagesFor('brand_name');
                foreach ($message as $m) {?>
                    <div class="alert alert-danger form-element"><?php echo $m; ?></div>
                <?php }?>
                
                
               
                <div class="btn-group btn-group-justified button-element">
                  <div class="btn-group">
                    <button type="submit" class="btn btn-lg btn-success btn-block">Save</button>
                  </div>
                  
                </div>

            </form>
        </div>
        

    </div>
</div>