<style>
h4{
color:#660099;

}

.info{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 55px;
    width: 95%;
    padding-top: 15px;
    padding-right: 10px;
    padding-bottom: 15px;
    padding-left: 10px;


}

.item-area{

    text-align: center;

}

p > a:hover{

    background-color: #52575F;
    color: white;
}

a{

    text-decoration: none;
    color:#870415;
}

a:hover{
    color:#432C8E;
    text-decoration: none;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height: 49px;
}
.row {
    margin-left: 3px;
    margin-right: -15px;
}
.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}


</style>
<div class="row">

    <div class="item-area">

        <div class="col-md-8 col-md-offset-2">

            <div class="info">
                <Strong> Product Id.: </strong><?php echo $product_id;?>
            </div>
            

            <div class="info">
                <Strong> Price: </strong><?php echo $price;?>
            </div>

            <div class="info">
                <Strong> Quantity: </strong><?php echo $quantity;?>
            </div>



            
        </div>


    </div>
    

</div>