<style>
.nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background-color: #fff;
    border-color: #fff #fff transparent;
   
    border-style: solid;
    border-width: 0px;
    color: #fff;
    cursor: default;
}
</style>

<?php echo \Phalcon\Tag::stylesheetLink("main/css/list.css"); ?>
<div class="row-cell">
    
    <div class="tabbable">
        <div class="mid-menu">
            
          <ul class="nav nav-tabs">
            
            <li class="active"><a href="#pane1" data-toggle="tab"><div class="item">All</div></a></li>
            <li><a href="#pane2" data-toggle="tab"><div class="item">Purchase</div></a></li>
            <li><a href="#pane3" data-toggle="tab"><div class="item">Pending</div></a></li>
            <li><a href="#pane4" data-toggle="tab"><div class="item">Reject</div></a></li>
          </ul>
      
        </div>

        <div class="red-joint"></div>
        <div class="tab-content">
            <div id="pane1" class="tab-pane active">
                <div class="container item-area">
                    <div class="col-md-8">
                        <div class="panel panel-default">
                            <div class="panel-heading" id="heading">
                                Order List
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">

                                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                                    <thead>
                                                        <tr>
                                                            <th>#</th>
                                                            <th>Order Number</th>
                                                            <th>Product Name</th>
                                                            
                                                            <th>Price</th>
                                                            <th>Quantity</th>
                                                            <th>Total</th>
                                                            <th>Status</th>
                                                            
                                                        </tr>
                                                    </thead>
                                                     <?php 
                                                     $count=0;
                                                     foreach ($Order->items as $record) { 
                                                            $count++;
                                                        ?>
                                                     <tbody>
                                                        <tr>
                                                            <td><?php echo $count; ?></td>
                                                            <td>
                                                                
                                                                <?php echo $record->order_no; ?>
                                                                    
                                                            </td>
                                                            <td>
                                                                <?php echo $record->product_name; ?>
                                                            </td>
                                                            <td>
                                                                 <?php echo $record->price;?>
                                                            </td>
                                                            <td>
                                                                 <?php echo $record->quantity; ?>
                                                            </td>

                                                            <td>
                                                                 <?php echo $record->total; ?>
                                                            </td>

                                                            <td>
                                                                 <?php echo $record->status; ?>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                     <?php } ?>
                                        </table>

                                    </div>
                                </div>

                            </div>
                        </div>
                </div> 

                <div class="col-md-8">

                    <ul class="pager">
                            <li><?php echo "You are in page ", $Order->current, " of ", $Order->total_pages; ?></li>
                            <li><a href="<?php echo $this->url->get("Order/list" ); ?>">First</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Order->before); ?>">Previous</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Order->next); ?>">Next</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Order->last); ?>">Last</a></li>            
                    </ul>

                </div>
            </div>
        </div>

        <div id="pane2" class="tab-pane">
            <div class="container item-area">
                <div class="col-md-8">
                    <div class="panel panel-default">
                        <div class="panel-heading" id="heading">
                           Purchase History
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">

                                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Order Number</th>
                                                <th>Total</th>
                                                
                                                <th>Subtotal</th>
                                                <th>Status</th>
                                                
                                                
                                            </tr>
                                        </thead>
                                         <?php 
                                         $count=0;
                                         foreach ($Purchase->items as $record) { 
                                                $count++;
                                            ?>
                                         <tbody>
                                            <tr>
                                                <td><?php echo $count; ?></td>
                                                <td>
                                                    
                                                    <?php echo $record->order_no; ?>
                                                        
                                                </td>
                                                <td>
                                                    <?php echo $record->total; ?>
                                                </td>
                                                <td>
                                                     <?php echo $record->subtotal;?>
                                                </td>
                                                <td>
                                                     <p><?php echo $record->status_name; ?></p>
                                                </td>

        
                                                
                                            </tr>
                                        </tbody>
                                         <?php } ?>
                                    </table>

                                </div>
                            </div>

                        </div>
                    </div>
                </div> 

                <div class="col-md-8">

                    <ul class="pager">
                            <li><?php echo "You are in page ", $Purchase->current, " of ", $Purchase->total_pages; ?></li>
                            <li><a href="<?php echo $this->url->get("Order/list" ); ?>">First</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Purchase->before); ?>">Previous</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Purchase->next); ?>">Next</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Purchase->last); ?>">Last</a></li>            
                    </ul>

                </div>
            </div>
        </div>

        <div id="pane3" class="tab-pane">
            <div class="container item-area">
                <div class="col-md-8">
                    <div class="panel panel-default">
                        <div class="panel-heading" id="heading">
                           Pending List
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">

                                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Order Number</th>
                                                <th>Total</th>
                                                
                                                <th>Subtotal</th>
                                                <th>Status</th>
                                                
                                                
                                            </tr>
                                        </thead>
                                         <?php 
                                         $count=0;
                                         foreach ($Pending->items as $record) { 
                                                $count++;
                                            ?>
                                         <tbody>
                                            <tr>
                                                <td><?php echo $count; ?></td>
                                                <td>
                                                    
                                                    <?php echo $record->order_no; ?>
                                                        
                                                </td>
                                                <td>
                                                    <?php echo $record->total; ?>
                                                </td>
                                                <td>
                                                     <?php echo $record->subtotal;?>
                                                </td>
                                                <td>
                                                     <p><?php echo $record->status_name; ?></p>
                                                </td>

        
                                                
                                            </tr>
                                        </tbody>
                                         <?php } ?>
                                    </table>

                                </div>
                            </div>

                        </div>
                    </div>
                </div> 

                <div class="col-md-8">

                    <ul class="pager">
                            <li><?php echo "You are in page ", $Pending->current, " of ", $Pending->total_pages; ?></li>
                            <li><a href="<?php echo $this->url->get("Order/list" ); ?>">First</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Pending->before); ?>">Previous</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Pending->next); ?>">Next</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Pending->last); ?>">Last</a></li>            
                    </ul>

                </div>
            </div>
        </div>


        <div id="pane4" class="tab-pane ">
            <div class="container item-area">
                <div class="col-md-8">
                    <div class="panel panel-default">
                        <div class="panel-heading" id="heading">
                           Reject List
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">

                                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Order Number</th>
                                                <th>Total</th>
                                                
                                                <th>Subtotal</th>
                                                <th>Status</th>
                                                
                                                
                                            </tr>
                                        </thead>
                                         <?php 
                                         $count=0;
                                         foreach ($Reject->items as $record) { 
                                                $count++;
                                            ?>
                                         <tbody>
                                            <tr>
                                                <td><?php echo $count; ?></td>
                                                <td>
                                                    
                                                    <?php echo $record->order_no; ?>
                                                        
                                                </td>
                                                <td>
                                                    <?php echo $record->total; ?>
                                                </td>
                                                <td>
                                                     <?php echo $record->subtotal;?>
                                                </td>
                                                <td>
                                                     <p><?php echo $record->status_name; ?></p>
                                                </td>

        
                                                
                                            </tr>
                                        </tbody>
                                         <?php } ?>
                                    </table>

                                </div>
                            </div>

                        </div>
                    </div>
                </div> 

                <div class="col-md-8">

                    <ul class="pager">
                            <li><?php echo "You are in page ", $Reject->current, " of ", $Reject->total_pages; ?></li>
                            <li><a href="<?php echo $this->url->get("Order/list" ); ?>">First</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Reject->before); ?>">Previous</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Reject->next); ?>">Next</a></li>
                            <li><a href="<?php echo $this->url->get("Order/list?page=" . $Reject->last); ?>">Last</a></li>            
                    </ul>

                </div>
            </div>
        </div>

    </div>
</div>

</div>
