<style>
.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 505px;
    width: 95%;


}


.row-cell>.col-md-6{
	
    height: 125px;
    width: 100%;

}



.gray{

	background-color:#F7FAFC;
	color:#042C51;

	

}

.gray:hover{
	background-color:#F7FAFC;
	color:#84660A;
}
.navbar {
	background-color: #F7FAFC;
}

a{

	text-decoration: none;
	color:#870415;
}

.col-md-3{
	position: inherit;
}

p{
	font-size: 18px;
}

.intro{
	color:#870415;
}

</style>


<div class="row-cell">
	
	<nav class="navbar navbar-default" role="navigation">
		
      		
   		
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/list/')?>" class="btn btn-lg btn-custom gray"><p>View Order List</p></a>
			</div>
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/purchase/')?>" class="btn btn-lg btn-custom gray"><p>Purchase History</p></a>
			</div>
			
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/pending/')?>" class="btn btn-lg btn-custom gray"><p>&ensp; Pending List &ensp;</p></a>
			</div>
			
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/reject/')?>" class="btn btn-lg btn-custom gray"><p>Reject History &ensp; </p></a>
			</div>
			
		</div>
	
	</nav>



</div>