

<style>

.nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background-color: #fff;
    border-color: #fff #fff transparent;
   
   border-style: solid;
    border-width: 0px;
    color: #fff;
    cursor: default;
}

table{
    border-collapse: separate;
}

.modal-footer {
    border-top: none;
    margin-top: -5px;
    padding: 0px;
    text-align: center;
}

.ques_mod{

    padding-left: 100px;
}

</style>
<?php echo \Phalcon\Tag::stylesheetLink("main/css/list.css"); ?>

<div class="row-cell">
    <div class="tabbable">
        <div class="mid-menu">
          <ul class="nav nav-tabs">
            
            <li class="active"><a href="#pane1" data-toggle="tab"><div class="item">Subscribed To</div></a></li>
            <li><a href="#pane2" data-toggle="tab"><div class="item">Subscribed By</div></a></li>
            
        </div>

    <div class="red-joint"></div>
    <div class="tab-content">
        <div id="pane1" class="tab-pane active">
            <div class="container item-area">
                <div class="col-md-8">
                    <div class="panel panel-default">
                        <div class="panel-heading" id="heading">
                           Subscribed To
                        </div>
                    <div class="panel-body">
                        <div class="table-responsive">

                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Shop</th>
                                                <th>Image</th>
                                                
                                                <th>Status</th>
                                                <th>Action</th>

                                            </tr>
                                        </thead>
                                         <?php 
                                         $count=0;
                                         foreach ($Subscription->items as $record) { 
                                                $count++;
                                            ?>
                                         <tbody>
                                            <tr>
                                                <td><?php echo $count; ?></td>
                                                
                                                <td>
                                                    <strong>
                                                        <?php if($record->shop_id==0) echo "General Subscribtion"; else {?>
                                                        <a href="<?php echo $this->url->get("shop/index/" . $record->shop_id); ?>" >
                                                            <?php echo $record->shop_name; }?>
                                                        </a>
                                                    </strong>
                                                    
                                                </td>
                                                <td>
                                                    <?php if (!isset($record->shop_image)) { ?>
  
                                                    <img src="<?php echo $this->url->get().'main/images/';?>shop_banner.jpg" class="img-responsive" alt="..." width="60px" style="height:40px;">

                                                    <?php } else { ?>

                                                    <img src="<?php echo $this->url->get().$record->shop_image;?>" class="img-responsive" alt="..." width="60px" style="height:40px;">

                                                    <?php } ?>
                                                </td>
                                                

                                                 <td class="status">
                                                     <?php echo $record->status;?>
                                                </td>
                                                <td>
                                                   <a href=""  data-toggle="modal" data-target="#basicModal<?php echo $record->id; ?>">
                                                        Unsubscribe
                                                    </a>

                                                    <div class="modal fade" id="basicModal<?php echo $record->id; ?>" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close" data-dismiss="modal">
                                                                    <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                                                                    <span class="sr-only">Close</span>
                                                                </button>
                                                                <h4 class="modal-title" id="myModalLabel"> </h4>
                                                            </div>
                                                            <div class="modal-body">
                                                              <p class="ques_mod"> Unsubscribe？ </p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <div class="top-tabs1">
                                                                    <button type="button" class="item btn" data-dismiss="modal">
                                                                         No 
                                                                    </button> &ensp;
                                                                    <button type="button" class="item btn btn-primary" onclick="window.location.href='<?php echo $this->url->get("subscribe/unsubscribe/" . $record->id); ?>'"> 
                                                                        Yes
                                                                    </button> 
                                                                </div> 
                                                            </div>
                                                        </div>
                                                    </div>
                                                    </div>
                                                </td>
                                                 
                                                
                                                
                                            </tr>
                                        </tbody>
                                         <?php } ?>
                                </table>

                            </div>
                        </div>

                    </div>
                    </div>
                </div>

            <div class="col-md-8">

                <ul class="pager">
                        <li><?php echo "You are in page ", $Subscription->current, " of ", $Subscription->total_pages; ?></li>
                        <li><a href="<?php echo $this->url->get("subscribe/subscription" ); ?>">First</a></li>
                        <li><a href="<?php echo $this->url->get("subscribe/subscription?page=" . $Subscription->before); ?>">Previous</a></li>
                        <li><a href="<?php echo $this->url->get("subscribe/subscription?page=" . $Subscription->next); ?>">Next</a></li>
                        <li><a href="<?php echo $this->url->get("subscribe/subscription?page=" . $Subscription->last); ?>">Last</a></li>            
                </ul>

            </div>
        </div> <!---Container item-area !-->

    </div> <!---pane1 !-->


    <div id="pane2" class="tab-pane">
        <div class="container item-area">
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading" id="heading">
                       Subscribed By
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">

                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    
                                                    <th>Shop</th>
                                                    <th>Image</th>
                                                    <th>Subscriber</th>
                                                    
                                                    <th>Status</th>
                                                    <th>Action</th>
                                                    
                                                </tr>
                                            </thead>
                                             <?php 
                                             $count=0;
                                             foreach ($News->items as $record) { 
                                                    $count++;
                                                ?>
                                             <tbody>
                                                <tr>
                                                    <td><?php echo $count; ?></td>
                                                    

                                                    <td>
                                                        
                                                        <strong>
                                                            <a href="<?php echo $this->url->get("myshop/details/" . $record->shop_id); ?>" >
                                                                <?php echo $record->shop_name; ?>
                                                            </a>
                                                        </strong>
                                                            
                                                    </td>
                                                    <td>
                                                        <?php if (!isset($record->shop_image)) { ?>
  
                                                    <img src="<?php echo $this->url->get().'main/images/';?>shop_banner.jpg" class="img-responsive" alt="..." height="50px" width="50px">

                                                    <?php } else { ?>

                                                    <img src="<?php echo $this->url->get().$record->shop_image;?>" class="img-responsive" alt="..." height="50px" width="50px">

                                                    <?php } ?>
                                                    </td>
                                                    <td>
                                                       
                                                         <?php echo $record->email;?>
                                                        
                                                    </td>

                                                     <td>
                                                         <?php echo $record->status;?>
                                                    </td>

                                                    <td>
                                                        <a href=""  data-toggle="modal" data-target="#basicModal2<?php echo $record->id; ?>">
                                                            Unsubscribe
                                                        </a>

                                                  

                                                        <div class="modal fade" id="basicModal2<?php echo $record->id; ?>" tabindex="-1" role="dialog" aria-labelledby="loginfirstModal" aria-hidden="true">
                                                            <div class="modal-dialog">
                                                                <div class="modal-content modal-margin-top">
                                                                    <div class="modal-header">
                                                                      <button type="button" class="close" data-dismiss="modal">
                                                                        <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                                                                        <span class="sr-only">Close</span>
                                                                      </button>
                                                                
                                                                    </div>
                                                                    <div class="modal-body">
                                                                        <p class="ques_mod">Unsubscribe？</p>
                                                                    </div>

                                                                    <div class="modal-footer">
                                                                        <button type="button" class="item btn" data-dismiss="modal">
                                                                             No 
                                                                        </button> &ensp;
                                                                        <button type="button" class="item btn btn-primary" onclick="window.location.href='<?php echo $this->url->get("subscribe/unsubscribe/" . $record->id); ?>'"> 
                                                                            Yes
                                                                        </button> 
                                                                    </div>
                                                                </div>
            
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                                    
                                                    
                                                    
                                                </tr>
                                            </tbody>
                                             <?php } ?>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">

                <ul class="pager">
                        <li><?php echo "You are in page ", $News->current, " of ", $News->total_pages; ?></li>
                        <li><a href="<?php echo $this->url->get("subscribe/subscription" ); ?>">First</a></li>
                        <li><a href="<?php echo $this->url->get("subscribe/subscription?page=" . $News->before); ?>">Previous</a></li>
                        <li><a href="<?php echo $this->url->get("subscribe/subscription?page=" . $News->next); ?>">Next</a></li>
                        <li><a href="<?php echo $this->url->get("subscribe/subscription?page=" . $News->last); ?>">Last</a></li>            
                </ul>

            </div>

        </div> <!---Container item-area !-->
    </div> 

    

</div>

</div>

    

    

    


</div>



