<?php echo \Phalcon\Tag::stylesheetLink("main/css/signin.css"); ?>
<style>
#signin{
	margin-left: 44px;
	margin-top: 40px;
	height:650px;
}

#comment{
	margin-top: 15px;
}

.alert{
	margin-bottom: 0px;
}


</style>

<div class="container">
			
	<div class="col-md-6" id="signin">
		<div class="page-header">
			<h3 class="customers">Contact US</h3>
			<div class="seperator-dotted"></div>
				<h4>Email Address is required</h4>
				<?php echo $this->getContent(); ?>
					
		</div>
		<form action="<?php echo $this->url->get().'contact/contact/';?>" class="form-inline" method="post" autocomplete="on">
			<fieldset>
				<div class="col-md-12">
					<div class="control-group">

									
						<div class="controls">
							<?php echo $form->render("email"); ?>
								<?php
								$message = $form->getMessagesFor('email');
			            			foreach ($message as $m) {
			                 	?>
			                 <div class="alert alert-danger form-element"><?php echo $m; ?></div>
			         			<?php } ?>
						</div>
					</div>
				</div>


					<div class="col-md-12">
						<div class="control-group">
							</br>
									
							<div class="controls">
								<?php echo $form->render("comments"); ?>
								<?php
								$message = $form->getMessagesFor('comments');
			            			foreach ($message as $m) {
			                 	?>
			                 <div class="alert alert-danger form-element"><?php echo $m; ?></div>
			         			<?php } ?>
							</div>
						</div>
					</div>

							
					</br>
							

					<div class="col-md-6" id="comment">
								
						<input type="submit" value="Send" class="btn btn-lg btn-custom red" pb-role="submit">
								
					</div>

							


			</fieldset>

		</form>

	</div>

			

</div>