
<style type="text/css">
.hover {
    display: inline-block;
    overflow: hidden;
    position: relative;
  text-decoration:none;
  
}
.hover .text {
    display: none;
    background: rgba(0,0,0,0.5);
  
    opacity: 0;
    position: absolute;
    width: 100%;
    height:100%;
    color: #ffffff;
    text-align:center;
    left: 0;
    top: 0;
  
   -webkit-transition: opacity 500ms;
     -moz-transition: opacity 500ms;
     -o-transition: opacity 500ms;
     transition: opacity 500ms;
}
.hover:hover .text { display: block; opacity: 1;}

.text .top_text{margin-top: 35%;}

.text .bottom_text{margin-top: 40%;}

.text .bottom_text2{margin-top: 20%;}

.cart, .wish, .wishB, .cartB{background-color: #454545; border:none; }

.modal-margin-top{
  margin-top: 40%;
}

</style>

<script type="text/javascript">

function processWishB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find1 = id.toString().concat(id.toString()); 
  var find11 = find1.toString().concat(id.toString());

    $.ajax({

        type: "POST",
        url: base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find11).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            //console.log(find);
            //alert("result");
           // console.log(result);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       if (result=="1") {$('#notLoggedInModal').modal('show');}
       else if (result=="2") {$('#productInWishlistModal').modal('show');}
       else if (result=="3") {$('#productAddedInWishlist').modal('show');}
 
    });


    }

$(function(){
$('.wishB').on('click', function(e) {

//subcategories();
 var wishIdB = e.target.id;
 var wishIdB1 = wishIdB.toString().split(":")[0]; 

 //clicked(idClicked);
 processWishB(wishIdB1);

  });


});



function processCartB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var p_idB = id.toString().split(":")[0]; 

  var msgB = p_idB.toString().concat(p_idB.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/addtocart",
        data: { data1 : p_idB, },
        success: function(result)
        {
            //$("#my_count").html(html);
            if(result!="")
              $("#my_count").html(result);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(p_idB);
        }
      })
    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       //if (result=="") {$('#productExistCartModal').modal('show');}
       //else {$('#productAddedCartModal').modal('show');}
 
    });


    //alert(id);

   
    }

$(function(){
$('.cartB').on('click', function(e) {

//subcategories();
 var cartIdB = e.target.id;
 //var cartIdB1 = cartIdB.toString().split(":")[0];
 //var cartIdB = $(this).attr('href');
 //clicked(idClicked);
 processCartB(cartIdB);

 //Fly effect

 var cart = $('.shopping-cart .glyphicon-shopping-cart');
        var imgtodrag = $(this).parent().parent().siblings(".img-responsive").eq(0);
        //var src = imgtodrag.attr("src");
        //console.log("fly");
        //console.log(src);
        if (imgtodrag) {
            var imgclone = imgtodrag.clone()
                .offset({
                top: imgtodrag.offset().top,
                left: imgtodrag.offset().left
            })
                .css({
                'opacity': '0.5',
                    'position': 'absolute',
                    'height': '150px',
                    'width': '150px',
                    'z-index': '100'
            })
                .appendTo($('body'))
                .animate({
                'top': cart.offset().top + 10,
                    'left': cart.offset().left + 10,
                    'width': 250,
                    'height': 400
            }, 1000, 'easeInOutExpo');
            
            setTimeout(function () {
                cart.parent().effect("shake", {
                    times: 2
                }, 200);
            }, 1500);

            imgclone.animate({
                'width': 0,
                    'height': 0
            }, function () {
                $(this).detach()
            });
        }

  });
});


</script>







<style type="text/css">
.search-box{
  border: 1px solid #dadada;
  width: 100%;
  margin-top: 20px;
  padding: 5px;
}

.search-box-text{
  color: #595959;
  font-size: 14px;
}

.bg-button {
    background-color: #909090;
    color: white;
    font-size: 16px;
}
</style>


<div class="container bottom-item-area">

	<div class="col-md-3">    
       <div class="search-box">REFINE BY</div>
      
       <form id='search-form' action="" mathod="get">
      	<p><br><span class="caret"></span>MAKE UP <br></p>

        <div class="search-box search-box-text">

      	 <div style="overflow-y:scroll; height:210px;">
      	  
          <?php echo $form->render("accessories"); ?>
          <label>Accessories</label> <br>

          <?php echo $form->render("bronzers_and_blushers"); ?>
          <label>Bronzers & Blushers</label> <br>

          <?php echo $form->render("eye_lashes"); ?>
          <label>Eye Lashes</label> <br>

          <?php echo $form->render("eye_liners"); ?>
          <label>Eye Liners & Eye Brows</label> <br>

          <?php echo $form->render("eye_shadow"); ?>
          <label>Eye Shadows</label> <br>

          <?php echo $form->render("foundation"); ?>
          <label>Foundations & Concealers</label> <br>

          <?php echo $form->render("illuminator"); ?>
          <label>Illuminators & Primers</label> <br>

          <?php echo $form->render("lip_gloss"); ?>
          <label>Lip Gloss & Balm </label> <br>

          <?php echo $form->render("lip_stick"); ?>
          <label>Lip Stick</label> <br>

         </div>

        </div>



        <p><br><span class="caret"></span>PRICE RANGE <br></p>

        <div class="search-box" style="padding:10px;"> 
         
         <span style="display: inline-block; width: 100%; padding: 0 5px;">
          <input id="Slider1" type="slider" name="price"
          <?php if(isset($range['low']) && isset($range['high'])) 
                  $temp = $range['low'].";".$range['high'];

                  else $temp = "1000;60000"; 
          ?> 
          value="<?php echo $temp; ?>" 
          />  
         </span>
    
        
         <input type="hidden" id="limit_low" name="limit_low" value="">
         <input type="hidden" id="limit_high" name="limit_high" value="">

         <script type="text/javascript" charset="utf-8">
         jQuery("#Slider1").slider({ from: 1000, to: 100000, step: 500, smooth: true, round: 0, dimension: "&nbsp;$", skin: "plastic" ,  onstatechange: function( value ){
          $('#limit_low').val(value.split(";")[0]);
          $('#limit_high').val(value.split(";")[1]);
          }
          });
          </script>

         <p></p>

         <button class="btn btn-default bg-button form-control" type="submit" style="width:60%;"> Check </button>
        </div>
        
        

        <p><br><span class="caret"></span>BRAND <br></p>

        <div class="search-box search-box-text">
         <div style="overflow-y:scroll; height:210px;">
      	  
      	  
          <?php echo $form->render("pop"); ?>
          <label>Pop</label> <br>

          <?php echo $form->render("ren"); ?>
          <label>Ren</label> <br>

          <?php echo $form->render("rimmel_london"); ?>
          <label>Rimmel London</label> <br>

          <?php echo $form->render("river_island"); ?>
          <label>River Island</label> <br>

          <?php echo $form->render("rodial"); ?>
          <label>Eye Rodial</label> <br>

          <?php echo $form->render("rose_and_co"); ?>
          <label>Rose & Co</label> <br>

          <?php echo $form->render("stilla"); ?>
          <label>Stilla</label> <br>

          <?php echo $form->render("ted_baker"); ?>
          <label>Ted Baker </label> <br>

          <?php echo $form->render("the_balm"); ?>
          <label>the Balm</label> <br>
         </div>
        </div>



        <p><br><span class="caret"></span>COLOUR<br></p>
      	  
      	<div class="search-box search-box-text">  
          <?php echo $form->render("beige"); ?>
          <label>Beige</label> <br>

          <?php echo $form->render("blue"); ?>
          <label>Blue</label> <br>

          <?php echo $form->render("clear"); ?>
          <label>Clear</label> <br>

          <?php echo $form->render("cream"); ?>
          <label>Cream</label> <br>

          <?php echo $form->render("green"); ?>
          <label>Green</label> <br>
        </div>

        <p><br><span class="caret"></span>STYLE<br></p>

      	<div class="search-box search-box-text">  
      	  
          <?php echo $form->render("beige"); ?>
          <label>Body & Face</label> <br>

          <?php echo $form->render("blue"); ?>
          <label>Cleanse & Tone</label> <br>
        </div>

        </form>
      
      

    </div>



    <div class="col-md-9">
      <div class="row product">
       <?php foreach ($Product->items as $row){?>
        <div class="col-md-3 hover">
          <div class="item">
        <div class="text"><p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".substr($row->product_description,0,19).'..'; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          <div id="<?php echo $row->id.$row->id.$row->id; ?>"> </div>
          <div class="bottom_text2">
            <button class="cartB" id="<?php echo $row->id.":".$row->id.":".$row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp; Add to Cart
            </button>
            &ensp; <i class="fa fa-minus fa-rotate-90"></i> &ensp;
            <button class="wishB" id="<?php echo $row->id.":".$row->id; ?>" type="button">
              <span class="glyphicon glyphicon-heart"></span>
            </button>
          </div>
        </div>            


            <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>"></img>
            <div class="product-name"><?php echo substr($row->product_name,0,18);?></div>
            <div class="product-price">$<?php echo $row->price; ?></div>
          </div>
        </div>
       <?php }?>
         
      </div> <!-- row ends !-->
      <div class="row">
       <div class="col-md-10 col-md-offset-2">
      	<ul class="pager"  style="text-align: left; margin: 10px 0;">
            <li><?php echo "You are in page ", $Product->current, " of ", $Product->total_pages; ?></li>
            <li><a href="<?php echo $this->url->get("category/index/".$data['category_id']); ?>">First</a></li>
            <li><a href="<?php echo $this->url->get("category/index/".$data['category_id']."?page=" . $Product->before); ?>">Previous</a></li>
            <li><a href="<?php echo $this->url->get("category/index/".$data['category_id']."?page=" . $Product->next); ?>">Next</a></li>
            <li><a href="<?php echo $this->url->get("category/index/".$data['category_id']."?page=" . $Product->last); ?>">Last</a></li>   
       </ul>
       </div>
      </div>



    </div>
    
  </div>

    

  <?php echo $this->partial('shared/ad'); ?>

<!--Modals !-->

<div class="modal fade" id="notLoggedInModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> You need to log in first. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productInWishlistModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> This product already exists in your wish list. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productAddedInWishlist" tabindex="-1" role="dialog" aria-labelledby="productAddedInWishlist" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Wish list updated successfully. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>


<div class="modal fade" id="productAddedCartModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Product successfully added to the cart</center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productExistCartModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Quantity incremented for this product. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>




