
<style type="text/css">
.hover2 {
    display: inline-block;
    overflow: hidden;
    position: relative;
    text-decoration:none;
    min-height: 312px;
    vertical-align: top;

  
}
.hover .text {
   
    background: rgba(0,0,0,0.5);
  
    opacity: 0;
    position: absolute;
    width: 86%;
    height:95%;
    color: #ffffff;
    text-align:center;
    left: 15px;
    top: 18px;
  
    -webkit-transition: opacity 500ms;
    -moz-transition: opacity 500ms;
    -o-transition: opacity 500ms;
     transition: opacity 500ms;
}



.product .item{
  margin-bottom: 0px;
}


.bottom_text2{
  margin-bottom: 0px;
  margin-left: 0;
  width:104%;
}

.cart, .cartB{
  background-color: #bcbcbc;
  border:none; 
  padding: 7px 5px; 
  
  color:#fff;
  margin-left: -5px;
  margin-right: -3px;
  border:1px dotted #a8a8a8;
}
.wish,.wishB{
  background-color: #bcbcbc;
  border:none; 
  padding: 7px 4px;
  margin-left: 0px; 
  color:#fff;
  border:1px dotted #a8a8a8;
}



#product_hov{

  margin-bottom: 0;
}

.modal-footer {
    border-top: none;
    margin-top: -25px;
    padding: 0px;
    text-align: center;
}

.bottom-item-area .product .item{

  margin-bottom: 25px;

}



</style>

<script type="text/javascript">

function processWishB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find1 = id.toString().concat(id.toString()); 
  var find11 = find1.toString().concat(id.toString());

    $.ajax({

        type: "POST",
        url: base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find11).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            //console.log(find);
            //alert("result");
           // console.log(result);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       if (result=="1") {$('#notLoggedInModal').modal('show');
        setTimeout( "jQuery('#notLoggedInModal').modal('hide');",3000 );
      }
       else if (result=="2") {$('#productInWishlistModal').modal('show');
        setTimeout( "jQuery('#productInWishlistModal').modal('hide');",3000 );
      }
       else if (result=="3") {$('#productAddedInWishlist').modal('show');
       setTimeout( "jQuery('#productAddedInWishlist').modal('hide');",3000 );
     }
 
    });


    }

$(function(){
$('.wishB').on('click', function(e) {

//subcategories();
 var wishIdB = e.target.id;
 var wishIdB1 = wishIdB.toString().split(":")[0]; 

 //clicked(idClicked);
 processWishB(wishIdB1);

  });


});



function processCartB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var p_idB = id.toString().split(":")[0]; 

  var msgB = p_idB.toString().concat(p_idB.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/addtocart",
        data: { data1 : p_idB, },
        success: function(result)
        {
            //$("#my_count").html(html);
            if(result!="")
              $("#my_count").html(result);

            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(p_idB);
        }
      })
      .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);





       //if (result=="") {$('#productExistCartModal').modal('show');}
       //else {$('#productAddedCartModal').modal('show');}
 
    });


    //alert(id);

   
    }

$(function(){
$('.cartB').on('click', function(e) {

//subcategories();
 var cartIdB = e.target.id;
 //var cartIdB1 = cartIdB.toString().split(":")[0];
 //var cartIdB = $(this).attr('href');
 //clicked(idClicked);
 processCartB(cartIdB);

 //Fly effect

 var cart = $('.shopping-cart-button .glyphicon-shopping-cart');
        var imgtodrag = $(this).parent().siblings(".drag").children(".img-responsive").eq(0);
        //var src = imgtodrag.attr("src");
        //console.log("fly");
        //console.log(src);
        if (imgtodrag) {
            var imgclone = imgtodrag.clone()
                .offset({
                top: imgtodrag.offset().top,
                left: imgtodrag.offset().left
            })
                .css({
                'opacity': '0.5',
                    'position': 'absolute',
                    'height': '150px',
                    'width': '150px',
                    'z-index': '100'
            })
                .appendTo($('body'))
                .animate({
                'top': cart.offset().top + 10,
                    'left': cart.offset().left + 10,
                    'width': 250,
                    'height': 400
            }, 1000, 'easeInOutExpo');
            
            setTimeout(function () {
                cart.parent().effect("shake", {
                    times: 2
                }, 200);
            }, 1500);

            imgclone.animate({
                'width': 0,
                    'height': 0
            }, function () {
                $(this).detach()
            });
        }

  });
});


</script>



<style type="text/css">
.search-box{
  border: 1px solid #dadada;
  width: 100%;
  margin-top: 20px;
  padding: 5px;
}

.search-box-text{
  color: #595959;
  font-size: 14px;
}

.bg-button {
    background-color: #909090;
    color: white;
    font-size: 16px;
}


</style>

<script type="text/javascript">

  $(document).ready(function() {
     $('.bottom_text2').hide();

     $('.hover2').hover(
         function () {
           //$(this).addClass("open");
            var id = $(this).attr('id');
            console.log(id);
            
             $('#'+id).children().children(".bottom_text2").show();
             
              
            
         }, 
         function () {
           //$(this).removeClass("open");
             $('.bottom_text2').hide();
             
         }
     );


    });

</script>

<script type="text/javascript">

 function submit_form(){
  //document.getElementById("search-form").submit();
  $("#search-form").submit();
 }

</script>

<div class="container bottom-item-area">

  <div class="col-md-3">    
       <div class="search-box">REFINE BY</div>
      
       <form id='search-form' action="" mathod="get">
        <p><br><span class="caret"></span>SHOP <br></p>

        <div class="search-box search-box-text">

         <div style="overflow-y:scroll; height:210px;">
          <?php 
             foreach ($shop_names as $id => $name) {
               # code...
              if ((isset($data['checked'])) && ($data['checked'] == $id)) {
                # code...
                echo '<input type="radio" name="shop_id" checked="checked" onchange="submit_form()" value="'.$id.'">';
              }
              else{
                echo '<input type="radio" name="shop_id" onchange="submit_form()" value="'.$id.'">';
              }
              echo '<label>'.'&nbsp;'.$name.'</label><br>';
             }

             //echo $shop_id_checked;

          ?>
         </div>

        </div>


        <p><br><span class="caret"></span>MAKE UP <br></p>

        <div class="search-box search-box-text">

         <div style="overflow-y:scroll; height:210px;">
          
          <?php echo $form->render("accessories"); ?>
          <label>Accessories</label> <br>

          <?php echo $form->render("bronzers_and_blushers"); ?>
          <label>Bronzers & Blushers</label> <br>

          <?php echo $form->render("eye_lashes"); ?>
          <label>Eye Lashes</label> <br>

          <?php echo $form->render("eye_liners"); ?>
          <label>Eye Liners & Eye Brows</label> <br>

          <?php echo $form->render("eye_shadow"); ?>
          <label>Eye Shadows</label> <br>

          <?php echo $form->render("foundation"); ?>
          <label>Foundations & Concealers</label> <br>

          <?php echo $form->render("illuminator"); ?>
          <label>Illuminators & Primers</label> <br>

          <?php echo $form->render("lip_gloss"); ?>
          <label>Lip Gloss & Balm </label> <br>

          <?php echo $form->render("lip_stick"); ?>
          <label>Lip Stick</label> <br>

         </div>

        </div>



        <p><br><span class="caret"></span>PRICE RANGE <br></p>

        <div class="search-box" style="padding:10px;"> 
         
         <span style="display: inline-block; width: 100%; padding: 0 5px;">
          <input id="Slider1" type="slider" name="price"
          <?php if(isset($range['low']) && isset($range['high'])) 
                  $temp = $range['low'].";".$range['high'];

                  else $temp = "0;100000"; 
          ?> 
          value="<?php echo $temp; ?>" 
          />  
         </span>
    
        
         <input type="hidden" id="limit_low" name="limit_low" value="">
         <input type="hidden" id="limit_high" name="limit_high" value="">

         <script type="text/javascript" charset="utf-8">
         jQuery("#Slider1").slider({ from: 0, to: 100000, step: 500, smooth: true, round: 0, dimension: "&nbsp;$", skin: "plastic" ,  onstatechange: function( value ){
          $('#limit_low').val(value.split(";")[0]);
          $('#limit_high').val(value.split(";")[1]);
          }
          });
          </script>

         <p></p>

         <button class="btn btn-default bg-button form-control" type="submit" style="width:60%;"> Check </button>
        </div>
        
        

        <p><br><span class="caret"></span>BRAND <br></p>

        <div class="search-box search-box-text">
         <div style="overflow-y:scroll; height:210px;">
          
          
          <?php echo $form->render("pop"); ?>
          <label>Pop</label> <br>

          <?php echo $form->render("ren"); ?>
          <label>Ren</label> <br>

          <?php echo $form->render("rimmel_london"); ?>
          <label>Rimmel London</label> <br>

          <?php echo $form->render("river_island"); ?>
          <label>River Island</label> <br>

          <?php echo $form->render("rodial"); ?>
          <label>Eye Rodial</label> <br>

          <?php echo $form->render("rose_and_co"); ?>
          <label>Rose & Co</label> <br>

          <?php echo $form->render("stilla"); ?>
          <label>Stilla</label> <br>

          <?php echo $form->render("ted_baker"); ?>
          <label>Ted Baker </label> <br>

          <?php echo $form->render("the_balm"); ?>
          <label>the Balm</label> <br>
         </div>
        </div>



        <p><br><span class="caret"></span>COLOUR<br></p>
          
        <div class="search-box search-box-text">  
          <?php echo $form->render("beige"); ?>
          <label>Beige</label> <br>

          <?php echo $form->render("blue"); ?>
          <label>Blue</label> <br>

          <?php echo $form->render("clear"); ?>
          <label>Clear</label> <br>

          <?php echo $form->render("cream"); ?>
          <label>Cream</label> <br>

          <?php echo $form->render("green"); ?>
          <label>Green</label> <br>
        </div>

        <p><br><span class="caret"></span>STYLE<br></p>

        <div class="search-box search-box-text">  
          
          <?php echo $form->render("beige"); ?>
          <label>Body & Face</label> <br>

          <?php echo $form->render("blue"); ?>
          <label>Cleanse & Tone</label> <br>
        </div>

        </form>
      
      

    </div>



    <div class="col-md-9">
      <div class="row product">
       <?php foreach ($Product->items as $row){?>
       
        <div class="col-md-3 hover2" id="<?php echo $row->id ; ?>" >
         
          <div class="item">
 
            <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>" class="drag">
              <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>"></img>
            </a>
            <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>">
              <div class="product-name"><?php echo substr($row->product_name,0,18);?></div>
            </a>
            
            <div class="product-price">$<?php echo $row->price; ?></div>

            <div class="bottom_text2" id="<?php echo $row->id ; ?>">
              <button class="cartB" id="<?php echo $row->id.":".$row->id.":".$row->id;?>" type="button" name="submit" value="test">
                <span class="glyphicon glyphicon-shopping-cart"></span>&ensp; Add to cart &ensp;
              </button>
              <button class="wishB" id="<?php echo $row->id.":".$row->id; ?>" type="button">
               <span>Add to Wishlist</span>
              </button>

            </div>
            
          </div>

        </div>
      
       <?php }?>
         
      </div> <!-- row ends !-->
      <div class="row" style="padding-top: 50px;">
       <div class="col-md-10 col-md-offset-2">
        <ul class="pager"  style="text-align: left; margin: 10px 0;">
            <li><?php echo "You are in page ", $Product->current, " of ", $Product->total_pages; ?></li>
            <li><a href="<?php echo $this->url->get("category/index/".$data['category_id']); ?>">First</a></li>
            <li><a href="<?php echo $this->url->get("category/index/".$data['category_id']."?page=" . $Product->before); ?>">Previous</a></li>
            <li><a href="<?php echo $this->url->get("category/index/".$data['category_id']."?page=" . $Product->next); ?>">Next</a></li>
            <li><a href="<?php echo $this->url->get("category/index/".$data['category_id']."?page=" . $Product->last); ?>">Last</a></li>   
       </ul>
       </div>
      </div>



    </div>
    
  </div>

    

  <?php echo $this->partial('shared/ad'); ?>

<!--Modals !-->

<div class="modal fade" id="notLoggedInModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> You need to log in first. </center> 
                </p>
            </div>

            <div class="modal-footer">
              <a href="<?php echo $this->url->get().'session/index/';?>" class="btn btn-md btn-primary">

                Sign In
              </a>
            </div>
            
        </div>
  </div>
</div>

<div class="modal fade" id="productInWishlistModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> This product already exists in your wish list. </center> 
                </p>
            </div>

            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'wishlist/wish/';?>">

                Checkout
              </a>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productAddedInWishlist" tabindex="-1" role="dialog" aria-labelledby="productAddedInWishlist" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> Wish list updated successfully. </center> 
                </p>
            </div>

            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'wishlist/wish/';?>">

                Checkout
              </a>
            </div>
            
    </div>
  </div>
</div>


<div class="modal fade" id="productAddedCartModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Product successfully added to the cart</center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productExistCartModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Quantity incremented for this product. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>




