<?php echo \Phalcon\Tag::stylesheetLink("main/css/myaccount.css"); ?>
<?php echo \Phalcon\Tag::stylesheetLink("public/main/css/common.css"); ?>


<style>

.panel-group > .panel panel-default {
    background-color: #FFFFFF;
}

.highlight{
    border:1px solid red ;
}

.shopping-text{
    text-decoration: none;
}

a{
    color:#870415;
    font-size: 15px;
    text-decoration: none;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}

.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}

.seperator-dotted{
    width: 100%;
    border-bottom: 1px solid #ECECEC;
    margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}

.gray{

    background-color:#FFFFFF;
    color:#042C51;
}

.gray:hover{
    background-color:#F7FAFC;
    color:#84660A;
}

.title{
    padding:8px;

}

.seperator-dotted2{
    width: 93%;
    border-bottom: 1px solid #ECECEC;
    margin: 0px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    cursor:pointer;
    height: 49px;
}

.panel-default > .panel-heading:hover{
    border:1px solid red ;
    background-color: #FFFFFF;
    color: #333;

}

.status{
    font-size: 15px;
}
.left-menu{
    display:table-row;
}


.row {
    margin-left: 3px;
    margin-right: -15px;
}

.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}

.info{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 55px;
    width: 95%;
    padding-top: 15px;
    padding-right: 10px;
    padding-bottom: 15px;
    padding-left: 10px;


}

.item-area{

    text-align: center;

}

strong > a{

    color:#A8A8A8;
    font-size: 15px;
    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px;

}

strong > a:hover{

    background-color: #52575F;
    color: white;
}



.shopping-text>a{
    color:#000000;
    text-decoration: underline;
}

.green{
     background-color: #339966;

}

.start{
    padding-left: 10px;
    padding-top: 10px;
    color:#000000;
    font-size: 15px;
    height:82px;
}

.navbar {
    background-color: #FFFFFF;
    margin-bottom: 0px;
}

.pager{
    color:#000000;
}
li>a{
    color: #106E96;
}

</style>
<!-- main body part -->
<div class="container">
<div class="container fixed-container">
	<!-- left menu start here -->
	<div class="col-md-3 left-menu">
		<div class="title"><h3>&ensp; &ensp; &ensp; &ensp; &ensp; &ensp;</h3></div>
    		<div class="panel-group row" id="accordion">
                
    		
    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get().'accdashboard/dashinfo/'; ?>"  >
    			     <div class="panel panel-default" id="accdashboard">
                            <div class="panel-heading">
                                   
                                    <div class="panel-title">
                                        
                                        Account Dashboard
                                        
                                    </div>
                                   
                            </div>
    							
    					
                        </div>
                </a>

    			 <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("accinfo/accinfo/") ?>" >			
        			<div class="panel panel-default" id="accinfo">
                                    <div class="panel-heading">
                                       
                                        <div class="panel-title">
                                           
                                            Account Information
                                           
                                        </div>
                                       
                                    </div>
                                </div>
                         </a>

    			 <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("address/address/") ?>" >			
    			     <div class="panel panel-default" id="address">
                                <div class="panel-heading">
                                    
                                    <div class="panel-title">
                                           
                                            Address Book
                                            
                                    </div>
                                   
                                </div>
                            </div>
                    </a>

    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("order/order/") ?>" >			
    			     <div class="panel panel-default" id="order">
                                <div class="panel-heading">
                                   
                                    <div class="panel-title">
                                            
                                            My Orders
                                            
                                    </div>
                                    
                                </div>
                            </div>
                    </a>


    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("index/index/") ?>" >			
    			     <div class="panel panel-default" id="bill">
                                <div class="panel-heading">
                                   
                                    <div class="panel-title">
                                            
                                            Billing Aggrements
                                           
                                    </div>
                                   
                                </div>
                            </div>
                     </a>


                <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("shop/shop/") ?>" >           
                     <div class="panel panel-default" id="shop">
                                <div class="panel-heading">
                                   
                                    <div class="panel-title">
                                            
                                            My Shop
                                           
                                    </div>
                                   
                                </div>
                            </div>
                     </a>

    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("inventory/list/") ?>" >			
    			     <div class="panel panel-default" id="inventory">
                                <div class="panel-heading">
                                    
                                    <div class="panel-title">
                                            
                                            My Inventory
                                            
                                    </div>
                                    
                                </div>
                            </div>
                    </a>


    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("wallet/pass/") ?>" >			
    			     <div class="panel panel-default" id="wallet">
                                <div class="panel-heading">
                                   
                                    <div class="panel-title">
                                            
                                            My Wallet
                                           
                                    </div>
                                   
                                </div>
                            </div>
                     </a>


    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("wishlist/wish/") ?>" >			
    			     <div class="panel panel-default" id="wishlist">
                                <div class="panel-heading">
                                   
                                    <div class="panel-title">
                                            
                                            My Wishlists
                                            
                                    </div>
                                   
                                </div>
                            </div>
                    </a>


    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("index/index/") ?>">			
    			     <div class="panel panel-default">
                                <div class="panel-heading">
                                    
                                    <div class="panel-title">
                                            
                                            My Applications
                                           
                                    </div>
                                   
                                </div>
                            </div>
                     </a>

                <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("refer/refer/") ?>" >
                    <div class="panel panel-default" id="refer">
                                <div class="panel-heading">
                                   
                                    <div class="panel-title">
                                            
                                            Referred Friends
                                            
                                    </div>
                                    
                                </div>
                            </div>
                    </a>


                <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("subscribe/subscription/") ?>" >    
                    <div class="panel panel-default" id="subscribe">
                                <div class="panel-heading">
                                    
                                    <div class="panel-title">
                                            
                                            Newsletter Subscriptions
                                            
                                    </div>
                                   
                                </div>
                            </div>
                    </a>

               
    		</div>
		
	</div>
	
	
	<!-- left menu ends here -->
	<div class="col-md-9 right-menu">

                    
					<div class="row text-center title-area">
                        <div class="main-menu-title"><h2><?php echo $title; ?></h2></div>
                        <div class="sub-menu-title">
                            <h4><?php
                                if (isset($action)) {
                                    echo $action;
                                }
                                ?>
                            </h4>
                        </div>
                    </div>

                    


                    <div class="main-area">
<?php echo $this->getContent() ?>
                    </div>


                </div>

	
</div>
</div>
<!-- main body part ends here -->


<!-- main body part ends here -->
<?php echo $this->partial('shared/ad'); ?>



<!-- better i should use switch case here,modify later -->
<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[2];

    console.log(choice);

    if(choice=='accdashboard')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#accdashboard").addClass("highlight");
    }

    else if(choice=='accinfo')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#accinfo").addClass("highlight");
    }

    else if(choice=='address')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#address").addClass("highlight");
    }

    else if(choice=='order')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#order").addClass("highlight");
    }

    else if(choice=='shop')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#shop").addClass("highlight");
    }

    else if(choice=='inventory')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#inventory").addClass("highlight");
    }

    else if(choice=='wallet')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#wallet").addClass("highlight");
    }

    else if(choice=='wishlist')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#wishlist").addClass("highlight");
    }

    else if(choice=='refer')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#refer").addClass("highlight");
    }

    else if(choice=='subscribe')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#subscribe").addClass("highlight");
    }
    else if(choice=='session')
    {
        $("#accdashboard").addClass("highlight");
    }

</script>