<?php echo \Phalcon\Tag::stylesheetLink("main/css/myaccount.css"); ?>
<?php echo \Phalcon\Tag::stylesheetLink("main/css/common.css"); ?>


<style>

.panel-group > .panel panel-default {
    background-color: #FFFFFF;
}

.highlight{
    border:1px solid red ;
}

.shopping-text{
    text-decoration: none;
}

a{
    color:#870415;
    font-size: 15px;
    text-decoration: none;
}



.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}

.seperator-dotted{
    width: 100%;
    border-bottom: 1px solid #ECECEC;
    margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}

.gray{

    background-color:#FFFFFF;
    color:#042C51;
}

.gray:hover{
    background-color:#F7FAFC;
    color:#84660A;
}

.title{
    padding:8px;

}

.seperator-dotted2{
    width: 93%;
    border-bottom: 1px solid #ECECEC;
    margin: 0px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    cursor:pointer;
    height: 49px;
}

.panel-default > .panel-heading:hover{
   
    background-color: #cd2027;
    color: white;

}

.status{
    font-size: 15px;
}
.left-menu{
    display:table-row;
}


.row {
    margin-left: 3px;
    margin-right: -15px;
}

.main-menu-title > h2{
    font-size: 25px;   
    padding-top: 6px;

}

.info{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 55px;
    width: 95%;
    padding-top: 15px;
    padding-right: 10px;
    padding-bottom: 15px;
    padding-left: 10px;


}

.item-area{

    text-align: center;

}

strong > a{

    color:#A8A8A8;
    font-size: 15px;
    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px;

}

strong > a:hover{

    background-color: #52575F;
    color: white;
}



.shopping-text > a{
    color:#000000;
    text-decoration: underline;
}

.green{
     background-color: #339966;

}

.start{
    padding-left: 10px;
    padding-top: 10px;
    color:#000000;
    font-size: 15px;
    height:82px;
}

.navbar {
    background-color: #FFFFFF;
    margin-bottom: 0px;
}

.pager{
    color:#000000;
}
li>a{
    color: #106E96;
}

.submenu .item {
    cursor: pointer;
    padding: 5px;
    text-align: right;
    width: 95%;
}

.collapse.in {
    display: block;
}

.panel-body{
    padding-top: 0;
    padding-bottom: 0;
}

.me_buy{
    color:black;
}
.me_sell{
    color:black;
}

.sub_select{
    
    color:#cd2027;
}


.shopping-cart-button{
    margin-top: 194px;
}

.panel-group .panel{
    border-radius: 0px;
}


</style>
<!-- main body part -->
<div class="container">
<div class="container fixed-container">
	<!-- left menu start here -->
	<div class="col-md-3 left-menu">
		<div class="title"><h3>&ensp; &ensp; &ensp; &ensp; &ensp; &ensp;</h3></div>
    		<div class="panel-group row" id="accordion">
                
    		
    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get().'accdashboard/dashinfo/'; ?>"  >
    			     <div class="panel panel-default"  >
                            <div class="panel-heading" id="accdashboard">
                                   
                                    <div class="panel-title">
                                        
                                        Account Dashboard
                                        
                                    </div>
                                   
                            </div>
    							
    					
                        </div>
                </a>

    			 <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("accinfo/accinfo/") ?>" >			
        			<div class="panel panel-default" >
                                    <div class="panel-heading" id="accinfo">
                                       
                                        <div class="panel-title">
                                           
                                            Account Information
                                           
                                        </div>
                                       
                                    </div>
                                </div>
                </a>

    			 

    						
    			     <div class="panel panel-default" >
                                <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" id="order">
                                   
                                    <div class="panel-title" >
                                        <a href="#">    
                                            My Orders
                                         </a>   
                                    </div>
                                    
                                </div>


                                <div id="collapseOne" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <div class="submenu row">
                                            <a href="<?php echo $this->url->get("order/list"); ?>" class="me_buy" id="list">
                                                <div class="item" >
                                                    Purchase
                                                </div>
                                            </a>
                                            <a href="<?php echo $this->url->get("order/delivery"); ?>" class="me_sell" id="delivery">
                                                <div class="item" >
                                                    Delivery
                                                </div>
                                            </a>                                         
                                        </div>

                                    </div>
                                </div>
                    </div>
                    


    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("index/index/") ?>" >			
    			     <div class="panel panel-default" >
                                <div class="panel-heading" id="bill">
                                   
                                    <div class="panel-title">
                                            
                                            Billing Aggrements
                                           
                                    </div>
                                   
                                </div>
                            </div>
                     </a>


                <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("myshop/myshop/") ?>" >           
                     <div class="panel panel-default" >
                                <div class="panel-heading" id="shop">
                                   
                                    <div class="panel-title" >
                                            
                                            My Shop
                                           
                                    </div>
                                   
                                </div>
                            </div>
                     </a>

    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("inventory/list/") ?>" >			
    			     <div class="panel panel-default" >
                                <div class="panel-heading" id="inventory">
                                    
                                    <div class="panel-title">
                                            
                                            My Inventory
                                            
                                    </div>
                                    
                                </div>
                            </div>
                    </a>


    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("wallet/pass/") ?>" >			
    			     <div class="panel panel-default" >
                                <div class="panel-heading" id="wallet">
                                   
                                    <div class="panel-title">
                                            
                                            My Wallet
                                           
                                    </div>
                                   
                                </div>
                            </div>
                     </a>


    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("wishlist/wish/") ?>" >			
    			     <div class="panel panel-default" >
                                <div class="panel-heading" id="wishlist">
                                   
                                    <div class="panel-title">
                                            
                                            My Wishlists
                                            
                                    </div>
                                   
                                </div>
                            </div>
                    </a>


    			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("index/index/") ?>">			
    			     <div class="panel panel-default">
                                <div class="panel-heading">
                                    
                                    <div class="panel-title">
                                            
                                            My Applications
                                           
                                    </div>
                                   
                                </div>
                            </div>
                     </a>

                <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("refer/refer/") ?>" >
                    <div class="panel panel-default" >
                                <div class="panel-heading" id="refer">
                                   
                                    <div class="panel-title">
                                            
                                            Referred Friends
                                            
                                    </div>
                                    
                                </div>
                            </div>
                    </a>


                <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("subscribe/subscription/") ?>" >    
                    <div class="panel panel-default" >
                                <div class="panel-heading" id="subscribe">
                                    
                                    <div class="panel-title">
                                            
                                            Newsletter Subscriptions
                                            
                                    </div>
                                   
                                </div>
                            </div>
                    </a>

               
    		</div>
		
	</div>
	
	
	<!-- left menu ends here -->
	<div class="col-md-9 right-menu">

                    
					<div class="row text-center title-area">
                        <div class="main-menu-title"><h2><?php echo $title; ?></h2></div>
                        <div class="sub-menu-title">
                            <h4><?php
                                if (isset($action)) {
                                    echo $action;
                                }
                                ?>
                            </h4>
                        </div>
                    </div>

                    


                    <div class="main-area">
<?php echo $this->getContent() ?>
                    </div>


                </div>

	
</div>
</div>
<!-- main body part ends here -->


<!-- main body part ends here -->
<?php echo $this->partial('shared/ad'); ?>



<!-- better i should use switch case here,modify later -->
<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[2];

    console.log(choice);

    if(choice=='accdashboard')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#accdashboard").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='accinfo')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#accinfo").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='address')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#address").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='order')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#order").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='myshop')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#shop").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='inventory')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#inventory").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='wallet')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#wallet").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='wishlist')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#wishlist").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='refer')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#refer").css('background-color','#cd2027').css('color','white');
    }

    else if(choice=='subscribe')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#subscribe").css('background-color','#cd2027').css('color','white');
    }
    else if(choice=='session')
    {
        $("#accdashboard").css('background-color','#cd2027').css('color','white');
    }





</script>

<script type="text/javascript">
            var pathname = window.location.pathname;
            //alert(pathname);
            var patharray = pathname.split("/");
            console.log("path arrray ");
            console.log(patharray);
            $(".panel a").each(function() {
                var href = $(this).attr("href");
                //alert(href);

                var urlArray = href.split("/");
                
                if (urlArray[2] === patharray[2] && urlArray[3] === patharray[3]) {
                    var div = $(this).closest('.collapse');
                    div.addClass('in');


                    
                    


                }



                if (urlArray[2] === patharray[2]) {
                    var div = $(this).closest('.collapse');
                    div.addClass('in');
                }
                

                //alert(urlArray[2]+urlArray[3]);
            });

            



</script>


<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[3];

    console.log(choice);

    if(choice=='list')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#list").addClass("sub_select");
    }

    else if(choice=='delivery')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#delivery").addClass("sub_select");
    }

</script>