<?php echo \Phalcon\Tag::stylesheetLink("main/css/myaccount.css"); ?>
<?php echo \Phalcon\Tag::stylesheetLink("main/css/common.css"); ?>
<style>
.panel-group > .panel panel-default {
    background-color: #FFFFFF;
}
.red{
    background-color: red;
}
</style>
<!-- main body part -->
<div class="container">
<div class="container fixed-container">
	<!-- left menu start here -->
	<div class="col-md-3 left-menu">
		<div class="title"><h3>&ensp; &ensp; &ensp; &ensp; &ensp; &ensp;</h3></div>
		<div class="panel-group row" id="accordion">
		
			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get().'accdashboard/dashinfo/'; ?>" >
			     <div class="panel panel-default">
                        <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        Account Dashboard
                                    
                                </div>
                        </div>
							
					
                    </div>
            </a>

			 <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("accinfo/accinfo/") ?>">			
    			<div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="panel-title">
                                       
                                            Account Information
                                       
                                    </div>
                                </div>
                            </div>
                     </a>

			 <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("address/address/") ?>">			
			     <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                   
                                        Address Book
                                    
                                </div>
                            </div>
                        </div>
                </a>

			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("order/order/") ?>" >			
			     <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        My Orders
                                    
                                </div>
                            </div>
                        </div>
                </a>


			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("index/index/") ?>">			
			     <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        Billing Aggrements
                                   
                                </div>
                            </div>
                        </div>
                 </a>

			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("inventory/list/") ?>">			
			     <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        My Inventory
                                    
                                </div>
                            </div>
                        </div>
                </a>


			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("wallet/pass/") ?>">			
			     <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        My Wallet
                                   
                                </div>
                            </div>
                        </div>
                 </a>


			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("wishlist/wish/") ?>">			
			     <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        My Wishlists
                                    
                                </div>
                            </div>
                        </div>
                </a>


			<a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("index/index/") ?>">			
			     <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        My Applications
                                   
                                </div>
                            </div>
                        </div>
                 </a>

            <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("refer/refer/") ?>">
                <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        Referred Friends
                                    
                                </div>
                            </div>
                        </div>
                </a>


            <a data-toggle="" data-parent="#accordion" href="<?php echo $this->url->get("subscribe/subscription/") ?>">    
                <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    
                                        Newsletter Subscription
                                    
                                </div>
                            </div>
                        </div>
                </a>
		
		</div>
		
	</div>
	
	
	<!-- left menu ends here -->
	<div class="col-md-9 right-menu">

                    
					<div class="row text-center title-area">
                        <div class="main-menu-title"><h2><?php echo $title; ?></h2></div>
                        <div class="sub-menu-title">
                            <h4><?php
                                if (isset($action)) {
                                    echo $action;
                                }
                                ?>
                            </h4>
                        </div>
                    </div>

                    


                    <div class="main-area">
<?php echo $this->getContent() ?>
                    </div>


                </div>

	
</div>
</div>
<!-- main body part ends here -->



<?php echo $this->partial('shared/ad'); ?>

