<style>
.info2{
    height:435px;
}

</style>
<div class="row-cell">

    <div class="item-area">
       <div class="col-md-12"> 
            <div class="col-md-6 col-md-offset-1">
                <div class="info">
                    <Strong> Product Name: </strong><?php echo $heading;?>
                </div>
                <div class="info">
                    <Strong> Description: </strong><?php echo $description;?>
                </div>

                <div class="info">
                    <Strong> Price: </strong><?php echo $price;?>
                </div>

                <div class="info">
                    <Strong> Creation: </strong><?php echo $created_at;?>
                </div>

                <div class="info">
                    <Strong> Stock Quantity: </strong><?php echo $in_stock;?>
                </div>

                <div class="info">
                    <Strong> Discount Rate: </strong><?php echo $discount;?>
                </div>
                <div class="info">
                    <Strong>Least Orders To be served:</strong> <?php echo $minimum_order_level; ?>
                </div>
                <div class="info">
                <a href="<?php echo $this->url->get("inventory/edit/".$id); ?>" class="edit" >
                    Edit Product 
                </a>
                </div>
            </div>

            <div class="col-md-5">
                <div class="info2">
                    <img src="<?php echo $this->url->get().$picture;?>" height="100%" width="100%">
                </div>

            </div>


    </div>
    

</div>