<style>

.nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background-color: #fff;
    border-color: #fff #fff transparent;
   
   border-style: solid;
    border-width: 0px;
    color: #fff;
    cursor: default;
}
table{
    border-collapse: separate;
}


</style>
<?php echo \Phalcon\Tag::stylesheetLink("main/css/list.css"); ?>

<div class="row-cell">
    <div class="tabbable">
        <div class="mid-menu">
          <ul class="nav nav-tabs">
            
            <li class="active"><a href="#pane1" data-toggle="tab"><div class="item">All</div></a></li>
            <li><a href="#pane2" data-toggle="tab"><div class="item">Most Selling</div></a></li>
            <li><a href="#pane3" data-toggle="tab"><div class="item">Most Valuable</div></a></li>
          </ul>
        </div>

    <div class="red-joint"></div>
    <div class="tab-content">
        <div id="pane1" class="tab-pane active">
            <div class="container item-area">
                <div class="col-md-8">
                    <div class="panel panel-default">
                        <div class="panel-heading" id="heading">
                            My Products
                        </div>
                    <div class="panel-body">
                        <div class="table-responsive">

                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Name</th>
                                                <th>Image</th>
                                                
                                                <th>Shop</th>
                                                <th>Price</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                         <?php 
                                         $count=0;
                                         foreach ($Product->items as $record) { 
                                                $count++;
                                            ?>
                                         <tbody>
                                            <tr>
                                                <td><?php echo $count; ?></td>
                                                <td>
                                                    <strong>
                                                        <a href="<?php echo $this->url->get("inventory/details/" . $record->id); ?>" id="name">
                                                            <?php echo $record->product_name; ?>
                                                        </a>
                                                    </strong>
                                                </td>
                                                <td>
                                                    <?php if (!isset($record->picture)) { ?>
  
                                                    <img src="<?php echo $this->url->get().'main/images/';?>shop_banner.jpg" class="img-responsive" alt="..." width="50px" style="height:40px;">

                                                    <?php } else { ?>

                                                    <img src="<?php echo $this->url->get().$record->picture;?>" class="img-responsive" alt="..."  width="50px" style="height:40px;">

                                                    <?php } ?>
                                                </td>
                                                <td>
                                                     <a href="<?php echo $this->url->get("myshop/details/" . $record->sid); ?>">
                                                     <?php echo $record->shop_name;?>
                                                    </a>
                                                </td>

                                                 <td>
                                                     <?php echo $record->price;?>
                                                </td>
                                                <td>
                                                    <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>"><p>Status</p></a>
                                                </td>
                                                 <td>
                                                    <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>">
                                                        <i class="glyphicon glyphicon-pencil" id="pencil" ></i>
                                                    </a>
                                                    <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>">
                                                        <i class="delete fa fa-trash-o fa-lg" ></i>
                                                    </a>

                                                </td>
                                                
                                                
                                            </tr>
                                        </tbody>
                                         <?php } ?>
                                </table>

                            </div>
                        </div>

                    </div>
                    </div>
                </div>

            <div class="col-md-8">

                <ul class="pager">
                        <li><?php echo "You are in page ", $Product->current, " of ", $Product->total_pages; ?></li>
                        <li><a href="<?php echo $this->url->get("inventory/list" ); ?>">First</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Product->before); ?>">Previous</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Product->next); ?>">Next</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Product->last); ?>">Last</a></li>            
                </ul>

            </div>
        </div> <!---Container item-area !-->

    </div> <!---pane1 !-->


    <div id="pane2" class="tab-pane">
        <div class="container item-area">
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading" id="heading">
                        Most Selling Products
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">

                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Name</th>
                                                    <th>Image</th>
                                                    
                                                    <th>Shop</th>
                                                    <th>Price</th>
                                                    <th>Status</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                             <?php 
                                             $count=0;
                                             foreach ($selling->items as $record) { 
                                                    $count++;
                                                ?>
                                             <tbody>
                                                <tr>
                                                    <td><?php echo $count; ?></td>
                                                    <td>
                                                        <strong>
                                                            <a href="<?php echo $this->url->get("inventory/details/" . $record->id); ?>">
                                                                <?php echo $record->product_name; ?>
                                                            </a>
                                                        </strong>
                                                    </td>
                                                    <td>
                                                        <?php if (!isset($record->picture)) { ?>
  
                                                    <img src="<?php echo $this->url->get().'main/images/';?>shop_banner.jpg" class="img-responsive" alt="..." width="50px" style="height:40px;">

                                                    <?php } else { ?>

                                                    <img src="<?php echo $this->url->get().$record->picture;?>" class="img-responsive" alt="..."  width="50px" style="height:40px;">

                                                    <?php } ?>
                                                    </td>
                                                    <td>
                                                        <a href="<?php echo $this->url->get("myshop/details/" . $record->sid); ?>">
                                                         <?php echo $record->shop_name;?>
                                                        </a>
                                                    </td>

                                                     <td>
                                                         <?php echo $record->price;?>
                                                    </td>
                                                    <td>
                                                        <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>"><p>Status</p></a>
                                                    </td>
                                                     <td>
                                                        <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>">
                                                            <i class="glyphicon glyphicon-pencil" id="pencil" ></i>
                                                        </a>
                                                        <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>">
                                                            <i class="delete fa fa-trash-o fa-lg" ></i>
                                                        </a>

                                                    </td>
                                                    
                                                    
                                                </tr>
                                            </tbody>
                                             <?php } ?>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">

                <ul class="pager">
                        <li><?php echo "You are in page ", $selling->current, " of ", $selling->total_pages; ?></li>
                        <li><a href="<?php echo $this->url->get("inventory/list" ); ?>">First</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $selling->before); ?>">Previous</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $selling->next); ?>">Next</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $selling->last); ?>">Last</a></li>            
                </ul>

            </div>

        </div> <!---Container item-area !-->
    </div> 

    
    <div id="pane3" class="tab-pane">
        <div class="container item-area">
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading" id="heading">
                        Valuable Products
                    </div>
                <div class="panel-body">
                    <div class="table-responsive">

                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Name</th>
                                                    <th>Image</th>
                                                    
                                                    <th>Shop</th>
                                                    <th>Price</th>
                                                    <th>Status</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                             <?php 
                                             $count=0;
                                             foreach ($Valuable->items as $record) { 
                                                    $count++;
                                                ?>
                                             <tbody>
                                                <tr>
                                                    <td><?php echo $count; ?></td>
                                                    <td>
                                                        <strong>
                                                            <a href="<?php echo $this->url->get("inventory/details/" . $record->id); ?>">
                                                                <?php echo $record->product_name; ?>
                                                            </a>
                                                        </strong>
                                                    </td>
                                                    <td>
                                                        <?php if (!isset($record->picture)) { ?>
  
                                                    <img src="<?php echo $this->url->get().'main/images/';?>shop_banner.jpg" class="img-responsive" alt="..." width="50px" style="height:40px;">

                                                    <?php } else { ?>

                                                    <img src="<?php echo $this->url->get().$record->picture;?>" class="img-responsive" alt="..."  width="50px" style="height:40px;">

                                                    <?php } ?>
                                                    </td>
                                                    <td>
                                                        <a href="<?php echo $this->url->get("myshop/details/" . $record->sid); ?>">
                                                         <?php echo $record->shop_name;?>
                                                        </a>
                                                    </td>

                                                     <td>
                                                         <?php echo $record->price;?>
                                                    </td>
                                                    <td>
                                                        <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>"><p>Status</p></a>
                                                    </td>
                                                     <td>
                                                        <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>">
                                                            <i class="glyphicon glyphicon-pencil" id="pencil" ></i>
                                                        </a>
                                                        <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>">
                                                            <i class="delete fa fa-trash-o fa-lg" ></i>
                                                        </a>

                                                    </td>
                                                    
                                                    
                                                </tr>
                                            </tbody>
                                             <?php } ?>
                            </table>

                        </div>
                    </div>
                </div>
                </div>
            </div>
            <div class="col-md-8">

                <ul class="pager">
                        <li><?php echo "You are in page ", $Valuable->current, " of ", $Valuable->total_pages; ?></li>
                        <li><a href="<?php echo $this->url->get("inventory/list" ); ?>">First</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Valuable->before); ?>">Previous</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Valuable->next); ?>">Next</a></li>
                        <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Valuable->last); ?>">Last</a></li>            
                </ul>

            </div>
        </div> <!---Container item-area !-->
    </div>
</div>

</div>

    

    

    <div class="col-md-4 col-md-offset-4">
        <div class="text-center new-button">
            <a href="<?php echo $this->url->get() . 'inventory/new'; ?>"><i class="fa fa-plus-square-o fa-5x"></i></a>   
                <h3>Add New Product</h3>
            </a>
        </div>
    </div>


</div>



