<style>

h3{
    text-align:center;
}

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 559px;
    width: 95%;
}

strong > a{
    padding-left: 0px;
}

.product{

    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px; 
    border:1px solid #ECECEC ;
    border-radius: 4px;   

}
.product>p{

    font-size: 15px;
    padding-left: 1px;

}

.glyphicon{
    float:right;
    color:#106E96;
}
.delete{
    float: right;
    color:#106E96;
}

.glyphicon:hover{
    color:#5B050B;
}
.delete:hover{
    color:#5B050B;
}

.fa{
    color: #106E96;
}

</style>


<div class="row-cell">

    

    <?php foreach ($Product->items as $record){?>
        <div class="product">

            <strong> <a href="<?php echo $this->url->get("inventory/details/" . $record->id); ?>"> <?php echo $record->product_name; ?>
            </a>
            </strong>
            <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>"><i class="delete fa fa-trash-o fa-lg" ></i></a>
            <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>"><i class="glyphicon glyphicon-pencil" ></i></a>
            
            <p> <?php echo $record->product_description;?></p>

        </div>
    <?php }?>

    

    <div class="col-md-4 col-md-offset-4">
        <div class="text-center new-button">
            <a href="<?php echo $this->url->get() . 'inventory/new'; ?>"><i class="fa fa-plus-square-o fa-5x"></i></a>   
                <h3>Add New Product</h3>
            </a>
        </div>
    </div>

    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Product->current, " of ", $Product->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("inventory/list" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Product->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Product->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("inventory/list?page=" . $Product->last); ?>">Last</a></li>            
        </ul>

    </div>


</div>

