<style>
h3{
text-align:center;
}

.settings-area {
    font-size: 13px;
    position: absolute;
    right: 60px;
    text-align: right;
    top: 10px;
}

.row {
    margin-left: -50px;
    margin-right: -15px;
}

.col-md-3 {
    width: 25%;
}
a {
    color: #0099CC;
	font-size: 18px;
    
}
</style>
<div class="container">
</hr>
<div class="row-cell">
<div class="col-md-8">

<h3 class="b"> My Products </h3>
<?php foreach ($data['value'] as $record){?>
<p><strong> <a href="<?php echo $this->url->get() . 'inventory/details/' . $record->id; ?>"><?php echo $record->product_name;?></a></strong></p>
<p> <?php echo $record->product_description;?></p>
</br>
</br>
<?php }?>
</div>
</div>
</div>
<div class="col-md-4 col-md-offset-4">
        <div class="text-center new-button">
        <a href="<?php echo $this->url->get() . 'inventory/new'; ?>"><i class="fa fa-plus-square-o fa-5x"></i></a>   
            <h3>Add New Product</h3>
        </a>
    </div>
    </div>

