<style>

h3{
    text-align:center;
}

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 642px;
    width: 95%;
}

strong > a{
    padding-left: 0px;
}

.product{

    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px; 
    border:1px solid #ECECEC ;
    border-radius: 4px;   

}
.product>p{

    font-size: 15px;
    padding-left: 1px;

}

#pencil{
    float:left;
    color:#106E96;
    padding-top: 4px;
}
.delete{
    float: left;
    color:#106E96;
    padding-top: 4px;
}

.glyphicon:hover{
    color:#5B050B;
}
.delete:hover{
    color:#5B050B;
}

.fa{
    color: #106E96;
}
.fa-5x:hover{
    color:#5B050B;
}

.seperator-dotted{
    width: 100%;
    border-bottom: 1px solid #ECECEC;
    margin: 0px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}

p{
    font-size: 15px;
}

.table-bordered > thead > tr > th, .table-bordered > tbody > tr > th, .table-bordered > tfoot > tr > th, .table-bordered > thead > tr > td, .table-bordered > tbody > tr > td, .table-bordered > tfoot > tr > td {
    border: 1px solid #ddd;
}

.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    border-top: 1px solid #ddd;
    line-height: 1.42857;
    padding: 8px;
    vertical-align: top;
}
</style>


<div class="row-cell">
    <nav class="navbar navbar-default" role="navigation">
        
            
        
        <div class="col-md-4">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('inventory/list/')?>" class="btn btn-lg btn-custom gray" id="list">
                    <p>&ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp;  All  &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp;</p>
                </a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('inventory/selling/')?>" class="btn btn-lg btn-custom gray" id="selling">
                    <p>&ensp; &ensp; &ensp; &ensp; &ensp; &ensp;Most Selling&ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; </p>
                </a>
            </div>
            
        </div>
        <div class="col-md-4">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('inventory/valuable/')?>" class="btn btn-lg btn-custom gray" id="valuable">
                    <p>&ensp; &ensp; &ensp; &ensp; &ensp;&ensp;Most Valuable &ensp; &ensp; &ensp; &ensp; &ensp;&ensp;</p>
                </a>
            </div>
            
        </div>
    
    </nav>

</br>

    <div class="table-responsive">

        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Image</th>
                                            
                                            <th>Shop</th>
                                            <th>Price</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                     <?php 
                                     $count=0;
                                     foreach ($Valuable->items as $record) { 
                                            $count++;
                                        ?>
                                     <tbody>
                                        <tr>
                                            <td><?php echo $count; ?></td>
                                            <td>
                                                <strong> 
                                                    <a href="<?php echo $this->url->get("inventory/details/" . $record->id); ?>">
                                                        <?php echo $record->product_name; ?>
                                                    </a>
                                                </strong>
                                            </td>
                                            <td>
                                                <img src="<?php echo $this->url->get().$record->picture;?>" height="30px" width="50px" >
                                            </td>
                                            <td>
                                                <a href="<?php echo $this->url->get("inventory/shopdetails/" . $record->shop_name); ?>">
                                                 <?php echo $record->shop_name;?>
                                                </a>
                                            </td>

                                             <td>
                                                 <?php echo $record->price;?>
                                            </td>
                                            <td>
                                                <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>"><p>Status</p></a>
                                            </td>
                                             <td>
                                                <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>">
                                                    <i class="glyphicon glyphicon-pencil" id="pencil" ></i>
                                                </a>
                                                <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>">
                                                    <i class="delete fa fa-trash-o fa-lg" ></i>
                                                </a>

                                            </td>
                                            
                                            
                                        </tr>
                                    </tbody>
                                     <?php } ?>
                </table>

        </div>
    </div>


    

    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Valuable->current, " of ", $Valuable->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("inventory/valuable" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("inventory/valuable?page=" . $Valuable->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("inventory/valuable?page=" . $Valuable->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("inventory/valuable?page=" . $Valuable->last); ?>">Last</a></li>            
        </ul>

    </div>

    <div class="col-md-4 col-md-offset-4">
        <div class="text-center new-button">
            <a href="<?php echo $this->url->get() . 'inventory/new'; ?>"><i class="fa fa-plus-square-o fa-5x"></i></a>   
                <h3>Add New Product</h3>
            </a>
        </div>
    </div>


</div>


<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[3];

    console.log(choice);

    if(choice=='list')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#list").addClass("highlight");
    }

    else if(choice=='selling')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#selling").addClass("highlight");
    }

    else if(choice=='valuable')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#valuable").addClass("highlight");
    }

    </script>

