 <!-- mid menu part -->
  <div class="container">
      <div class="mid-menu">
        <div class="item">New Products</div>
        <div class="item">Hot Products</div>
        <div class="item">Best Selling</div>
      </div>
      <div class="red-joint"></div>
    
  </div>
  <!-- mid menu part ends here -->


  <!-- item area part -->

  <div class="container item-area">
    <div class="col-md-3">
      <div class="item">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>dress1.jpg"></img>
        <div class="price">Price: 200</div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="item">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>dress2.jpg"></img>
        <div class="price">Price: 200</div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="item">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>dress3.jpg"></img>
        <div class="price">Price: 200</div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="item">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>dress4.jpg"></img>
        <div class="price">Price: 200</div>
      </div>
    </div>
   


  </div>

  <!-- item area part ends -->


  <?php echo $this->partial('shared/ad'); ?>


  <!-- bottom item area -->

  <div class="container bottom-item-area">
    <div class="col-md-9">
      <div class="row product">
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product1.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product2.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product3.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product4.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product5.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product6.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product7.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product8.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product9.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product10.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product11.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product12.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product1.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product2.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product3.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="item">
            <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>product4.jpg"></img>
            <div class="product-name">Product Name</div>
            <div class="product-price">$200</div>
          </div>
        </div>
       
        
      </div>
    </div>
    <div class="col-md-3">
      <div class="portal"></div>
      <div class="portal"></div>

    </div>
  </div>

  <!-- bottom item area ends here -->


