<style type="text/css">
.image{
    border: 1px solid #dadada;
    margin-top: 5px;
    padding: 5px;
    margin-bottom: 5px;

}



.cart .form-control{
  display: inline;
  width: 40%;

}

.ash-bg{
  background-color: #F1F1F1;
  margin-top: 15px;
}

.form-box{

    border: 1px solid #dadada;
    height: 570px;
    width: 100%;
    padding: 10px;


}

.bg-button {
    background-color: #909090;
    color: white;
    font-size: 16px;
}



#prod_set{
  background: none repeat scroll 0 0 #f7f8fa;
  border: medium none;
  height: auto;
  margin-bottom: 20px;
  padding-top: 5px;
  text-transform: none;
  font-size: 14px;

}

.cart-intro{
  padding-bottom: 10px;
}

#shop_pic{
  padding-left: 0px;
}

.modal-footer {
    border-top: 0px solid #e5e5e5;
    margin-top: 15px;
    padding: 19px 20px 20px;
    text-align: right;
}

#proceed{
  margin-top: 65px;
  font-size: 18px;
}

#procd_pay{
  margin-top: 27px;
}


#shopping_des{
  margin-left:-12px;
  margin-top: 3px;
}

#bag_price{
  margin-top: 3px;
}


#remove_bag{
  margin-top: -7px;
}

#separator{
  border-top: 1px solid black;
}

.modal-footer {
    border-top: none;
    margin-top: -25px;
    padding: 0px;
    text-align: center;
}

</style>

<script type="text/javascript">
 function processWish(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find = id.toString().concat(id.toString()); 

    $.ajax({

        type: "POST",
        url:base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(find);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       if (result=="1") {
        $('#notLoggedInModal').modal('show');
         setTimeout( "jQuery('#notLoggedInModal').modal('hide');",3000 );
      }
       else if (result=="2") {
        $('#productInWishlistModal').modal('show');
        setTimeout( "jQuery('#productInWishlistModal').modal('hide');",3000 );
      }
       else if (result=="3") {
        $('#productAddedInWishlist').modal('show');
        setTimeout( "jQuery('#productAddedInWishlist').modal('hide');",3000 );
      }
 
    });

    //alert(id);

   
    }

$(function(){
$('.wish').on('click', function(e) {

//subcategories();
 var wishId = e.target.id;

 //clicked(idClicked);
 processWish(wishId);

  });
});
</script>

<script type="text/javascript">

$( document ).ready(function() {
//$('.quant-changed').val("1");
  $('.quant-changed').mask("9?999",{placeholder:""});

});
 
$(function(){
$('.quant-changed').on('change', function(e) {
var base_url =<?php echo $this->url->get(); ?>;

var quantId = e.target.id;
//$(this).mask("9999");
console.log(quantId);
var pId = quantId.toString().split(",")[0];
var priceUnit = quantId.toString().split(",")[1];
console.log(pId);
console.log(priceUnit);
var quantity = $(this).val();


console.log(quantity);

var spin_area_id = pId.toString().concat("spin");
$('#'+spin_area_id).html('<i class="fa fa-spin fa-refresh"></i>');

$.ajax({

        type: "POST",
        url: base_url+"index/checkStock",
        data: { data1 : pId, },
        success: function(result)
        {
            //$("#sub_cat_id").html(html);
            //location.reload();
            if((result=="no") || (result=="No"))
              $('#checkStockModal').modal('show');
            console.log(result);
             $('#'+spin_area_id).html('');
        }
      });
//checkStock(quantity);
//$('#'+spin_area_id).html('');


 if(parseInt(quantity)>=0){
  
  var subTotal = parseInt(quantity) * parseInt(priceUnit);
  console.log(subTotal);

  var sub_text_area_id = pId.toString().concat("sub");

  console.log(sub_text_area_id);

  $('#'+sub_text_area_id).html(subTotal);

}

 if(quantity==" "){
  $('#'+sub_text_area_id).html("0");
  //$('#negQuantModal').modal('show');
}

 

 

  console.log(spin_area_id);
  /*
    $('.cart-delete').click(function(){
      $(this).parent('div').parent('div').slideUp('slow');
  });
  */
  console.log("Quantity");
  console.log(quantity);
  console.log("Produc ID");
  console.log(pId);

  $.ajax({

        type: "POST",
        url: base_url+"index/updateQuantCookie",
        data: { productID : pId, Quant: quantity },
        success: function(html)
        {
            //console.log("Quantity Successfully updated in cookie");
            $("#total").html(html);
            $("#subtotal").html(html);

        }
      });

  /*

  $.ajax({

        type: "POST",
        url: "/biz_mela/index/calculateTotal",
        success: function(html)
        {
          $("#total").html(html);
            
        }
      });

  */




  
  });


});

$(function(){
$('.glyphicon-remove-circle').on('click', function() {
    var base_url =<?php echo $this->url->get(); ?>;

      //$(this).parent('div').parent('div').slideUp('slow');
      var pId = $(this).attr('product_id');
      console.log(pId);

      

      $.ajax({

        type: "POST",
        url: base_url+"index/updateCookie",
        data: { data1 : pId, },
        success: function(html)
        {
            //$("#sub_cat_id").html(html);
            $("#my_count").html(html);
        }
      });

      //$(this).parent('div').parent('div').slideUp('slow');
      var spin_area_id = pId.toString().concat("spin");
      $('#'+spin_area_id).parent('div').parent('div').parent('div').parent('div').slideUp('slow');;
  

  });
});

</script>




<div class="container">
  
    <div class="col-md-12" id="cart-section">
        <div class="cart-header">
            <div class="cart-intro">
                <font size="5">My Shopping Cart</font> <br>
     
            </div>
            

        </div>
    </div>
</div>


<div class="container">
    <div class="col-md-12">
      <div class="col-md-7">
      <?php foreach ($shop['cResult'] as $row){?>
         <div  class="col-md-12" id="prod_set">
        
          
              <div class="col-md-3" id="shop_pic">
                <div class="image">
                  <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>" style="width:100%;height:125px;"></img>
                </div>
              </div>

              <div class="col-md-9" >
                <div class="col-md-9" id="shopping_des" >
                  <a href="<?php echo $this->url->get("index/productdetails/" . $row->id); ?>" >
                      <?php echo $row->product_name; ?>
                  </a>

                   <div><?php echo $row->product_description; ?></div>

                   <div class="pro_qty" style="width:25%" >
                    Qty:
                    <?php $cookie_array = unserialize($_COOKIE['product']);?>
                     <input type="text" class="form-control quant-changed" id="<?php echo $row->id.",".$row->price; ?>" value="<?php echo $cookie_array[$row->id];?>"> &ensp; 
                     <span class="spin" id="<?php echo $row->id."spin"; ?>"></span>
                  </div>
                </div>


                <div class="col-md-3" id="bag_price"style="text_align:right;">
                  <div >BDT. <?php echo $row->price; ?></div>
                  <div  id="<?php echo $row->id."sub"; ?>" >
                    <?php $cookie_array = unserialize($_COOKIE['product']);?>
                    BDT. <?php echo intval($row->price)*intval($cookie_array[$row->id]); ?>
                  </div>
                  </br>
              
                  <div id="remove_bag">
                    <a href="" data-toggle="modal" data-target="#cartDeleteModal<?php echo $row->id; ?>"  style="color:#000000;">
                     <span class="glyphicon glyphicon-remove" product_id="<?php echo $row->id; ?>" ></span>
                    </a>
                    <a href="" data-toggle="modal" data-target="#cartDeleteModal<?php echo $row->id; ?>" style="color:#000000;">Remove
                    </a>
                  </div>
                </div>

                <div class="col-md-12" id="separator">
                  <div class="col-md-6 wish" id="<?php echo $row->id; ?>" style="cursor:pointer; margin-left:-20px;">
                   
                      <i class="fa fa-star" style="color: #D21E21"></i>
                    
                        Add to Wish list
                  </div>

                </div>

               
                
                
              </div>


              
      </div>

      <div class="modal fade" id="cartDeleteModal<?php echo $row->id; ?>" tabindex="-1" role="dialog" aria-labelledby="cartDeleteModal<?php echo $row->id; ?>" aria-hidden="true">
          <div class="modal-dialog">
              <div class="modal-content modal-margin-top">
                 <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                      <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                      <span class="sr-only">Close</span>
                    </button>
        
                  </div>
                  <div class="modal-body">
                      <p>
                      <center> Do you really want to delete this product from your cart ? </center> 
                      </p>
                  </div> 
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><span>Cancel</span></button>
                    <button type="button" class="btn btn-primary glyphicon-remove-circle " product_id="<?php echo $row->id; ?>" data-dismiss="modal">Delete</button>
                  </div> 
              </div>
          </div>
      </div>
       <?php }?>
</div>
       <div class="col-md-5" >
          <div class="form-box">
            Estimate Shipping and Tax <br>
            <font color="#D1D1D1">
              Enter your destination to get a shipping estimate.

                <p></p>

                Country<br>
                <select class="form-control">
                  <option>Bangladesh</option>
                </select>
          
                <br>District/State<br>
                <select class="form-control">
                  <option>Please select district,state or region</option>
                </select>

                <br>Zip/Postal code<br>
                <input type="text" class="form-control">

                <p><br></p>

            </font>

            <div class="col-md-6">

            <button type="button" class="btn btn-default bg-button"> Get a Quote
            </button>
            
            <p><br></p>
            Shipping Method<br>
            <input type="radio" name="home_delivery" value="home_delivery"><font color="#D1D1D1">Home Delivery: Tk 60</font><br>

            Pickup from office<br>
            <input type="radio" name="pick_from_office" value="pick_from_office"><font color="#D1D1D1">Free Tk 0 </font><br>

            <p></p>

            <button type="button" class="btn btn-default bg-button">Update Total
            </button> 

          </div>

          <div class="col-md-6" id="proceed">
            Subtotal: &ensp;&ensp; 
              <span id="subtotal"><?php echo $data['mult']; ?></span>
              <br>
              
              Total: &ensp;&ensp;&ensp;&ensp;&nbsp;  
              <span id="total"><?php echo $data['mult']; ?></span>
              <br>
              <p></p>
              <button type="button" class="btn btn-default bg-button" id="procd_pay">Proceed to payment &ensp;<span class="glyphicon glyphicon-chevron-right"></span>
              </button> 
            

          </div>
    
          </div>

          
  


      </div>
    </div>
 
</div>

<div class="modal fade" id="checkStockModal" tabindex="-1" role="dialog" aria-labelledby="checkStockModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> This product is out of stock. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="negQuantModal" tabindex="-1" role="dialog" aria-labelledby="negQuantModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Quantity must be positive. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>


<div class="modal fade" id="notLoggedInModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> You need to log in first. </center> 
                </p>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
            </div>
            
        </div>
  </div>
</div>

<div class="modal fade" id="productInWishlistModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            
            <div class="modal-body">
                <p>
                <center> This product already exists in your wish list. </center> 
                </p>
            </div>
            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'wishlist/wish/';?>">

                Checkout
              </a>
            </div>
            
        </div>
  </div>
</div>

<div class="modal fade" id="productAddedInWishlist" tabindex="-1" role="dialog" aria-labelledby="productAddedInWishlist" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            
            <div class="modal-body">
                <p>
                <center> Wish list updated successfully. </center> 
                </p>
            </div>

            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'wishlist/wish/';?>">

                Checkout
              </a>
            </div>
            
        </div>
  </div>
</div>




<?php echo $this->partial('shared/ad'); ?>