<style type="text/css">
.image{
    border: 1px solid #dadada;
    margin-top: 5px;
    padding: 5px;
    margin-bottom: 5px;

}

.top-padding{
  padding-top: 40px;
}

.cart .form-control{
  display: inline;
  width: 40%;

}

.ash-bg{
  background-color: #F1F1F1;
  margin-top: 15px;
}

.form-box{

    border: 1px solid #dadada;
    height: 600px;
    margin-top: 15px;
    width: 100%;
    padding: 10px;


}

.bg-button {
    background-color: #909090;
    color: white;
    font-size: 16px;
}

.modal-margin-top{
  margin-top: 40%;
}
</style>

<script type="text/javascript">
 
$(function(){
$('.quant-changed').on('change', function(e) {

var quantId = e.target.id;
console.log(quantId);
var pId = quantId.toString().split(",")[0];
var priceUnit = quantId.toString().split(",")[1];
console.log(pId);
console.log(priceUnit);
var quantity = $(this).val();


console.log(quantity);
 var spin_area_id = pId.toString().concat("spin");
$('#'+spin_area_id).html('<i class="fa fa-spin fa-refresh"></i>');
$.ajax({

        type: "POST",
        url: "/biz_mela/index/checkStock",
        data: { data1 : pId, },
        success: function(result)
        {
            //$("#sub_cat_id").html(html);
            //location.reload();
            if((result=="no") || (result=="No"))
              $('#checkStockModal').modal('show');
            console.log(result);
             $('#'+spin_area_id).html('');
        }
      });
//checkStock(quantity);
 if(parseInt(quantity)>0){
  
  var subTotal = parseInt(quantity) * parseInt(priceUnit);
  console.log(subTotal);

  var sub_text_area_id = pId.toString().concat("sub");

  console.log(sub_text_area_id);

  $('#'+sub_text_area_id).html(subTotal);

}

else{
  //$('#'+sub_text_area_id).html("invalid quantity");
  $('#negQuantModal').modal('show');
}

 

  console.log(spin_area_id);
  /*
    $('.cart-delete').click(function(){
      $(this).parent('div').parent('div').slideUp('slow');
  });
  */
  
  });


});

$(function(){
$('.cart-delete').on('click', function() {

      //$(this).parent('div').parent('div').slideUp('slow');
      var pId = $(this).attr('product_id');
      console.log(pId);

      $.ajax({

        type: "POST",
        url: "/biz_mela/index/updateCookie",
        data: { data1 : pId, },
        success: function(html)
        {
            //$("#sub_cat_id").html(html);
            $("#my_count").html(html);
        }
      });

      $(this).parent('div').parent('div').slideUp('slow');
  

  });
});

</script>

<div class="container">
  <div class="row" style="padding-top:10px; padding-bottom:10px;">
    <div class="col-md-4">
     <font size="5">Your Shopping Cart</font>&ensp; (3 items/ 100 items)
    </div>

    <div class="col-md-3 col-md-offset-5">
      &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
     <button type="button" class="btn btn-default bg-button">Proceed to payment &ensp;<span class="glyphicon glyphicon-chevron-right"></span>
     </button> 
    </div>
  </div>
</div>


<div class="seperator marg-top"></div>


<div class="container">
  <div class="row" style="padding-top:10px;">
    <div class="col-md-4">
      Seller: Beauty house, beuty you
    </div>
  </div>
</div>



<div class="container-fluid">
  <div class="row ash-bg">
    <div class="col-md-2 col-md-offset-3">
      Product Name
    </div>

    <div class="col-md-2 col-md-offset-1">
      Quantity
    </div>

    <div class="col-md-2">
      Price
    </div>

    <div class="col-md-2">
      Subtotal
    </div>
  </div>
</div>


<div class="container-fluid">
  <?php foreach ($cResult as $row){?>

  <div class="row">
    <div class="col-md-2 col-md-offset-1">
      <div class="image">
        <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>"></img>
      </div>
    </div>

    <div class="col-md-2 top-padding">
      <?php echo $row->product_name; ?>
    </div>

    <div class="col-md-2 col-md-offset-1 top-padding cart">
       <input type="text" class="form-control quant-changed" id="<?php echo $row->id.",".$row->price; ?>" value="1"> &ensp; 
       <span class="spin" id="<?php echo $row->id."spin"; ?>"></span>

    </div>

    <div class="col-md-1  top-padding">
      <?php echo $row->price; ?>
    </div>

    <div class="col-md-1 col-md-offset-1 top-padding" id="<?php echo $row->id."sub"; ?>">
      <?php echo $row->price; ?>
    </div>

    <div class="col-md-1 top-padding ">
      <span class="glyphicon glyphicon-shopping-cart cart-delete" style="cursor:pointer" product_id="<?php echo $row->id; ?>"> </span>
    </div>

  </div>

  <div class="seperator"></div>

  <?php }?>

</div>

<div class="container-fluid">
  <div class="row">
  <div class="col-md-4 col-md-offset-5">
    <div class="form-box">
      Estimate Shipping and Tax <br>
      <font color="#D1D1D1">
      Enter your destination to get a shipping estimate.

      <p></p>

      Country<br>
      <select class="form-control">
        <option>Bangladesh</option>
      </select>
      
      <br>District/State<br>
      <select class="form-control">
        <option>Please select district,state or region</option>
      </select>

      <br>Zip/Postal code<br>
      <input type="text" class="form-control">

      <p><br></p>

    </font>

      <button type="button" class="btn btn-default bg-button"> Get a Quote
      </button>
      
      <p><br></p>
      Shipping Method<br>
      <input type="radio" name="home_delivery" value="home_delivery"><font color="#D1D1D1">Home Delivery: Tk 60</font><br>

      Pickup from office<br>
      <input type="radio" name="pick_from_office" value="pick_from_office"><font color="#D1D1D1">Free Tk 0 </font><br>

      <p></p>

      <button type="button" class="btn btn-default bg-button">Update Total
      </button> 




    </div>
  </div>

  <div class="col-md-2 col-md-offset-1 top-padding">
    Subtotal &ensp;&ensp; 9855 <br>
    All total &ensp;&ensp; 9855<br>
    <p></p>
    <button type="button" class="btn btn-default bg-button">Proceed to payment &ensp;<span class="glyphicon glyphicon-chevron-right"></span>
    </button> 

    
  </div>
  </div>
</div>

<div class="modal fade" id="checkStockModal" tabindex="-1" role="dialog" aria-labelledby="checkStockModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> This product is out of stock. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="negQuantModal" tabindex="-1" role="dialog" aria-labelledby="negQuantModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Quantity must be positive. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>




<?php echo $this->partial('shared/ad'); ?>