<style>

a>.glyphicon{
    float:left;
    color:#106E96;
    font-size: 18px;
    margin-top: 10px;
}
.delete{
    float: left;
    color:#106E96;
    font-size: 22px;
    margin-top: 10px;
}

.glyphicon:hover{
    color:#5B050B;
}
.delete:hover{
    color:#5B050B;
}

.fa{
    color: #106E96;
}

.product{
    height:50px;
    border:1px solid #ECECEC ;
    border-radius: 4px;
    
    width: 95%;
}

strong>a{
    font-size: 18px;
}


.table-bordered > thead > tr > th, .table-bordered > tbody > tr > th, .table-bordered > tfoot > tr > th, .table-bordered > thead > tr > td, .table-bordered > tbody > tr > td, .table-bordered > tfoot > tr > td {
    border: 1px solid #ddd;
}

.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    border-top: 1px solid #ddd;
    line-height: 1.42857;
    padding: 8px;
    vertical-align: top;

}

.table {
    margin-bottom: 20px;
    max-width: 100%;
    width: 100%;
}

table {
    border-collapse: collapse;
    border-spacing: 0;
}

.table-bordered {
    border: 1px solid #ddd;
}

.glyphicon{
    float:left;
    color:#106E96;
    padding-top: 0px;
    
}
.delete{
    float: left;
    color:#106E96;
    padding-top: 0px;
    
}


</style>

    <div class="table-responsive">

        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Shop Name</th>
                                            <th>Image</th>
                                            <th>Total Products</th>
                                            
                                            
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                     <?php 
                                     $count=0;
                                     foreach ($Shop->items as $record) { 
                                            $count++;
                                        ?>
                                     <tbody>
                                        <tr>
                                            <td><?php echo $count; ?></td>
                                            <td>
                                                <strong> 
                                                     <a href="<?php echo $this->url->get("shop/details/" . $record->id); ?>"> 
                                                        <?php echo $record->shop_name; ?>
                                                    </a>
                                                   
                                                </strong>
                                            </td>
                                            <td>
                                                <img src="<?php echo $this->url->get().$record->shop_image;?>" height="40px" width="60px" >
                                            </td>
                                            <td>
                                                 
                                            </td>

                                             <td>
                                               <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>"><p>Status</p></a>
                                            </td>
                                            
                                             <td>
                                                <a href="<?php echo $this->url->get("inventory/edit/" . $record->id); ?>">
                                                    <i class="glyphicon glyphicon-pencil" ></i>
                                                </a>
                                                <a href="<?php echo $this->url->get("inventory/delete/" . $record->id); ?>">
                                                    <i class="delete fa fa-trash-o fa-lg" ></i>
                                                </a>

                                            </td>
                                            
                                            
                                        </tr>
                                    </tbody>
                                     <?php } ?>
                </table>

        </div>
    </div>



    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Shop->current, " of ", $Shop->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("Shop/shop" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("Shop/shop?page=" . $Shop->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("Shop/shop?page=" . $Shop->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("Shop/shop?page=" . $Shop->last); ?>">Last</a></li>            
        </ul>

    </div>

    <div class="col-md-4 col-md-offset-4">
        <div class="text-center new-button">
            <a href="<?php echo $this->url->get() . 'shop/new'; ?>"><i class="fa fa-plus-square-o fa-5x"></i></a>   
                <h3>Add New Shop</h3>
            </a>
        </div>
    </div>


</div>