<style>
h2{
	text-align:center;
}

.errorMessage{
    color:#a94442;
    font-size: 15px;
    padding: 15px;
    width:100%;
    border:1px solid #ECECEC ;
    border-radius: 4px;
    background-color: #f2dede;

}


</style>

<div class="row-cell">
			<div class="col-md-6 col-md-offset-3 login-area">
				
				<div class="row form-area">
					
					<?php echo $this->getContent(); ?>
					<h2>Refer Your Friend Via Email</h2>

				<form action="" method="post">
					<!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
					<?php echo $form->render("email"); ?>
					<?php $message = $form->getMessagesFor('email');
					foreach ($message as $m) {?>
						<div class="alert alert-danger form-element"><?php echo $m; ?></div>
					<?php }?>
					
					</br>
				    <div class="btn-group btn-group-justified button-element">
					  <div class="btn-group">
					    <button type="submit" class="btn btn-lg btn-custom green">Send Email</button>
					  </div>
					</div>
					
					<div class="btn-group btn-group-justified form-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="cancel" class="btn btn-lg btn-custom btn-danger">Cancel</button>
                    </div>		  
                </div>
				</form>
				</div>
			</div>
		</div>