
<div class="row-cell">
    <div class="item-area">
	
        <div class="form-area">

            <?php echo $this->getContent(); ?>

            <form action="" method="post">
			
				<div class="col-md-6 col-md-offset-3">
					<div class="row cell">
						<?php echo $form->render("password"); ?>
						</br>
						<div class="btn-group btn-group-justified button-element">
		                    <div class="btn-group">
		                        <button type="submit" name="submit" class="btn btn-lg btn-custom green">Enter Password</button>
		                    </div>			  
		                </div>
					</div>
				</div>
			</form>
    	</div>
	</div>
</div>