<style>
.intro{
	color:#870415;
	padding-top: 3px;
	font-size: 15px;
}

a{
	color:#870415;
	text-decoration: none;
	font-size: 15px;
}

a:hover{
	color:#CD2027;
	text-decoration: none;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height: 49px;
}

.left-menu{
	display:table-row;
}

.row {
    margin-left: 3px;
    margin-right: -15px;
}
.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}


</style>

<div class="row-cell">
    <div class="item-area">
	
        <div class="form-area">

            <?php echo $this->getContent(); ?>

            <form action="" method="post">
			
				<div class="col-md-6 col-md-offset-3">
					<div class="row cell">
						<?php echo $form->render("password"); ?>
						</br>
						<div class="btn-group btn-group-justified button-element">
		                    <div class="btn-group">
		                        <button type="submit" name="submit" class="btn btn-lg btn-custom green">Enter Password</button>
		                    </div>			  
		                </div>
					</div>
				</div>
			</form>
    	</div>
	</div>
</div>