<style>

b.padding{
	padding-top: 25px;
    padding-right: 50px;
    padding-bottom: 25px;
    padding-left: 50px;
}

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 559px;
    width: 67.5%;
}


.pay{

    border:1px solid #ECECEC ;
    height: 105px;
    width: 104%;
    margin-bottom: 10px;
    margin-left: -15px;
    
}

p{
    font-size: 18px;
}

.data{
    font-size: 15px;
}

.data>b{
    padding-left: 5px;
}

.red{
    color: #9E0423;

}

</style>
<div class="container">
</hr>
    <div class="row-cell">
        <nav class="navbar navbar-default" role="navigation">
            <div class="col-md-3">
                <div class="btn-group">
                    <a href="<?php echo $this->url->get('wallet/account/')?>" class="btn btn-lg btn-custom gray" id="account">
                        <p>My Account &ensp; &ensp; </p></a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="btn-group">
                    <a href="<?php echo $this->url->get('wallet/payment/')?>" class="btn btn-lg btn-custom gray" id="payment">
                        <p>Payment History</p></a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="btn-group">
                    <a href="<?php echo $this->url->get('wallet/status/')?>" class="btn btn-lg btn-custom gray" id="status">
                        <p>Payment Status &ensp;  </p></a>
                </div>
                
            </div>
            <div class="col-md-3">
                <div class="btn-group">
                    <a href="<?php echo $this->url->get('wallet/withdraw/')?>" class="btn btn-lg btn-custom gray" id="withdraw">
                        <p>Payment Withdraw &ensp;  </p></a>
                </div>
                
            </div>
    
        </nav>
        <div class="col-md-12">

            
            
            <?php foreach ($Wallet->items as $row){?>
                <div class="pay">
                    <p class="data" ><b>Order Number</b>   : <?php echo $row->order_no;?></p>
                    <p class="data"><b>Payment Method</b>   : <?php echo $row->method_name;?></p>
                    <p class="data"><b>Transaction Amount</b>   : <?php echo $row->total;?></p>


                </div>
           
            <?php }?>

           
        </div>

        <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Wallet->current, " of ", $Wallet->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("Wallet/payment" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("Wallet/payment?page=" . $Wallet->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("Wallet/payment?page=" . $Wallet->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("Wallet/payment?page=" . $Wallet->last); ?>">Last</a></li>            
        </ul>

    </div>
    </div>
</div>


<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[3];

    console.log(choice);

    if(choice=='account')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#account").addClass("red");
    }

    else if (choice=='payment')
    {
        //$("#purchase").html("<font color="red"> Purchase List </font>");
        $("#payment").addClass("red");
    }

    else if (choice=='status')
    {
        //$("#pending").html("<font color="red"> Pending List </font>");
        $("#status").addClass("red");
    }

    else if (choice=='withdraw')
    {
        //$("#reject").html("<font color="red"> Reject List </font>");
        $("#withdraw").addClass("red");
    }

</script>