<style>
.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 495px;
    width: 95%;


}

.gray{

    background-color: #A0A0A0;
    color:#336699;
    

}

a{

    text-decoration: none;
    color:#870415;

}

.intro{
    color:#870415;
}

.gray{

    background-color:#F7FAFC;
    color:#042C51;

    

}
.navbar {
    background-color: #F7FAFC;
}

.gray:hover{
    background-color:#F7FAFC;
    color:#84660A;
}
p{
    font-size: 18px;
}

</style>


<div class="row-cell">
    <nav class="navbar navbar-default" role="navigation">
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('wallet/account/')?>" class="btn btn-lg btn-custom gray"><p>My Account &ensp; &ensp; </p></a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('wallet/payment/')?>" class="btn btn-lg btn-custom gray"><p>Payment History</p></a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('wallet/status/')?>" class="btn btn-lg btn-custom gray"><p>Payment Status &ensp;  </p></a>
            </div>
            
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('wallet/withdraw/')?>" class="btn btn-lg btn-custom gray"><p>Payment Withdraw &ensp;  </p></a>
            </div>
            
        </div>
    
    </nav>
</div>



