<style>
a{
color:#162D8A;
}


b.padding{
	padding-top: 25px;
    padding-right: 50px;
    padding-bottom: 25px;
    padding-left: 50px;
}
.seperator-dotted{
	width: 40%;

}

.settings-area {
    font-size: 13px;
    position: absolute;
    right: 60px;
    text-align: right;
    top: 10px;
}

</style>
<div class="container">
</hr>
<div class="row-cell">
<div class="col-md-8 ">
<h3 class="b"> Account Information </h3>
<div class="seperator-dotted"></div>
<p><b>Bank Name</b>     : <?php echo $data['value']->bank_name;?></p>
<p><b>Branch Name</b>   : <?php echo $data['value']->branch_name;?></p>
<p><b>Swift Code</b>    : <?php echo $data['value']->swift_code;?></p>
<p><b>Account Holder</b>: <?php echo $data['value']->account_holder_name;?></p>
<p><b>Account Number</b>: <?php echo $data['value']->account_no;?></p>
<a href='/bizmela/wallet/update/'.$userid>Update Bank Account</a>
</br>
</br>
</div>
</div>
</div>