<style>
.successMessage{
    color:#339966;
    font-size: 18px;
    padding: 15px;
    border:1px solid #ECECEC ;
    border-radius: 4px;

}

.form-area.>.errorMessage{
    color:#a94442;
    font-size: 15px;
    padding: 15px;
    width:50%;
    border:1px solid #ECECEC ;
    border-radius: 4px;

}

.intro{
    color:#870415;
}
a{
    color:#870415;
    text-decoration: none;
}
</style>
<div class="row">
    <div class="item-area">
	   
        <div class="form-area">

            <?php echo $this->getContent(); ?>

            <form action="" method="post">
                    <!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
				<div class="col-md-10 col-md-offset-1">
				<div class="row cell">
    				<?php echo $form->render("current_pass"); ?>
                    <?php $message = $form->getMessagesFor('current_pass');
                        foreach ($message as $m) {?>
                            <div class="alert alert-danger form-element"><?php echo $m; ?></div>
                        <?php }?>
    				<?php echo $form->render("new_pass"); ?>
                    <?php $message = $form->getMessagesFor('new_pass');
                        foreach ($message as $m) {?>
                            <div class="alert alert-danger form-element"><?php echo $m; ?></div>
                        <?php }?>
    				<?php echo $form->render("confirm_pass"); ?>
                    <?php $message = $form->getMessagesFor('confirm_pass');
                        foreach ($message as $m) {?>
                            <div class="alert alert-danger form-element"><?php echo $m; ?></div>
                        <?php }?>
    				
				    </br>

                <div class="btn-group btn-group-justified button-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="publish" class="btn btn-lg btn-custom green">Change Password</button>
                    </div>			  
                </div>
				
                
			</div>
				</div>
            </form>
        </div>

    </div>
    <script type="text/javascript">
        
    </script>
</div>
