<style>

h4 {
    color:#000000;

}
h4.padding{
	padding-top: 25px;
    padding-right: 50px;
    padding-bottom: 25px;
    padding-left: 50px;

}
.seperator-dotted{
	width: 100%;
	border-bottom: 1px solid #ECECEC;
	margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}
.green{
	background-color: #00872A;
	color: white;
}


.settings-area {
    font-size: 13px;
    position: absolute;
    right: 60px;
    text-align: right;
    top: 10px;
}

h2{

    font-size:25 px;
    text-align: center;
}

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 505px;
    width: 95%;


}

.dash {

    padding-left: 20px;
    font-size:20px;

}

h5{

    color: #D44243;

}

.subscription{

    font-size: 15px;

}

p{

    font-size: 15px;

}
a{
    text-decoration: none;
}

</style>

<div class="row-cell">

    <div >
        <p class="dash">ACCOUNT  INFORMATION</p>
    </div>

    <div class="seperator-dotted"></div>

     <div class="col-md-6">
        <h4>Contact Information &ensp; &ensp; &ensp; &ensp;  &ensp;  &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; 
            <a href="<?php echo $this->url->get("accdashboard/edit"); ?>">
                Edit
             </a>
         </h4>   
        
        <div class="seperator-dotted">

        </div>


     </div>

     <div class="col-md-6">
        <h4>Newsletter Subscription</h4>
        <div class="seperator-dotted">

        </div>
     </div> 

 

     <div class="col-md-6">
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $data['value']->email;?></p>
            <a href="<?php echo $this->url->get("settings/changepassword"); ?>">
                <h5>Change Password</h5>
            </a>
            </br>
     </div>

     <div class="col-md-6">
        <p class="subscription">You Are Currently Subscribed to General Subscription..</p>
        </br>
        </br>
     </div>


     <div class="col-md-12">
        <p class="address"> <b>Address Book </b></p>
        <div class="seperator-dotted">

        </div>
     </div>

     <div class="col-md-6">
        <p><strong>Default Billing Address</strong></p>
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $address['value']->billing_address;?></p>
        <p><?php echo $address['value']->country;?></p>
        <p><?php echo $address['value']->zip_code;?></p>
        <p>T:<?php echo $data['value']->contact_no;?></p>

        <a href="<?php echo $this->url->get("accdashboard/editaddress"); ?>">
                <h5>Edit Address</h5>
        </a>

     </div>

     <div class="col-md-6">
        <p ><strong>Default Shipping Address</strong></p>
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $shipment['value']->shipping_address;?></p>
        <p><?php echo $shipment['value']->country;?></p>
        <p><?php echo $shipment['value']->zip_code;?></p>
        <p>T:<?php echo $shipment['value']->contact_no;?></p>
        <a href="<?php echo $this->url->get("accdashboard/editshipment"); ?>">
                <h5>Edit Address</h5>
        </a>
     </div>
</div>