<style>
.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}
a{
    color:#870415;
    text-decoration: none;
    font-size: 15px;
}

.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
}
a:hover{
    color:#CD2027;
    text-decoration: none;
}


</style>
<div class="row">
    <div class="item-area">
	
        <div class="form-area">

            <?php echo $this->getContent(); ?>

            <form action="" method="post">
                    <!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
				<div class="col-md-10 col-md-offset-1">
				<div class="row cell">
    				<?php echo $form->render("address"); ?>
    				<?php echo $form->render("country"); ?>
    				<?php echo $form->render("zipcode"); ?>
    				<?php echo $form->render("contactno"); ?>
				    </br>

                <div class="btn-group btn-group-justified button-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="publish" class="btn btn-lg btn-custom green">Update Address</button>
                    </div>			  
                </div>
				<div class="btn-group btn-group-justified form-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="cancel" class="btn btn-lg btn-custom btn-danger">Cancel</button>
                    </div>		  
                </div>
                
			</div>
				</div>
            </form>
        </div>

    </div>
    <script type="text/javascript">
        
    </script>
</div>
