<style>

h4 {
    color:#000000;
}

h4.padding{
	padding-top: 25px;
    padding-right: 50px;
    padding-bottom: 25px;
    padding-left: 30px;

}
.seperator-dotted{
	width: 100%;
	border-bottom: 1px solid #ECECEC;
	margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}

.seperator-dotted2{
    width: 93%;
    border-bottom: 1px solid #ECECEC;
    margin: 0px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}


.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 464px;
    width: 95%;
}

.dash {

    padding-left: 15px;
    font-size:20px;
    text-align: left;
    padding-top: 10px;
    height:42px;
}

h5{

    color: #870415;
}


p{

    font-size: 15px;
}

a{
    color:#870415;
    font-size: 15px;
    text-decoration: none;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}

h4>a{
    color:#870415;
}

.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}
.title{
    padding:8px;

}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    cursor:pointer;
    height: 49px;
}

.panel-default > .panel-heading:hover{
    background-color: #0264C0;
    color: white;

}

.edt:hover{
    color:#72081D;
}


.start{
    padding-left: 10px;
    padding-top: 10px;
    color:#000000;
    font-size: 15px;
    height:82px;
}
.row{
    padding-left: 20px;
}

.main-menu-title>h2{
    font-size: 20px;
    text-align: left;
    padding-top: 10px;

}

</style>

<div class="row">
    <div class="seperator-dotted2"></div>
    <p class="start">Hello,<?php echo $data['value']->username;?>!</br>From your Account Dashboard you have the ability to view a snapshort of your recent activity and update your information.</br>Select a link below to view or edit information.</p>
</div>

<div class="row-cell">

    <div >
        <p class="dash">ACCOUNT  INFORMATION</p>
    </div>

    <div class="seperator-dotted"></div>

     <div class="col-md-6">
        <h4>Contact Information &ensp; &ensp; &ensp; &ensp;  &ensp;  &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp;
            <a href="<?php echo $this->url->get("accdashboard/edit"); ?>" >
                Edit
             </a>
         </h4>   
        
        <div class="seperator-dotted">

        </div>


     </div>

     <div class="col-md-6">
        <h4>Newsletter Subscription</h4>
        <div class="seperator-dotted">

        </div>
     </div> 

 

     <div class="col-md-6">
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $data['value']->email;?></p>
            <a href="<?php echo $this->url->get("accdashboard/changepassword"); ?>">
                <h5>Change Password</h5>
            </a>
            </br>
     </div>

     <div class="col-md-6">
        <p><?php  echo $subs['value']; ?></p>
        </br>
        </br>
     </div>


     <div class="col-md-12">
        <p class="address"> <b>Address Book </b></p>
        <div class="seperator-dotted">

        </div>
     </div>

        </br>
        </br>

     <div class="col-md-6">
        <p><strong>Default Billing Address</strong></p>
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $address['value']->billing_address;?></p>
        <p><?php echo $address['value']->country;?></p>
        <p><?php echo $address['value']->zip_code;?></p>
        <p>T:<?php echo $data['value']->contact_no;?></p>

        <a href="<?php echo $this->url->get("accdashboard/editaddress"); ?>">
                <h5>Edit Address</h5>
        </a>

     </div>

     <div class="col-md-6">
        <p ><strong>Default Shipping Address</strong></p>
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $shipment['value']->shipping_address;?></p>
        <p><?php echo $shipment['value']->country;?></p>
        <p><?php echo $shipment['value']->zip_code;?></p>
        <p>T:<?php echo $shipment['value']->contact_no;?></p>
        <a href="<?php echo $this->url->get("accdashboard/editshipment"); ?>">
                <h5>Edit Address</h5>
        </a>
     </div>
</div>