<style>
h4{
color:#DF013A

}
h4.padding{
	padding-top: 25px;
    padding-right: 50px;
    padding-bottom: 25px;
    padding-left: 50px;

}
.seperator-dotted{
	width: 100%;
	border-bottom: 1px dotted #000;
	margin: 5px 0px 5px 0px;
}
.green{
	background-color: #00872A;
	color: white;
}
a{
color:#2E05AA;

}

.settings-area {
    font-size: 13px;
    position: absolute;
    right: 60px;
    text-align: right;
    top: 10px;
}

</style>

<div class="row-cell">

    <div class="col-md-4">
        </br>
        <h4>Contact Information</h4>
        <div class="seperator-dotted"></div>
            <p>User Name : <?php echo $data['value']->username;?></p>
            <p>Email: <?php echo $data['value']->email;?></p>
            <p>Cell Phone : <?php echo $data['value']->contact_no;?></p>
            <p>Date of Birth : <?php echo $data['value']->dob;?></p>

            <div class="z"><a href='/bizmela/accdashboard/edit'><h5>Edit Profile</h5></a></div>
            <div><a href="<?php echo $this->url->get("settings/changepassword"); ?>"><h5>Change Password</h5></a></div>

            </br>
            </br>
    </div>

    <div class="col-md-3 col-md-offset-3">
        </br>
        <h4>Newsletter</h4>

        <div class="seperator-dotted"></div>
        
        </br>
    </div>

    <div class="col-md-10">
        <h3>Address Book</h3>
        <div class="seperator-dotted"></div>
        </hr>
    </div>



    <div class="col-md-4 ">
        <h4>Default Billing Address</h4>
        <div class="seperator-dotted"></div>
        <?php echo $record['value']->account_holder_name;?>
        </br>
        <p>Account No. :<?php echo $record['value']->account_no;?></p>
        <?php echo $record['value']->branch_name;?>,<?php echo $record['value']->bank_name;?>.
    </div>

</div>