<style>

h4 {
    color:#000000;

}
h4.padding{
	padding-top: 25px;
    padding-right: 50px;
    padding-bottom: 25px;
    padding-left: 50px;

}
.seperator-dotted{
	width: 100%;
	border-bottom: 1px solid #ECECEC;
	margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}



h2{

    font-size:25 px;
    text-align: center;
    padding-left: -10px;
}

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 605px;
    width: 95%;


}

.dash {

    padding-left: 20px;
    font-size:20px;
    text-align: left;
    padding-top: 5px;
}

h5{

    color: #870415;

}

.subscription{

    font-size: 15px;

}

p{

    font-size: 15px;

}
a{
    text-decoration: none;
    color:#870415;
    font-size: 15px;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}

h4>a{
    color:#870415;
}

.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}
.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
}
.edt:hover{
    color:#72081D;
}

</style>

<div class="row-cell">

    <div >
        <p class="dash">ACCOUNT  INFORMATION</p>
    </div>

    <div class="seperator-dotted"></div>

     <div class="col-md-6">
        <h4>Contact Information &ensp; &ensp; &ensp; &ensp;  &ensp;  &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; 
            <a href="<?php echo $this->url->get("accdashboard/edit"); ?>" >
                Edit
             </a>
         </h4>   
        
        <div class="seperator-dotted">

        </div>


     </div>

     <div class="col-md-6">
        <h4>Newsletter Subscription</h4>
        <div class="seperator-dotted">

        </div>
     </div> 

 

     <div class="col-md-6">
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $data['value']->email;?></p>
            <a href="<?php echo $this->url->get("accdashboard/changepassword"); ?>">
                <h5>Change Password</h5>
            </a>
            </br>
     </div>

     <div class="col-md-6">
        <p><?php  echo $subs['value']; ?></p>
        </br>
        </br>
     </div>


     <div class="col-md-12">
        <p class="address"> <b>Address Book </b></p>
        <div class="seperator-dotted">

        </div>
     </div>

     <div class="col-md-6">
        <p><strong>Default Billing Address</strong></p>
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $address['value']->billing_address;?></p>
        <p><?php echo $address['value']->country;?></p>
        <p><?php echo $address['value']->zip_code;?></p>
        <p>T:<?php echo $data['value']->contact_no;?></p>

        <a href="<?php echo $this->url->get("accdashboard/editaddress"); ?>">
                <h5>Edit Address</h5>
        </a>

     </div>

     <div class="col-md-6">
        <p ><strong>Default Shipping Address</strong></p>
        <p><?php echo $data['value']->username;?></p>
        <p><?php echo $shipment['value']->shipping_address;?></p>
        <p><?php echo $shipment['value']->country;?></p>
        <p><?php echo $shipment['value']->zip_code;?></p>
        <p>T:<?php echo $shipment['value']->contact_no;?></p>
        <a href="<?php echo $this->url->get("accdashboard/editshipment"); ?>">
                <h5>Edit Address</h5>
        </a>
     </div>
</div>