<style>

a{
    color:#870415;
    text-decoration: none;
}

a:hover{
    text-decoration: none;
}


b.padding{
	padding-top: 25px;
    padding-right: 50px;
    padding-bottom: 25px;
    padding-left: 50px;
}
.seperator-dotted{
    width: 100%;
    border-bottom: 1px solid #ECECEC;
    margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}


.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 505px;
    width: 67.5%;


}

.col-md-12 > h3{

    
     color: #043868;

}

.pay{

    border:1px solid #ECECEC ;
    height: 105px;
    width: 100%;
}

.gray{

    background-color:#FFFFFF;
    color:#042C51;
}
.navbar {
    background-color: #FFFFFF;
}

.gray:hover{
    background-color:#F7FAFC;
    color:#84660A;
}

p{
    font-size: 18px;
}

.data{
    font-size: 15px;
}

.intro{
    color:#870415;
}

.red{
    color: #9E0423;

}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height: 49px;
}

.row {
    margin-left: 3px;
    margin-right: -15px;
}
.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}


</style>
<div class="container">
</hr>
    <div class="row-cell">
        <nav class="navbar navbar-default" role="navigation">
            <div class="col-md-3">
                <div class="btn-group">
                    <a href="<?php echo $this->url->get('wallet/account/')?>" class="btn btn-lg btn-custom gray" id="account">
                        <p>My Account &ensp; &ensp; </p></a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="btn-group">
                    <a href="<?php echo $this->url->get('wallet/payment/')?>" class="btn btn-lg btn-custom gray" id="payment">
                        <p>Payment History</p></a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="btn-group">
                    <a href="<?php echo $this->url->get('wallet/status/')?>" class="btn btn-lg btn-custom gray" id="status">
                        <p>Payment Status &ensp;  </p></a>
                </div>
                
            </div>
            <div class="col-md-3">
                <div class="btn-group">
                    <a href="<?php echo $this->url->get('wallet/withdraw/')?>" class="btn btn-lg btn-custom gray" id="withdraw">
                        <p>Payment Withdraw &ensp;  </p></a>
                </div>
                
            </div>
    
        </nav>
        <div class="col-md-12">

            <h3>Payment History</h3>
            <div class="seperator-dotted">
                
            </div>
            <?php foreach ($newresult as $row){?>
                <div class="pay">
                    <p class="data" ><b>Order Number</b>   : <?php echo $row->order_no;?></p>
                    <p class="data"><b>Payment Method</b>   : <?php echo $row->method_name;?></p>
                    <p class="data"><b>Transaction Amount</b>   : <?php echo $row->total;?></p>


                </div>
            </br>
            <?php }?>

            </br>
            </br>
        </div>
    </div>
</div>


<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[3];

    console.log(choice);

    if(choice=='account')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#account").addClass("red");
    }

    else if (choice=='payment')
    {
        //$("#purchase").html("<font color="red"> Purchase List </font>");
        $("#payment").addClass("red");
    }

    else if (choice=='status')
    {
        //$("#pending").html("<font color="red"> Pending List </font>");
        $("#status").addClass("red");
    }

    else if (choice=='withdraw')
    {
        //$("#reject").html("<font color="red"> Reject List </font>");
        $("#withdraw").addClass("red");
    }

</script>