<style>
.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 495px;
    width: 95%;
}


.red{
    color: #9E0423;

}

.navbar {
    background-color: #FFFFFF;
}

.data{
    font-size: 15px;
}

.red2{
    color: #9E0423;

}

h3{
    font-size: 18px;

}

</style>


<div class="row-cell">
    <nav class="navbar navbar-default" role="navigation">
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('wallet/account/')?>" class="btn btn-lg btn-custom gray" id="account">
                    <p>My Account &ensp; &ensp; </p>
                </a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('wallet/payment/')?>" class="btn btn-lg btn-custom gray" id="payment">
                    <p>Payment History</p>
                </a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('wallet/status/')?>" class="btn btn-lg btn-custom gray" id="status">
                    <p>Payment Status &ensp;  </p>
                </a>
            </div>
            
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('wallet/withdraw/')?>" class="btn btn-lg btn-custom gray" id="withdraw">
                    <p>Payment Withdraw &ensp;  </p>
                </a>
            </div>
            
        </div>
    
    </nav>

    <div class="col-md-12">

            <h3>Account Information</h3>
            <div class="seperator-dotted">

            </div>
                <p class="data" ><b>Account Holder</b>   : <?php echo $data['value']->account_holder_name;?></p>
                <p class="data"><b>Account No.</b>       :<?php echo $data['value']->account_no;?></p>
                <p class="data"><b>Bank</b>       : <?php echo $data['value']->bank_name;?></p>
                <p class="data"><b>Branch</b>   : <?php echo $data['value']->branch_name;?></p>
                <p class="data"><b>Swift Code</b> : <?php echo $data['value']->swift_code;?></p>

            </br>
            </br>
        </div>
    </div>
</div>


<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[3];

    console.log(choice);

    if(choice=='wallet')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#account").addClass("red2");
    }

    

</script>
</div>



