<style>
.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 495px;
    width: 95%;


}


.row-cell>.col-md-6{
    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 165px;
    width: 100%;

}

.btn-group{

    padding-top: 50px;
    padding-right: 290px;
    padding-bottom: 30px;
    padding-left: 320px;
    height:50px;
    width:150px;
}

.gray{

    background-color: #A0A0A0;
    color:#336699;
    

}

a{

    text-decoration: none;

}

</style>


<div class="row-cell">
    <div class="col-md-6">
        <div class="btn-group">
            <a href="<?php echo $this->url->get('wallet/account/')?>" class="btn btn-lg btn-custom gray"><p>My Account &ensp; &ensp; </p></a>
        </div>
    </div>
    <div class="col-md-6">
        <div class="btn-group">
            <a href="<?php echo $this->url->get('wallet/payment/')?>" class="btn btn-lg btn-custom gray"><p>Payment History</p></a>
        </div>
    </div>
    <div class="col-md-6">
        <div class="btn-group">
            <a href="<?php echo $this->url->get('wallet/status/')?>" class="btn btn-lg btn-custom gray"><p>Payment Status &ensp;  </p></a>
        </div>
        
    </div>
    
        
    </div>


</div>