<style>

h3{
    text-align:center;
}


.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 559px;
    width: 95%;
}



.product{

    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px; 
    border:1px solid #ECECEC ;
    border-radius: 4px;   

}
p{

    font-size: 15px;

}

.product > a{
    
    color: #585858;
    font-size: 15px;
}

a>i{
    float: right;
}

.delete{
    color:#106E96;
}

</style>


<div class="row-cell">

    <?php foreach ($Wish->items as $record){?>
    <div class="product">

        <a href="<?php echo $this->url->get("wishlist/details/" . $record->product_name); ?>">
            <?php echo $record->product_name; ?>
        </a>

        <a href="<?php echo $this->url->get("wishlist/delete/" . $record->product_name); ?>">
            <i class="delete fa fa-trash-o fa-lg" ></i>
        </a>
        
    </div>
    <?php }?>

    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Wish->current, " of ", $Wish->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("Wishlist/wish" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("Wishlist/wish?page=" . $Wish->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("Wishlist/wish?page=" . $Wish->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("Wishlist/wish?page=" . $Wish->last); ?>">Last</a></li>            
        </ul>

    </div>

</div>
