<style>
h4{
    color:#660099;

}

p > a:hover{

    background-color: #52575F;
    color: white;
}


</style>
<div class="row">

    <div class="item-area">

        <div class="col-md-8 col-md-offset-2">
            <div class="info">
                <Strong> Product Name: </strong><b><?php echo $heading;?></b>
            </div>
            <div class="info">
                <Strong> Description: </strong><?php echo $description;?>
            </div>

            <div class="info">
                <Strong> Price: </strong><?php echo $price;?>
            </div>
            <div class="info">
                <Strong> Discount Rate: </strong><?php echo $discount;?>
            </div>
            
        </div>


    </div>
    

</div>