<style>

h3{
    text-align:center;
}

.settings-area {
    font-size: 13px;
    position: absolute;
    right: 60px;
    text-align: right;
    top: 10px;
}

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 805px;
    width: 95%;
}


a{

    text-decoration: none;
    color:#870415;
    
    font-size: 15px;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}

.dash{

    text-align: left;
    font-size: 30px;
    padding-top: 0px;
    padding-right: 0px;
    padding-bottom: 0px;
    padding-left: 10px;
    color: #106E96;
}


.seperator-dotted{
    width: 100%;
    border-bottom: 1px solid #ECECEC;
    margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}


strong > a{

    color:#A8A8A8;
    font-size: 15px;
    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px;

}

strong > a:hover{

    background-color: #52575F;
    color: white;
}


i{

    font-size:20px;

}

.product{

    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px; 
    border:1px solid #ECECEC ;
    border-radius: 4px;   

}
p{

    font-size: 15px;

}

.product > a{
    
    color: #585858;
    font-size: 15px;
}

.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}

a>i{
    float: right;
}

.pager{
    color:#000000;
}

li>a{
    color: #106E96;
}

.delete{
    color:#106E96;
}

.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
}
</style>


<div class="row-cell">

    <div >
        <p class="dash">My WishList</p>
    </div>
    <div class="seperator-dotted"></div>

    <?php foreach ($Wish->items as $record){?>
    <div class="product">

        <a href="<?php echo $this->url->get("wishlist/details/" . $record->product_name); ?>">
            <?php echo $record->product_name; ?>
        </a>

        <a href="<?php echo $this->url->get("wishlist/delete/" . $record->product_name); ?>">
            <i class="delete fa fa-trash-o fa-lg" ></i>
        </a>
        
    </div>
    <?php }?>

    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Wish->current, " of ", $Wish->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("Wishlist/wish" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("Wishlist/wish?page=" . $Wish->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("Wishlist/wish?page=" . $Wish->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("Wishlist/wish?page=" . $Wish->last); ?>">Last</a></li>            
        </ul>

    </div>

</div>
