 <!-- mid menu part -->
<style>

</style>


<style type="text/css">
/*****************************************************
 * generic styling for ALS elements: outer container
 ******************************************************/

.als-container {
  position: relative;
  width: 100%;
  margin: 0px auto;
  z-index: 0;
}

/****************************************
 * viewport styling
 ***************************************/

.als-viewport {
  position: relative;
  overflow: hidden;
  margin: 0px auto;
  height:393px;
  width:960px;
}



/***************************************************
 * wrapper styling
 **************************************************/

.als-wrapper {
  position: relative;
  width:1920px;
  height:393px;
  /* if you are using a list with <ul> <li> */
  
}



/*************************************
 * item: single list element
 ************************************/

#my-als-list .als-item {
  position: relative;
  display: block;
  text-align: center;
  cursor: pointer;
  float: left;
}

#my-als-list2 .als-item {
  position: relative;
  display: block;
  text-align: center;
  cursor: pointer;
  float: left;
}

#my-als-list3 .als-item {
  position: relative;
  display: block;
  text-align: center;
  cursor: pointer;
  float: left;
}


.als-item{
  margin-top: 40px;
  margin-right: 20px;
  margin-bottom: 40px;
  margin-left: 20px;
}



/***********************************************
 * prev, next: buttons styling
 **********************************************/
 
.als-prev, .als-next {
  position: absolute;
  cursor: pointer;
  clear: both;
}








</style>

<?php echo \Phalcon\Tag::stylesheetLink("main/css/home.css"); ?>

<script type="text/javascript">

function processWish(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find = id.toString().concat(id.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(find);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

        if (result=="1") {$('#notLoggedInModal').modal('show');
        setTimeout( "jQuery('#notLoggedInModal').modal('hide');",3000 );
      }
       else if (result=="2") {$('#productInWishlistModal').modal('show');
        setTimeout( "jQuery('#productInWishlistModal').modal('hide');",3000 );
      }
       else if (result=="3") {$('#productAddedInWishlist').modal('show');
       setTimeout( "jQuery('#productAddedInWishlist').modal('hide');",3000 );
     }
 
    });

    //alert(id);

   
    }

$(function(){
$('.wish').on('click', function(e) {

//subcategories();
 var wishId = e.target.id;

 //clicked(idClicked);
 processWish(wishId);

  });
});

function processWishB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find1 = id.toString().concat(id.toString()); 
  var find11 = find1.toString().concat(id.toString());

    $.ajax({

        type: "POST",
        url: base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find11).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            //console.log(find);
            //alert("result");
           // console.log(result);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

        if (result=="1") {$('#notLoggedInModal').modal('show');
        setTimeout( "jQuery('#notLoggedInModal').modal('hide');",3000 );
      }
       else if (result=="2") {$('#productInWishlistModal').modal('show');
        setTimeout( "jQuery('#productInWishlistModal').modal('hide');",3000 );
      }
       else if (result=="3") {$('#productAddedInWishlist').modal('show');
       setTimeout( "jQuery('#productAddedInWishlist').modal('hide');",3000 );
     }
 
    });

    



    //alert(id);

   
    }

$(function(){
$('.wishB').on('click', function(e) {

//subcategories();
 var wishIdB = e.target.id;
 var wishIdB1 = wishIdB.toString().split(":")[0]; 

 //clicked(idClicked);
 processWishB(wishIdB1);

  });


});


function processWishC(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find1 = id.toString().concat(id.toString()); 
  var find11 = find1.toString().concat(id.toString());

    $.ajax({

        type: "POST",
        url: base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find11).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            //console.log(find);
            //alert("result");
           // console.log(result);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       if (result=="1") {$('#notLoggedInModal').modal('show');}
       else if (result=="2") {$('#productInWishlistModal').modal('show');}
       else if (result=="3") {$('#productAddedInWishlist').modal('show');}
 
    });

    



    //alert(id);

   
    }

$(function(){
$('.wishC').on('click', function(e) {

//subcategories();
 var wishIdB = e.target.id;
 var wishIdB1 = wishIdB.toString().split(":")[0]; 

 //clicked(idClicked);
 processWishB(wishIdB1);

  });


});



function processCart(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var p_id = id.toString().split(":")[0]; 

  var msg = p_id.toString().concat(p_id.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/addtocart",
        //dataType: "json",
        data: { data1 : p_id, },
        success: function(result)
        {
            //$("#my_count").html(html);
           console.log("count is"+result);
            if(result!="")
              $("#my_count").html(result);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(p_id);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);


       //if (result=="") {$('#productExistCartModal').modal('show');}
       //else {$('#productAddedCartModal').modal('show');}
 
    });

    //alert(id);

   
    }

$(function(){
$('.cart').on('click', function(e) {

//subcategories();
 var cartId = e.target.id;

 //clicked(idClicked);
 processCart(cartId);
 //Fly effect
 var cart = $('.shopping-cart-button .glyphicon-shopping-cart');
        var imgtodrag = $(this).parent().parent().siblings(".img-responsive").eq(0);
        //var src = imgtodrag.attr("src");
        //console.log("fly");
        //console.log(src);
        if (imgtodrag) {
            var imgclone = imgtodrag.clone()
                .offset({
                top: imgtodrag.offset().top,
                left: imgtodrag.offset().left
            })
                .css({
                'opacity': '0.5',
                    'position': 'absolute',
                    'height': '150px',
                    'width': '150px',
                    'z-index': '100'
            })
                .appendTo($('body'))
                .animate({
                'top': cart.offset().top + 10,
                    'left': cart.offset().left + 10,
                    'width': 250,
                    'height': 400
            }, 1000, 'easeInOutExpo');
            
            setTimeout(function () {
                cart.parent().effect("shake", {
                    times: 2
                }, 200);
            }, 1500);

            imgclone.animate({
                'width': 0,
                    'height': 0
            }, function () {
                $(this).detach()
                location.reload();
            });
        }



  });
});

function processCartB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var p_idB = id.toString().split(":")[0]; 

  var msgB = p_idB.toString().concat(p_idB.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/addtocart",
        data: { data1 : p_idB, },
        success: function(result)
        {
            //$("#my_count").html(html);
            if(result!="")
              $("#my_count").html(result);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(p_idB);
        }
      })
    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);
       window.location.href=window.location.href;

       //if (result=="") {$('#productExistCartModal').modal('show');}
       //else {$('#productAddedCartModal').modal('show');}
 
    });


    //alert(id);

   
    }

$(function(){
$('.cartB').on('click', function(e) {

//subcategories();
 var cartIdB = e.target.id;
 //var cartIdB1 = cartIdB.toString().split(":")[0];
 //var cartIdB = $(this).attr('href');
 //clicked(idClicked);
 processCart(cartIdB);

 //Fly effect

 var cart = $('.shopping-cart-button .glyphicon-shopping-cart');
         var imgtodrag = $(this).parent().siblings(".drag").children(".img-responsive").eq(0);
        //var src = imgtodrag.attr("src");
        //console.log("fly");
        //console.log(src);
        if (imgtodrag) {
            var imgclone = imgtodrag.clone()
                .offset({
                top: imgtodrag.offset().top,
                left: imgtodrag.offset().left
            })
                .css({
                'opacity': '0.5',
                    'position': 'absolute',
                    'height': '150px',
                    'width': '150px',
                    'z-index': '100'
            })
                .appendTo($('body'))
                .animate({
                'top': cart.offset().top + 10,
                    'left': cart.offset().left + 10,
                    'width': 250,
                    'height': 400
            }, 1000, 'easeInOutExpo');
            
            setTimeout(function () {
                cart.parent().effect("shake", {
                    times: 2
                }, 200);
            }, 1500);

            imgclone.animate({
                'width': 0,
                    'height': 0
            }, function () {
                $(this).detach()
                location.reload();
            });
        }

  });
});


function processCartC(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var p_idB = id.toString().split(":")[0]; 

  var msgB = p_idB.toString().concat(p_idB.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/addtocart",
        data: { data1 : p_idB, },
        success: function(result)
        {
            //$("#my_count").html(html);
            if(result!="")
              $("#my_count").html(result);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(p_idB);
        }
      })
    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       //if (result=="") {$('#productExistCartModal').modal('show');}
       //else {$('#productAddedCartModal').modal('show');}
 
    });


    //alert(id);

   
    }

$(function(){
$('.cartC').on('click', function(e) {

//subcategories();
 var cartIdB = e.target.id;
 //var cartIdB1 = cartIdB.toString().split(":")[0];
 //var cartIdB = $(this).attr('href');
 //clicked(idClicked);
 processCart(cartIdB);

 //Fly effect

 var cart = $('.shopping-cart-button .glyphicon-shopping-cart');
        var imgtodrag = $(this).parent().parent().siblings(".img-responsive").eq(0);
        //var src = imgtodrag.attr("src");
        //console.log("fly");
        //console.log(src);
        if (imgtodrag) {
            var imgclone = imgtodrag.clone()
                .offset({
                top: imgtodrag.offset().top,
                left: imgtodrag.offset().left
            })
                .css({
                'opacity': '0.5',
                    'position': 'absolute',
                    'height': '150px',
                    'width': '150px',
                    'z-index': '100'
            })
                .appendTo($('body'))
                .animate({
                'top': cart.offset().top + 10,
                    'left': cart.offset().left + 10,
                    'width': 250,
                    'height': 400
            }, 1000, 'easeInOutExpo');
            
            setTimeout(function () {
                cart.parent().effect("shake", {
                    times: 2
                }, 200);
            }, 1500);

            imgclone.animate({
                'width': 0,
                    'height': 0
            }, function () {
                $(this).detach()
                location.reload();
            });
        }

  });
});

 $(document).ready(function(){

 $("#my-als-list").als({
          visible_items: 4,
          scrolling_items: 1,
          orientation: "horizontal",
          circular: "yes",
          autoscroll: "no",
          speed: 250

        }); 
    
  });

   /*$("#my-als-list2").als({
          visible_items: 4,
          scrolling_items: 1,
          orientation: "horizontal",
          circular: "yes",
          autoscroll: "no",
          speed: 250

        }); 
    
  });

  $("#my-als-list3").als({
          visible_items: 4,
          scrolling_items: 1,
          orientation: "horizontal",
          circular: "yes",
          autoscroll: "no",
          speed: 250

        }); 
    
  });*/


</script>

<script type="text/javascript">

  $(document).ready(function() {
     $('.bottom_text2').hide();

     $('.hover2').hover(
         function () {
           //$(this).addClass("open");
            var id = $(this).attr('id');
            console.log(id);
            
             $('#'+id).children().children(".bottom_text2").show();
             
        }, 
         function () {
           //$(this).removeClass("open");
             $('.bottom_text2').hide();
             
         }
     );

    });

</script>


<script type="text/javascript">

  $(document).ready(function() {
     $('.bottom_text3').hide();

     $('.hover3').hover(
         function () {
           //$(this).addClass("open");
            var idB = $(this).attr('product_id');
            console.log(idB);
            
             $(this).children().children(".bottom_text3").show();
             
        }, 
         function () {
           //$(this).removeClass("open");
             $('.bottom_text3').hide();
             
         }
     );

    });

</script>




<div role="tabpanel">
  <div class="container">
    <div class="tabbable">
      <div class="mid-menu">
        <ul class="nav nav-tabs">
      
          <li class="active" ><a href="#pane1" data-toggle="tab"><div class="item">New Products</div></a></li>
          <li ><a href="#pane2" data-toggle="tab"><div class="item">Hot Products</div></a></li>
          <li ><a href="#pane3" data-toggle="tab"><div class="item">Best Selling</div></a></li>

        </ul>
      </div>

      <div class="red-joint"></div>
    </div>

      
    
  </div>

 <div class="tab-content">
  <div id="pane1" class="tab-pane active ">
    <div class="als-container" id="my-als-list">
      <span class="als-prev" style="left: 150px;top: 150px;">
        <img src="<?php echo $this->url->get().'main/images/';?>left.png" alt="prev" title="previous" />
      </span>
      <div class="als-viewport">
        <div class="als-wrapper">
      
     
    <?php foreach ($newResult as $row){?>
    
   
    <div class="als-item ">
      <div class="hover4">

      <div class="item" >
        
        <div class="text2">
          <p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".$row->product_description; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          <div id="<?php echo $row->id;echo $row->id; ?>"> </div>
          <div class="bottom_text">
            <button class="cart" id="<?php echo $row->id; echo ":"; echo $row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp;&ensp; Add to Cart
            </button>
            
            <button class="wish" id="<?php echo $row->id; ?>" type="button">
              <span>Add to Wishlist&ensp; &ensp; </span>
            </button>
          </div>
        </div>
        
        <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>" style="width : 200px; height : 250px;"></img>
      
      </br>
        <div class="product_price"></div>
      </div> <!--item -->
    
    </div> <!--hover -->
  </div> <!--ais-item -->

    <?php }?>

    </div> <!--wrapper -->
    </div> <!--ais-viewport -->
    <span class="als-next" style="right: 150px; top: 150px;">
      <img src="<?php echo $this->url->get().'main/images/';?>right.png" alt="next" title="next" />
    </span> <!-- "next" button -->
    </div> <!--als-container-->

    </div> <!---pane1 !-->



    <div id="pane2" class="tab-pane">
    <div class="als-container" id="my-als-list2">
      <span class="als-prev" style="left: 150px; top: 150px;">
        <img src="<?php echo $this->url->get().'main/images/';?>left.png" alt="prev" title="previous" />
      </span>
      <div class="als-viewport">
        <div class="als-wrapper">
      
     
    <?php foreach ($hotResult as $row){?>
    
   
    <div class="als-item">
      <div class="hover4">

      <div class="item" id="top_item">
        
        <div class="text2"><p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".$row->product_description; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          <div id="<?php echo $row->id;echo $row->id; ?>"> </div>
          <div class="bottom_text">
              <button class="cart" id="<?php echo $row->id; echo ":"; echo $row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp;&ensp; Add to Cart
            </button>
            
            <button class="wish" id="<?php echo $row->id; ?>" type="button">
              <span>Add to Wishlist&ensp; &ensp; </span>
            </button>
          </div>
        </div>
        <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>" style="width : 200px; height : 250px;"></img>
      </br>
        
      </div>
    
  </div>
</div>

    <?php }?>

    </div> <!--wrapper -->
    </div> <!--ais-viewport -->
    <span class="als-next" style="right: 150px; top: 150px;">
      <img src="<?php echo $this->url->get().'main/images/';?>right.png" alt="next" title="next" />
    </span> <!-- "next" button -->
    </div> <!--als-container-->

    </div> <!---pane2 !-->

 <div id="pane3" class="tab-pane">
    <div class="als-container" id="my-als-list3">
      <span class="als-prev" style="left: 150px; top: 150px">
        <img src="<?php echo $this->url->get().'main/images/';?>left.png" alt="prev" title="previous" />
      </span>
      <div class="als-viewport">
        <div class="als-wrapper">
      
     
    <?php foreach ($bestResult as $row){?>
    
   
    <div class=" als-item">
      <div class="hover4">

      <div class="item" id="top_item">
        
        <div class="text2"><p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".$row->product_description; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          <div id="<?php echo $row->id;echo $row->id; ?>"> </div>
          <div class="bottom_text">
             <button class="cart" id="<?php echo $row->id; echo ":"; echo $row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp;&ensp; Add to Cart
            </button>
            
            <button class="wish" id="<?php echo $row->id; ?>" type="button">
              <span>Add to Wishlist&ensp; &ensp; </span>
            </button>
          </div>
        </div>
        <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>" style="width : 200px; height : 250px;"></img>
      </br>
        
      </div>
    
  </div>
</div>

    <?php }?>

    </div> <!--wrapper -->
    </div> <!--ais-viewport -->
    <span class="als-next" style="right: 150px; top: 150px;">
      <img src="<?php echo $this->url->get().'main/images/';?>right.png" alt="next" title="next" />
    </span> <!-- "next" button -->
    </div> <!--als-container-->

    </div> <!---pane3 !-->

    



    
  </div><!-- /.tab-content --> 
   </div> <!-- /.tabpanel -->



  
  
  <!-- mid menu part ends here -->


  <!-- item area part -->

  <!-- item area part ends -->


  <?php echo $this->partial('shared/ad'); ?>


  <!-- bottom item area -->

  <div class="container bottom-item-area">
    <div class="col-md-9">
      <div class="row product">
       <?php foreach ($bottomResult as $bottomrow){?>
        <div class="col-md-3 hover3" product_id="<?php echo $bottomrow->id; ?>"  >
         
          <div class="item">
 
            <a href="<?php echo $this->url->get().'index/productdetails/'.$bottomrow->id;?>" class="drag">
              <img class="img-responsive" src="<?php echo $this->url->get().$bottomrow->picture;?>"></img>
            </a>
            <a href="<?php echo $this->url->get().'index/productdetails/'.$bottomrow->id;?>">
              <div class="product-name"><?php echo substr($bottomrow->product_name,0,18);?></div>
            </a>
            
            <div class="product-price">$<?php echo $bottomrow->price; ?></div>

            <div class="bottom_text3" product_id="<?php echo $bottomrow->id; ?>">
              <button class="cartB" id="<?php echo $bottomrow->id.":".$bottomrow->id.":".$bottomrow->id;?>" type="button" name="submit" value="test">
                <span class="glyphicon glyphicon-shopping-cart"></span>&ensp; Add to cart &ensp;
              </button>
              <button class="wishB" id="<?php echo $bottomrow->id.":".$bottomrow->id; ?>" type="button">
               <span>Add to Wishlist</span>
              </button>

            </div>
            
          </div>

        </div>
       <?php }?>
         
      </div> <!-- row ends !-->
    </div>
    <div class="col-md-3">
      <div class="portal">
        <img src="<?php echo $this->url->get().'main/images/';?>job.jpg" class="img-responsive" alt="..." width="100%" style="height:100%;">
      </div>
      <div class="portal">
        <img src="<?php echo $this->url->get().'main/images/';?>travel.jpg" class="img-responsive" alt="..." width="100%" style="height:100%;">

      </div>

    </div>
  </div>

  <!-- bottom item area ends here -->

<!--Modals !-->

<div class="modal fade" id="notLoggedInModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
          <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> You need to log in first. </center> 
                </p>
            </div>
            
        </div>
    </div>
</div>

<div class="modal fade" id="productInWishlistModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
          <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> This product already exists in your wish list. </center> 
                </p>
            </div>

            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'wishlist/wish/';?>">

                Go to Wishlist
              </a>
            </div>
            
        </div>
  </div>
</div>

<div class="modal fade" id="productAddedInWishlist" tabindex="-1" role="dialog" aria-labelledby="productAddedInWishlist" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
          <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> Wish list updated successfully. </center> 
                </p>
            </div>

            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'wishlist/wish/';?>">

                Go to Wishlist
              </a>
            </div>
            
    </div>
  </div>
</div>


<div class="modal fade" id="productAddedCartModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Product successfully added to the cart</center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productExistCartModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Quantity incremented for this product. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>


