 <!-- mid menu part -->
<style>

.hover {
    display: inline-block;
    overflow: hidden;
    position: relative;
  text-decoration:none;
  
}
.hover .text {
    display: none;
    background: rgba(0,0,0,0.5);
  
    opacity: 0;
    position: absolute;
    width: 100%;
    height:100%;
    color: #ffffff;
    text-align:center;
    left: 0;
    top: 0;
  
   -webkit-transition: opacity 500ms;
     -moz-transition: opacity 500ms;
     -o-transition: opacity 500ms;
     transition: opacity 500ms;
}
.hover:hover .text { display: block; opacity: 1;}

.text .top_text{margin-top: 35%;}

.text .bottom_text{margin-top: 40%;}

.text .bottom_text2{margin-top: 20%;}

.nav-tabs> li.active > a, .nav-tabs> li.active > a:hover, .nav-tabs> li.active > a:focus {border-width: 0;}

.nav-tabs> li > a, .nav-tabs> li > a:hover {border: none; background-color: #ffffff;}

.nav-tabs {border-bottom: none;}

.cart, .wish, .wishB, .cartB{background-color: #454545; border:none; }

.mid-menu .active .item{

  border: 2px solid #cc0001;
}

.modal-margin-top{
  margin-top: 40%;
}

.portal{
  border:0px;
}


</style>

<script type="text/javascript">

function processWish(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find = id.toString().concat(id.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(find);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       if (result=="1") {$('#notLoggedInModal').modal('show');}
       else if (result=="2") {$('#productInWishlistModal').modal('show');}
       else if (result=="3") {$('#productAddedInWishlist').modal('show');}
 
    });

    //alert(id);

   
    }

$(function(){
$('.wish').on('click', function(e) {

//subcategories();
 var wishId = e.target.id;

 //clicked(idClicked);
 processWish(wishId);

  });
});

function processWishB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find1 = id.toString().concat(id.toString()); 
  var find11 = find1.toString().concat(id.toString());

    $.ajax({

        type: "POST",
        url: base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find11).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            //console.log(find);
            //alert("result");
           // console.log(result);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       if (result=="1") {$('#notLoggedInModal').modal('show');}
       else if (result=="2") {$('#productInWishlistModal').modal('show');}
       else if (result=="3") {$('#productAddedInWishlist').modal('show');}
 
    });

    



    //alert(id);

   
    }

$(function(){
$('.wishB').on('click', function(e) {

//subcategories();
 var wishIdB = e.target.id;
 var wishIdB1 = wishIdB.toString().split(":")[0]; 

 //clicked(idClicked);
 processWishB(wishIdB1);

  });


});



function processCart(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var p_id = id.toString().split(":")[0]; 

  var msg = p_id.toString().concat(p_id.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/addtocart",
        data: { data1 : p_id, },
        success: function(result)
        {
            //$("#my_count").html(html);
            if(result!="")
              $("#my_count").html(result);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(p_id);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       //if (result=="") {$('#productExistCartModal').modal('show');}
       //else {$('#productAddedCartModal').modal('show');}
 
    });

    //alert(id);

   
    }

$(function(){
$('.cart').on('click', function(e) {

//subcategories();
 var cartId = e.target.id;

 //clicked(idClicked);
 processCart(cartId);
 //Fly effect
 var cart = $('.shopping-cart .glyphicon-shopping-cart');
        var imgtodrag = $(this).parent().parent().siblings(".img-responsive").eq(0);
        //var src = imgtodrag.attr("src");
        //console.log("fly");
        //console.log(src);
        if (imgtodrag) {
            var imgclone = imgtodrag.clone()
                .offset({
                top: imgtodrag.offset().top,
                left: imgtodrag.offset().left
            })
                .css({
                'opacity': '0.5',
                    'position': 'absolute',
                    'height': '150px',
                    'width': '150px',
                    'z-index': '100'
            })
                .appendTo($('body'))
                .animate({
                'top': cart.offset().top + 10,
                    'left': cart.offset().left + 10,
                    'width': 250,
                    'height': 400
            }, 1000, 'easeInOutExpo');
            
            setTimeout(function () {
                cart.parent().effect("shake", {
                    times: 2
                }, 200);
            }, 1500);

            imgclone.animate({
                'width': 0,
                    'height': 0
            }, function () {
                $(this).detach()
            });
        }



  });
});

function processCartB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var p_idB = id.toString().split(":")[0]; 

  var msgB = p_idB.toString().concat(p_idB.toString()); 

    $.ajax({

        type: "POST",
        url: base_url+"index/addtocart",
        data: { data1 : p_idB, },
        success: function(result)
        {
            //$("#my_count").html(html);
            if(result!="")
              $("#my_count").html(result);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(p_idB);
        }
      })
    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       //if (result=="") {$('#productExistCartModal').modal('show');}
       //else {$('#productAddedCartModal').modal('show');}
 
    });


    //alert(id);

   
    }

$(function(){
$('.cartB').on('click', function(e) {

//subcategories();
 var cartIdB = e.target.id;
 //var cartIdB1 = cartIdB.toString().split(":")[0];
 //var cartIdB = $(this).attr('href');
 //clicked(idClicked);
 processCart(cartIdB);

 //Fly effect

 var cart = $('.shopping-cart .glyphicon-shopping-cart');
        var imgtodrag = $(this).parent().parent().siblings(".img-responsive").eq(0);
        //var src = imgtodrag.attr("src");
        //console.log("fly");
        //console.log(src);
        if (imgtodrag) {
            var imgclone = imgtodrag.clone()
                .offset({
                top: imgtodrag.offset().top,
                left: imgtodrag.offset().left
            })
                .css({
                'opacity': '0.5',
                    'position': 'absolute',
                    'height': '150px',
                    'width': '150px',
                    'z-index': '100'
            })
                .appendTo($('body'))
                .animate({
                'top': cart.offset().top + 10,
                    'left': cart.offset().left + 10,
                    'width': 250,
                    'height': 400
            }, 1000, 'easeInOutExpo');
            
            setTimeout(function () {
                cart.parent().effect("shake", {
                    times: 2
                }, 200);
            }, 1500);

            imgclone.animate({
                'width': 0,
                    'height': 0
            }, function () {
                $(this).detach()
            });
        }

  });
});


</script>



<div class="container">

  
  <div class="tabbable">
  <div class="mid-menu">
  <ul class="nav nav-tabs">
    
    <li class="active"><a href="#pane1" data-toggle="tab"><div class="item">New Products</div></a></li>
    <li><a href="#pane2" data-toggle="tab"><div class="item">Hot Products</div></a></li>
    <li><a href="#pane3" data-toggle="tab"><div class="item">Best Selling</div></a></li>
  </ul>
  </div>

  <div class="red-joint"></div>
   
  <div class="tab-content">
    <div id="pane1" class="tab-pane active">
    <div class="container item-area">
    <?php foreach ($newResult as $row){?>
  
    <div class="col-md-3 hover">
      <div class="item">
        <div class="text"><p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".$row->product_description; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          <div id="<?php echo $row->id;echo $row->id; ?>"> </div>
          <div class="bottom_text">
            <button class="cart" id="<?php echo $row->id; echo ":"; echo $row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp; Add to Cart
            </button>
            &ensp; <i class="fa fa-minus fa-rotate-90"></i> &ensp;
            <button class="wish" id="<?php echo $row->id; ?>" type="button">
              <span class="glyphicon glyphicon-heart"></span>
            </button>
          </div>
        </div>
        <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>"></img>
        <div class="price">Price: <?php echo $row->price; ?> </div>
      </div>
    </div>

    <?php }?>

    </div> <!---Container item-area !-->

    </div> <!---pane1 !-->
    <div id="pane2" class="tab-pane">
    <div class="container item-area">
    <?php foreach ($hotResult as $row){?>
  
    <div class="col-md-3 hover">
      <div class="item">
        <div class="text"><p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".$row->product_description; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          <div id="<?php echo $row->id;echo $row->id; ?>"> </div>
          <div class="bottom_text">
            <button class="cart" id="<?php echo $row->id; echo ":"; echo $row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp; Add to Cart
            </button>
            &ensp; <i class="fa fa-minus fa-rotate-90"></i> &ensp;
            <button class="wish" id="<?php echo $row->id; ?>" type="button">
              <span class="glyphicon glyphicon-heart"></span>
            </button>
          </div>
        </div>
        <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>"></img>
        <div class="price">Price: <?php echo $row->price; ?> </div>
      </div>
    </div>

    <?php }?>

    </div> <!---Container item-area !-->
    </div> <!---pane2 !-->
    <div id="pane3" class="tab-pane">
    <div class="container item-area">
    <?php foreach ($bestResult as $row){?>
  
    <div class="col-md-3 hover">
      <div class="item">
        <div class="text"><p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".$row->product_description; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          <div id="<?php echo $row->id;echo $row->id; ?>"> </div>
          <div class="bottom_text">
            <button class="cart" id="<?php echo $row->id; echo ":"; echo $row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp; Add to Cart
            </button>
            &ensp; <i class="fa fa-minus fa-rotate-90"></i> &ensp;
            <button class="wish" id="<?php echo $row->id; ?>" type="button">
              <span class="glyphicon glyphicon-heart"></span>
            </button>
          </div>
        </div>
        <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>"></img>
        <div class="price">Price: <?php echo $row->price; ?> </div>
      </div>
    </div>

    <?php }?>

    </div> <!---Container item-area !-->
    </div><!---pane3 !-->
  </div><!-- /.tab-content -->

  </div>

      
    
  </div>
  <!-- mid menu part ends here -->


  <!-- item area part -->

  <!-- item area part ends -->


  <?php echo $this->partial('shared/ad'); ?>


  <!-- bottom item area -->

  <div class="container bottom-item-area">
    <div class="col-md-9">
      <div class="row product">
       <?php foreach ($bottomResult as $row){?>
        <div class="col-md-3 hover">
          <div class="item">
        <div class="text"><p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".substr($row->product_description,0,19).'..'; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          <div id="<?php echo $row->id.$row->id.$row->id; ?>"> </div>
          <div class="bottom_text2">
            <button class="cartB" id="<?php echo $row->id.":".$row->id.":".$row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp; Add to Cart
            </button>
            &ensp; <i class="fa fa-minus fa-rotate-90"></i> &ensp;
            <button class="wishB" id="<?php echo $row->id.":".$row->id; ?>" type="button">
              <span class="glyphicon glyphicon-heart"></span>
            </button>
          </div>
        </div>            


            <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>"></img>
            <div class="product-name"><?php echo substr($row->product_name,0,18);?></div>
            <div class="product-price">$<?php echo $row->price; ?></div>
          </div>
        </div>
       <?php }?>
         
      </div> <!-- row ends !-->
    </div>
    <div class="col-md-3">
      <div class="portal">
        <img src="<?php echo $this->url->get().'main/images/';?>job.jpg" class="img-responsive" alt="..." width="100%" style="height:100%;">
      </div>
      <div class="portal">
        <img src="<?php echo $this->url->get().'main/images/';?>travel.jpg" class="img-responsive" alt="..." width="100%" style="height:100%;">

      </div>

    </div>
  </div>

  <!-- bottom item area ends here -->

<!--Modals !-->

<div class="modal fade" id="notLoggedInModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> You need to log in first. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productInWishlistModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> This product already exists in your wish list. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productAddedInWishlist" tabindex="-1" role="dialog" aria-labelledby="productAddedInWishlist" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Wish list updated successfully. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>


<div class="modal fade" id="productAddedCartModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Product successfully added to the cart</center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="productExistCartModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> Quantity incremented for this product. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>


