<style type="text/css">
.image{
  width: 100%;
  border: 1px solid #dadada;
  margin-top: 20px;
  padding: 5px 5px 0;
  height: 370px;
}

.image-small{
  width: 100%;
  border: 1px solid #dadada;
  margin-top: 20px;
  padding: 5px 5px 0;
  height: 110px;
}

.price-table{
  border: 1px solid #dadada;
  text-align: center;
  margin-top: 20px;
  padding: 5px 5px 0;
}

.box{
  border: 1px solid #dadada;
  margin-top: 20px;
  padding: 5px 5px 0;
  font-size: 15px;
}



.bg-button, .bg-button:hover, .bg-button:focus {
    background-color: #909090;
    color: white;
    font-size: 16px;
    width: 100%;
    border: none;
}

.modal-margin-top{
  margin-top: 30%;
}

.modal-footer {
    border-top: none;
    margin-top: 0;
    padding: 15px 25px;
    text-align: right;
}

.modal-footer button{
    width: 30%;
}

/**For hover effect **/
.hover {
    display: inline-block;
    overflow: hidden;
    position: relative;
    text-decoration:none;
  
}
.hover .text {
    display: none;
    background: rgba(0,0,0,0.5);
  
    opacity: 0;
    position: absolute;
    width: 100%;
    height:100%;
    color: #ffffff;
    text-align:center;
    left: 0;
    top: 0;
  
   -webkit-transition: opacity 500ms;
     -moz-transition: opacity 500ms;
     -o-transition: opacity 500ms;
     transition: opacity 500ms;
}
.hover:hover .text { display: block; opacity: 1;}

.text .top_text{margin-top: 35%;}

.text .bottom_text{margin-top: 70%;}
.hover .cart, .hover .wish, .hover .cartB{background-color: #454545; border:none; }

.mid-menu {
    display: table;
    height: auto;
    margin: 40px auto 10px;
    width: auto;
}

.nav-tabs {
    border-bottom: medium none;
}

.lis-group-item, .active {
    border: 0 none;
}

.red-joint {
    border-bottom: 1px solid #cc0001;
    margin-top: -30px;
    width: 100%;
}
.mid-menu .active .item {
    border: 2px solid #cc0001;
}

.nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
  border-color: none;
}

.review_name{
  font-size: 20px;
  margin-top: 14px;
  margin-left: -50px;
}


#reviewe_form>.input-lg{
  margin-left: -50px;
  width:75%;
}

#rev_button>.input-lg{
  width:30%;
  margin-left: -50px;
}

.comment_section{
  margin-left:-50px;
  margin-top: 10px;
  font-size: 18px;
 
}

#details_comments{
  background: none repeat scroll 0 0 #f7f8fa;
  border: medium none;
 
  margin-bottom: 10px;
  padding-top: 5px;
  text-transform: none;
  font-size: 14px;
  margin-left: -50px;

}

</style>

<style type="text/css">
/*****************************************************
 * generic styling for ALS elements: outer container
 ******************************************************/

.als-container {
  position: relative;
  width: 100%;
  margin: 0px auto;
  z-index: 0;
}

/****************************************
 * viewport styling
 ***************************************/

.als-viewport {
  position: relative;
  overflow: hidden;
  margin: 0px auto;
}

/***************************************************
 * wrapper styling
 **************************************************/

.als-wrapper {
  position: relative;
  /* if you are using a list with <ul> <li> */
  
}

/*************************************
 * item: single list element
 ************************************/

#my-als-list .als-item {
  position: relative;
  display: block;
  text-align: center;
  cursor: pointer;
  float: left;
  padding: 10px;
}

#up-list .als-item {
  position: relative;
  display: block;
  text-align: center;
  cursor: pointer;
  float: left;
  height: 115px;
  width: 100%;
 
}


/***********************************************
 * prev, next: buttons styling
 **********************************************/
 
.als-prev, .als-next {
  position: absolute;
  cursor: pointer;
  clear: both;
}


</style>

<style type="text/css">


.price{
  border:1px solid #DADADA;
  height: 50px;
  margin-top:10px; 
  padding: 10px;
  color: #717171;
}

.below_image{
  text-align: center;
}
</style>


<script type="text/javascript">
  $(document).ready(function(){
    //$("#my-als-list").als();
    $("#up-list").als({
          visible_items: 3,
          scrolling_items: 1,
          orientation: "vertical",
          circular: "yes",
          autoscroll: "no",
          speed: 200,
          direction: "down"
        });



    $("#my-als-list").als({
          visible_items: 4,
          scrolling_items: 1,
          orientation: "horizontal",
          circular: "yes",
          autoscroll: "no",
          speed: 250
        });

    
    
  }); 
</script>

<script type="text/javascript">
 function processWish(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var find = id.toString().concat(id.toString()); 

    $.ajax({

        type: "POST",
        url:base_url+"index/wishlist",
        data: { data1 : id, },
        success: function(html)
        {
            //$('#'+find).html(html);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(find);
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       if (result=="1") {
        $('#notLoggedInModal').modal('show');
         setTimeout( "jQuery('#notLoggedInModal').modal('hide');",3000 );
      }
       else if (result=="2") {
        $('#productInWishlistModal').modal('show');
        setTimeout( "jQuery('#productInWishlistModal').modal('hide');",3000 );
      }
       else if (result=="3") {
        $('#productAddedInWishlist').modal('show');
        setTimeout( "jQuery('#productAddedInWishlist').modal('hide');",3000 );
      }
 
    });

    //alert(id);

   
    }

$(function(){
$('.wish').on('click', function(e) {

//subcategories();
 var wishId = e.target.id;

 //clicked(idClicked);
 processWish(wishId);

  });
});
</script>

<script type="text/javascript">
$( document ).ready(function() {
//$('.quant-changed').val("1");
  $('#quant').mask("9?999",{placeholder:""});

});

function processCart(id){
var base_url =<?php echo $this->url->get(); ?>;

var quantity = $("#quant").val();


    $.ajax({

        type: "POST",
        url:base_url+"index/addtocart2",
        data: { data1 : id, data2: quantity},
        success: function(result)
        {
            //$("#my_count").html(html);
            if(result!="")
              $("#my_count").html(result);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            
        }
      })

    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       if (result=="") {
        $('#productExistCartModal').modal('show');
        setTimeout( "jQuery('#productExistCartModal').modal('hide');",3000 );

      }
       else {
        $('#productAddedCartModal').modal('show');
        setTimeout( "jQuery('#productAddedCartModal').modal('hide');",3000 );

      }
 
    });

    //alert(id);

   
    }

 
$(function(){
$('.cart').on('click', function(e) {
  var cartId = $(this).attr("product_id");
  processCart(cartId);
  console.log(cartId);

  });
});


function processCartB(id){
  var base_url =<?php echo $this->url->get(); ?>;

  var p_idB = id.toString().split(":")[0]; 

  var msgB = p_idB.toString().concat(p_idB.toString()); 

    $.ajax({

        type: "POST",
        url:base_url+"index/addtocart",
        data: { data1 : p_idB, },
        success: function(result)
        {
            //$("#my_count").html(html);
            if(result!="")
              $("#my_count").html(result);
            //document.getElementById('write_'+id).html(html);
            //location.reload();

            //console.log();
            console.log(p_idB);
        }
      })
    .done(function(result) {
       //alert(result);
       console.log("test successful");
       console.log(result);

       //if (result=="") {$('#productExistCartModal').modal('show');}
       //else {$('#productAddedCartModal').modal('show');}
 
    });


    //alert(id);

   
    }




$(function(){
$('.cartB').on('click', function(e) {

//subcategories();
 var cartIdB = e.target.id;
 //var cartIdB1 = cartIdB.toString().split(":")[0];
 //var cartIdB = $(this).attr('href');
 //clicked(idClicked);
 processCartB(cartIdB);


  var cart = $('.shopping-cart-button .glyphicon-shopping-cart');
        var imgtodrag = $(this).parent().parent().siblings(".img-responsive").eq(0);
        //var src = imgtodrag.attr("src");
        //console.log("fly");
        //console.log(src);
        if (imgtodrag) {
            var imgclone = imgtodrag.clone()
                .offset({
                top: imgtodrag.offset().top,
                left: imgtodrag.offset().left
            })
                .css({
                'opacity': '0.5',
                    'position': 'absolute',
                    'height': '400px',
                    'width': '250px',
                    'z-index': '100'
            })
                .appendTo($('body'))
                .animate({
                'top': cart.offset().top + 10,
                    'left': cart.offset().left + 10,
                    'width': 250,
                    'height': 400
            }, 1000, 'easeInOutExpo');
            
            setTimeout(function () {
                cart.parent().effect("shake", {
                    times: 2
                }, 200);
            }, 1500);

            imgclone.animate({
                'width': 0,
                    'height': 0
            }, function () {
                $(this).detach()
            });
        }
    


  });
});


</script>


<div class="container">
  <div class="col-md-1"> 
    <p><br></p>
    <div>
    
    <div class="als-container" id="up-list">
    <span class="als-prev" style="left: 20px;top: -32px;">
      <img src="<?php echo $this->url->get().'main/images/';?>up.png" alt="prev" title="previous" />
    </span>
    <div class="als-viewport">
    <div class="als-wrapper">

      <div class="als-item">
        <img class="img-responsive" src="<?php echo $this->url->get().$data['picture'];?>"></img>
      </div>

      <div class="als-item">
        <img class="img-responsive" src="<?php echo $this->url->get().$data['picture'];?>"></img>
      </div>

      <div class="als-item">
        <img class="img-responsive" src="<?php echo $this->url->get().$data['picture'];?>"></img>
      </div>

      <div class="als-item">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>dress1.jpg"></img>
      </div>

      <div class="als-item">
         <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>dress2.jpg"></img>
      </div>

      <div class="als-item">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>dress3.jpg"></img>
      </div>

      <div class="als-item">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>dress4.jpg"></img>
      </div>

    </div> <!--wrapper -->
    </div> <!--ais-viewport -->
    <span class="als-next" style="top: 340px; left: 20px">
      <img src="<?php echo $this->url->get().'main/images/';?>down.png" alt="next" title="next" />
    </span> <!-- "next" button -->
    </div> <!--als-container-->




  </div>

  </div> <!--col-md-1 ends -->
    
  <div class="col-md-4">
    <img class="img-responsive image" src="<?php echo $this->url->get().$data['picture'];?>"></img>
      
  </div>
    
  

  <div class="col-md-6 col-md-offset-1" id="full_details">
    <div class="row">
      <div class="col-md-12">
      <p></p>
      <?php echo $data['product_name']; ?> <br>
      By <a style="text-decoration: none;" href="<?php echo $this->url->get().'shop/index/'.$data['shop_id'];?>"> <font color="blue"> <?php echo $data['shop_name']; ?> </font> </a> &ensp;
      
     
      </div>
    </div>

    <div class="row">
      <div class="col-md-3 price-table">
        Original price<br>
        <strike><?php echo "Tk. ".$data['price']; ?><strike>
      </div>

      <div class="col-md-3 price-table">
        Special price<br>
        <?php echo "Tk. ";echo intval($data['price'])-intval($data['discount']) * intval($data['price']) * 0.01;?>
      </div>

      <div class="col-md-3 price-table">
        Discount<br>
        <?php echo $data['discount']." %"; ?>
      </div>

      <div class="col-md-3 price-table">
        Save <br>
        <?php echo "Tk. ";echo intval($data['discount']) * intval($data['price']) * 0.01;?>
      </div>

    </div>

    <div class="row">

      <div class="col-md-12 box">
      Product description<br>
     

      <p></p>

      About product<br>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
      </div>

    </div>

    <div class="row" style="padding-top: 20px">
      <div class="col-md-4">
        Quantity: &ensp; <span><input type="text" class="form-control" id="quant" value="<?php echo $data['quantity'];?>" size="5" style="width: 40%;display: inline;"></span>
      </div>

      <div class="col-md-4">
        <button type="button" class="btn btn-primary bg-button cart" product_id="<?php echo $data['product_id']; ?>">Add to Cart </button> 
      </div>

      <div class="col-md-4 wish" id="<?php echo $data['product_id']; ?>" style="cursor:pointer">
        <?php if($data['color']==0) {?>
          <i class="fa fa-star" style="color: #D21E21"></i>
        <?php } else { ?>
          <i class="fa fa-star" style="color: #000"></i>
        <?php } ?>
        Add to Wish list
      </div>

    </div>

    
  </div>

</div>


<div class="container">
  <div class="tabbable">
      <div class="mid-menu">
            
          <ul class="nav nav-tabs">
            
            <li class="active"><a href="#pane1" data-toggle="tab"><div class="item">Ask About The Product</div></a></li>
            <li><a href="#pane2" data-toggle="tab"><div class="item">Review and comments</div></a></li>
            
          </ul>
      
      </div>

      <div class="red-joint"></div>


      <div class="tab-content">
          <div id="pane1" class="tab-pane active">
            <div class="container item-area">

             
              <div class="col-md-4 col-md-offset-4" style="margin-top:17px;">

                <form action="<?php echo $this->url->get("index/ask/".$data['product_id']) ?>" method="post" >
                  <input type="text" name="email" class="form-control input-lg" placeholder="Your mail address here..">
                </br>
                  <textarea name="message" class="form-control input-lg" placeholder="Enter Your Message Here!"></textarea>
                </br>
                  <div class="btn-group btn-group-justified button-element">
                      <div class="btn-group">
                          <button type="submit" name="submit" value="publish" class="form-control input-lg btn bg-red">Submit</button>
                      </div>        
                  </div>

                </form>

              </div>





            </div>  <!--container item area ends here -->
          </div>  <!--pane1 ends here -->

           <div id="pane2" class="tab-pane">
              <div class="container item-area">

                <div class="col-md-4">
                  <div>
                   <img class="img-responsive image" src="<?php echo $this->url->get().$data['picture'];?>"></img>
                 </div>
               </br>
                 <div class="below_image">
                    <b><?php echo $data['product_name']; ?></b>
                  </br>
                  <p>Your Rating</p>

                 </div>
                </div>

                <div class="col-md-7 col-md-offset-1">
                  <div class="review_name">
                    <?php echo $data['product_name']; ?>

                  </div>

                </br>

                  <form action="#" method="post" class="ajax" id="reviewe_form">
                      <textarea name="comment" id="comment "class="form-control input-lg" placeholder="Enter Your Comment Here!"></textarea>
                    </br>
                      <div class="btn-group btn-group-justified button-element">
                        <div class="btn-group" id="rev_button">
                            <a href="#" id="review" name="review"value="publish" class="form-control input-lg btn bg-red">Post</a>
                        </div>        
                      </div>
                  </form>

                  <div class="comment_section">

                     <a href="#" id="show_comments" name="show_comments"value="publish" ><p>Show All Comments</p></a>
                  </div>
                  </br>

                 
                  <div class="all_comments">
                     <?php if(count($data['comments'])==0){
                     echo "No Comments for this Product";
                   } else 
                     foreach ($data['comments'] as $record) { ?>
                    <div class="col-md-12" id="details_comments">
                      <div class="col-md-3">
                       Posted By:<?php echo $temp[$record->user_id];?>
                      </div>
                      <div class="col-md-9">
                       <?php echo $record->created_at;?>
                      </div>

                    </br>
                      <div class="col-md-12">
                         <?php echo $record->text;?>

                      </div>
                    </div>
                   <?php } ?>
                  
                </div>

                  
                 

                 

                </div>    <!--col-md-7 col-md-offset-1 ends-->
                </div>   <!--container item-area-->
                </div>  <!--pane2 ends here -->

              </div>    <!--tab content ends here -->



            </div>    <!--tabbable ends here -->
      </div>      <!--container ends here -->


<script type="text/javascript">
  $(document).ready(function(){
    $('[name="review"]').click(function (e) {
      // alert('clicked');
    
    var comment = $('[name="comment"]').val();

    var PID = <?php echo $data['product_id']; ?>;




    
        if (comment !== "") {
        $.ajax({
           
            url: "http://localhost/biz_mela/index/comment/"+PID, 
            type: 'POST', // request method
           
            data: {
                comment: comment // here the email
            },


            success: function (data) {
               //alert(data);
               
                
            },
           
        })


      .done(function(result) {
       //alert(result);

       console.log(result);

       if (result=="1") { 
                $('#loginfirst').modal('show');
                 setTimeout( "jQuery('#loginfirst').modal('hide');",3000 );
                 $("#reviewe_form")[0].reset();
                 console.log("1");


             }
             else if (result=="2") { 
               $('#revdone').modal('show');
                setTimeout( "jQuery('#revdone').modal('hide');",3000 );
                $("#reviewe_form")[0].reset();
                console.log("2");

             }
             else if (result=="3") { 

                $('#trylater').modal('show');
                 setTimeout( "jQuery('#trylater').modal('hide');",3000 );
                 $("#reviewe_form")[0].reset();

                 console.log("3");
             }

            else if (result=="4") { 
             $('#nocomment').modal('show');
              setTimeout( "jQuery('#nocomment').modal('hide');",3000 );
              $("#reviewe_form")[0].reset();
              console.log("4");
              
            }




    });
    } else {
         
    }
  });

  })

</script>



<script type="text/javascript">
    $('.all_comments').hide();
    $(document).ready(function(){
       $('[name="show_comments"]').click(function (e) {
          $( "#shocomments> p" ).html( "Hide All Comments");
          $('.all_comments').show();

          


       });

    })

</script>



<?php if (count($data['related']) > 0) { ?>

  <div class="container">
      <div class="mid-menu">
        <div class="item">Related Products</div>
      </div>
      <div class="red-joint"></div>
    
  </div>

  <p><br></p>




  <div>
    
    <div class="als-container" id="my-als-list">
    <span class="als-prev" style="left: 150px;top: 150px">
      <img src="<?php echo $this->url->get().'main/images/';?>left.png" alt="prev" title="previous" />
    </span>
    <div class="als-viewport">
    <div class="als-wrapper">
    <?php foreach ($data['related'] as $row){?>
    
    <div class="als-item">
      <div class="hover" style="height : 445px;">
        <div class="text"><p class="top_text"><?php echo $row->product_name."<br>"."Price: ".$row->price."<br>".$row->product_description; ?></P>
          <a href="<?php echo $this->url->get().'index/productdetails/'.$row->id;?>"><font color="white">Details</font></a>
          
          <div class="bottom_text">
            <button class="cartB add-to-cart" id="<?php echo $row->id.":".$row->id.":".$row->id;?>" type="button" name="submit" value="test">
              <span class="glyphicon glyphicon-shopping-cart"></span>&ensp; Add to Cart
            </button>
            &ensp; <i class="fa fa-minus fa-rotate-90"></i> &ensp;
            <button class="wish" id="<?php echo $row->id; ?>" type="button">
              <span class="glyphicon glyphicon-heart"></span>
            </button>
          </div>
        </div>


        <img class="img-responsive" src="<?php echo $this->url->get().$row->picture;?>" style="width : 280px; height : 385px;"></img>
        <div class="price">Price: <?php echo $row->price; ?></div>
      </div>
    </div>
    
    <?php }?>
    </div> <!--wrapper -->
    </div> <!--ais-viewport -->
    <span class="als-next" style="right: 150px; top: 150px;">
      <img src="<?php echo $this->url->get().'main/images/';?>right.png" alt="next" title="next" />
    </span> <!-- "next" button -->
    </div> <!--als-container-->

    <?php } ?>



    
  </div>


  <!--Modals !-->

<div class="modal fade" id="notLoggedInModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            
            <div class="modal-body">
                <p>
                <center> You need to log in first. </center> 
                </p>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
            </div>
            
        </div>
  </div>
</div>

<div class="modal fade" id="productInWishlistModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            
            <div class="modal-body">
                <p>
                <center> This product already exists in your wish list. </center> 
                </p>
            </div>
            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'wishlist/wish/';?>">

                Checkout
              </a>
            </div>
            
        </div>
  </div>
</div>

<div class="modal fade" id="productAddedInWishlist" tabindex="-1" role="dialog" aria-labelledby="productAddedInWishlist" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            
            <div class="modal-body">
                <p>
                <center> Wish list updated successfully. </center> 
                </p>
            </div>

            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'wishlist/wish/';?>">

                Checkout
              </a>
            </div>
            
        </div>
  </div>
</div>

<div class="modal fade" id="productAddedCartModal" tabindex="-1" role="dialog" aria-labelledby="notLoggedInModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            
            <div class="modal-body">
                <p>
                <center> Product successfully added to the cart</center> 
                </p>
            </div>

            <div class="modal-footer">
             <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'index/shoppingcart/';?>">

                Checkout
              </a>
            </div>
            
       </div>
  </div>
</div>

<div class="modal fade" id="productExistCartModal" tabindex="-1" role="dialog" aria-labelledby="productInWishlistModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
           <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            
            <div class="modal-body">

                <p>
                <center> Quantity incremented for this product. </center> 
                </p>
            </div>
            <div class="modal-footer">
              <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'index/shoppingcart/';?>">

                Checkout
              </a>
            </div>
            
       </div>
  </div>
</div>


<div class="modal fade" id="loginfirst" tabindex="-1" role="dialog" aria-labelledby="loginfirstModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> You Need To logIn first. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>


<div class="modal fade" id="revdone" tabindex="-1" role="dialog" aria-labelledby="revdoneModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> Your Comment Updated Successfully. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="trylater" tabindex="-1" role="dialog" aria-labelledby="trylaterModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center>Try Again later. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>


<div class="modal fade" id="nocomment" tabindex="-1" role="dialog" aria-labelledby="nocommentModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center>Type Something </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

 



<?php echo $this->partial('shared/ad'); ?>

<script type="text/javascript">
$(function(){
$('#up-list .als-item').on('click', function(e) {

  console.log("Red");
  console.log($(this).offset().top);

  /*

  if($(this).offset().top==375.1166687011719){
    $(this).css("border", "solid 3px #B61026");
    console.log("middle element clicked");
    var getsrc = $(this).children(":first").attr("src");
    console.log(getsrc);
    $('.col-md-4 .image').attr('src',getsrc);
  }
  */

  /*

  $(this).filter(function() {
    return ($(this).offset().top > 370) && (($(this).offset().top < 380));
  }).css("border", "solid 3px #B61026");
  */

  var getsrc = $(this).children(":first").attr("src");
    console.log(getsrc);
    $('.col-md-4 .image').attr('src',getsrc);

  });
});



</script>

