<!-- right body starts here -->
	<div class="col-md-9 right-menu">
		<div class="title">My Dashboard</div>
		<div class="seperator"></div>
		<p class="details-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<div class="details">
			<div class="subtitle">Account Information</div>
			<div class="seperator"></div>
			<div class="row">
				<div class="col-md-6">
					<div class="subtitle">
						<span class="pull-left">Contact Information</span>
						<span class="pull-right"><a href="">Edit</a></span>
					</div>
					<div class="seperator"></div>
				</div>
				<div class="col-md-6">
					<div class="subtitle">
						<span class="pull-left">Newsletters</span>
						<span class="pull-right"><a href="">Edit</a></span>
					</div>
					<div class="seperator"></div>
				</div>
			</div>
			<div class="row marge-top">
				<div class="col-md-6">
					<div>Some name</div>
					<div>Designation</div>
					<div><a href="">Change Password</a></div>
				</div>
				<div class="col-md-6">
					Lorem ipsum dolor sit amet, consectetur adipisicing elit.
				</div>
			</div>
			<div class="row marge-top">
				<div class="col-md-6 text-left">
					Addressbook
				</div>
				<div class="col-md-6 text-right">
					<a href="">Manage Addresses</a>
				</div>
			</div>

			<div class="seperator marge-top"></div>
			<div class="row marge-top">
				<div class="col-md-6">
					<div class="subtitle">Some name</div>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					<div><a href="">Edit Address</a></div>
				</div>
				<div class="col-md-6">
					<div class="subtitle">Some name</div>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					<div><a href="">Edit Address</a></div>
				</div>
			</div>
		</div>
	</div>	
	<!-- right body ends here -->