<style>
h4{
color:#780000;

}

a{
color:#3300CC;

}
</style>

<div class="col-md-8 ">
<h4>Default Billing Address</h4>
<div class="seperator-dotted"></div>
<p>Account Holder:<?php echo $record['value']->account_holder_name;?></p>
<p>Account No.:<?php echo $record['value']->account_no;?></p>
<p>Branch:<?php echo $record['value']->branch_name;?></p>
<p>Bank :<?php echo $record['value']->bank_name;?></p>

<a href='/bizmela/address/edit/'>Edit</a>
</div>