<style>

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 605px;
    width: 67.5%;
}


h4>a{
	font-size: 15px;
}


p{
	font-size: 15px;
}


.col-md-6>h4{
	height:25px;
}


</style>


<div class="container">

	<div class="row-cell">


		<div class="col-md-6">
	        <h4>Default Billing Address &ensp; &ensp; &ensp; &ensp;  &ensp;  &ensp; &ensp; &ensp; &ensp; &ensp; &ensp;
	            <a href="<?php echo $this->url->get("address/editbill"); ?>">
	                Edit
	             </a>
	         </h4>   
        
	        <div class="seperator-dotted">

	        </div>


     	</div>


     	<div class="col-md-6">
	        <h4>Default Shipping Address &ensp; &ensp; &ensp; &ensp;  &ensp;  &ensp; &ensp; &ensp;  &ensp; &ensp;
	            <a href="<?php echo $this->url->get("address/editshipment"); ?>">
	                Edit
	             </a>
	         </h4>   
        
	        <div class="seperator-dotted">

	        </div>


     	</div>

     	<div class="col-md-6">
	        
	        <p><?php echo $user['value']->username;?></p>
	        <p><?php echo $data['value']->billing_address;?></p>
	        <p><?php echo $data['value']->country;?></p>
	        <p><?php echo $data['value']->zip_code;?></p>
	        <p>T:<?php echo $data['value']->contact_no;?></p>

	        

     	</div>

     	<div class="col-md-6">
	        
	        <p><?php echo $user['value']->username;?></p>
	        <p><?php echo $record['value']->shipping_address;?></p>
	        <p><?php echo $record['value']->country;?></p>
	        <p><?php echo $record['value']->zip_code;?></p>
	        <p>T:<?php echo $record['value']->contact_no;?></p>
	        
     	</div>

	</div>

</div>








