<div class="row">
	<h2>Change Password</h2>
</div>
<div class="row">
	<div class="item-area">
		<div class="form-area">
					
			<?php echo $this->getContent(); ?>

			<form action="" method="post">
				<!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
				<div class="form-group">
                                    <input class="form-control" placeholder="Current Password" name="current_pass" type="password"  autofocus>
                </div>
				<?php $message = $form->getMessagesFor('current_pass');
				foreach ($message as $m) {?>
					<div class="alert alert-danger form-element"><?php echo $m; ?></div>
				<?php }?>
				
				<div class="form-group">
                                    <input class="form-control" placeholder="New Password" name="new_pass" type="password"  autofocus>
                                </div>
				<?php $message = $form->getMessagesFor('new_pass');
				foreach ($message as $m) {?>
					<div class="alert alert-danger form-element"><?php echo $m; ?></div>
				<?php }?>

				 <div class="form-group">
                                    <input class="form-control" placeholder="Confirm Password" name="confirm_pass" type="password"  autofocus>
                                </div>
				<?php $message = $form->getMessagesFor('confirm_pass');
				foreach ($message as $m) {?>
					<div class="alert alert-danger form-element"><?php echo $m; ?></div>
				<?php }?>

				

			    <div class="btn-group btn-group-justified button-element">
				  <div class="btn-group">
				    <button type="submit" class="btn btn-lg btn-success btn-block">Change Password</button>
				  </div>
				  
				</div>

			</form>
		</div>
		

	</div>
</div>