<style>



.sample{
	text-align: center;
	padding-top: 50px;
	color:  #106e96;
	
}

a{

	text-decoration: none;
	color:#870415;

    font-size: 15px;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}
.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}

.gray{

	background-color:#ABD1F2;
	color:#000000;

}

.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height:49px;
}

.row {
    margin-left: 3px;
    margin-right: -15px;
}
.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}



</style>


<div class="show">
	<h3 class="sample"><?php  echo $data['value']; ?></h3>
</div>
</br>
