<style>
h2{
	text-align:center;
}
.intro{
    color:#870415;
}

a {
    color: #870415;
	text-decoration: none;
}
</style>

		<!-- main area -->
	<div class="row">
		<div class="col-md-6 col-md-offset-3 login-area">
				
			<div class="row form-area">
					
				<?php echo $this->getContent(); ?>

			<form action="" method="post">
					<!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
				<?php echo $form->render("invitation_code"); ?>
				<?php $message = $form->getMessagesFor('invitation_code');
				foreach ($message as $m) {?>
					<div class="alert alert-danger form-element"><?php echo $m; ?></div>
				<?php }?>
					
				</br>
				<div class="btn-group btn-group-justified button-element">
				<div class="btn-group">
					<button type="submit" class="btn btn-lg btn-custom green">Confirm Invitation Code</button>
					</div>
					</div>
					
			</form>
			</div>
		</div>
	</div>
		<!-- main area ends here -->


		