<style>
h2{
	text-align:center;
}
.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}

a{

	text-decoration: none;
	color:#870415;

    font-size: 15px;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}

.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height:49px;
}
.row {
    margin-left: 3px;
    margin-right: -15px;
}
.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}

</style>

<div class="row-cell">
			<div class="col-md-6 col-md-offset-3 login-area">
				
				<div class="row form-area">
					
					<?php echo $this->getContent(); ?>
					<h2>Refer Your Friend Via Email</h2>

				<form action="" method="post">
					<!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
					<?php echo $form->render("email"); ?>
					<?php $message = $form->getMessagesFor('email');
					foreach ($message as $m) {?>
						<div class="alert alert-danger form-element"><?php echo $m; ?></div>
					<?php }?>
					
					</br>
				    <div class="btn-group btn-group-justified button-element">
					  <div class="btn-group">
					    <button type="submit" class="btn btn-lg btn-custom green">Send Email</button>
					  </div>
					</div>
					
					<div class="btn-group btn-group-justified form-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="cancel" class="btn btn-lg btn-custom btn-danger">Cancel</button>
                    </div>		  
                </div>
				</form>
				</div>
			</div>
		</div>