<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bizmela</title>

    <!-- bootstrap integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("bootstrap/css/bootstrap.min.css"); ?>

    <!-- font-awesome integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("font-awesome/css/font-awesome.min.css"); ?>

    <!-- common css integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/main.css"); ?>
	
	  <?php echo \Phalcon\Tag::stylesheetLink("main/css/common.css"); ?>
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/start.css"); ?>
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/cart.css"); ?>

    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    


    <script type="text/javascript">
	    var baseUrl = "<?php echo $this->url->get(); ?>"
	    // alert(baseUrl);

    </script>

    <!-- jquery integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("jquery/jquery-1.11.1.min.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("jquery/jquery-migrate-1.2.1.min.js"); ?>

    <!-- bootstrap integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("bootstrap/js/bootstrap.min.js"); ?>

    <!-- common js integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/main.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.maskedinput.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.als-1.7.min.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery-ui.min.js"); ?>

    <!--CSS for range slider-->
<?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.css"); ?>
<?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.blue.css"); ?>

<?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.plastic.css"); ?>

<!--Scripts for range slider -->



<?php echo \Phalcon\Tag::javascriptInclude("main/js/jshashtable-2.1_src.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.numberformatter-1.2.3.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/tmpl.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.dependClass-0.1.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/draggable-0.1.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.slider.js"); ?>


  </head>
  <body>
    

  <!-- upper part -->
  <div class="top">
    <div class="container container-custom">    
      <div class="row">
        <div class="col-md-6 top-date top-pad bottom-pad">
          <?php $today = date("F j, Y, g:i a"); 
            echo "$today";
          ?>
        </div>
        <div class="col-md-6">
          <div class="top-menu">
            <div class="item top-pad bottom-pad">

              <?php
                            $auth = $this->session->get('auth');
                            if(!$auth){?>
                      
                            <?php }
                            else { ?>

                              <div class="intro">Welcome <?php echo $auth['name'];?></div>
                           <?php } ?>


            </div>
            <div class="item top-pad bottom-pad">
                            <?php
                            $auth = $this->session->get('auth');
                            if(!$auth){?>
                              <a href="<?php echo $this->url->get().'session/index/';?>">SignIn</a>
                            <?php }
                            else { ?>

                              <a href="<?php echo $this->url->get().'home/logout/';?>">Logout</a>
                           <?php } ?>
                            
            </div>
            <div class="item top-pad bottom-pad"><a href="/bizmela/help/index">Help & Support</a></div>
            <div class="item top-pad bottom-pad"><a>US</a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- upper part end -->
  


  <!-- search part -->
  <div class="top-search container container-custom">
    <div class="row"> 
      <form action="<?php echo $this->url->get().'search/search/';?>" method="post">
        <div class="col-md-5 col-md-offset-4">
          <div class="input-group">
            <input type="text" id="key" name="key" class="form-control" placeholder="Enter keyword ">
            <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
          </div>
        </div>
      </form>
      <div class="col-md-3 text-right shopping-cart">
        <div class="dropdown cartMenu" >
          <a class="six dropdown-toggle" data-toggle="dropdown" href="#" >
            <span class="glyphicon glyphicon-shopping-cart"></span> 
            <span class="shopping-text">
              Shopping Cart
            </span>  
            <span class="shopping-count arrow_box" id="my_count">
            <?php 
            if (!isset($_COOKIE['product'])) {
            # code...
            echo "0";
            }
            else{
            $cookie_count = unserialize($_COOKIE['product']); 
            //print_r($cookie_count);
            echo count($cookie_count); 
            }
          
            ?>  
          </span>
          <b class="caret"></b>
          </a>

          <div class="dropdown-menu six-menu" style="width : 200%; margin: 0; padding-top: 0px;">
            <div class="scrollable">
            <?php

             if (isset($_COOKIE['product'])) {
              $cookie_array = unserialize($_COOKIE['product']);

      //echo count($cookie_array); 
              if (count($cookie_array) > 0) {
               
              

              $keysHolder = array_keys($cookie_array);

              $cResult = $this->modelsManager->createBuilder()
              ->from('Biz_mela\Models\ProductMaster')
              ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
              ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
              ->inWhere('Biz_mela\Models\ProductMaster.id', $keysHolder)
              ->getQuery()
              ->execute();
             foreach ($cResult as $cart) {?>

            <div class="col-md-12" id="cart_data">
              <div class="col-md-2" id="checkout">

                <img  src="<?php echo $this->url->get().$cart->picture;?>" width="80px" style="height:80px;" ></img>

              </div>
              
               
              
              <div class="col-md-4" id="cart_name" >

                <?php echo '<a href="'.$this->url->get()."index/productdetails/".$cart->id.'">'.$cart->product_name.'</a>'?>

              </div>
              <div class="col-md-2" id="cart_price" >

               <?php echo $cart->price;?>

              </div>

              <div class="col-md-1" id="cart_quan" >

               <?php echo $cookie_array[$cart->id];?>

              </div>

              <div class="col-md-2" id="cart_total">

               <?php echo intval($cart->price)*intval($cookie_array[$cart->id]); ?>

              </div>

              <div class="col-md-1" id="cart_gla">

                <a href="" data-toggle="modal" data-target="#cartDeleteModal2<?php echo $cart->id; ?>" style="color:#000000;">
                  <span class="glyphicon glyphicon-shopping-cart" product_id="<?php echo $cart->id; ?>"> </span>
                </a>

              </div>
          </div>

          <div class="modal fade" id="cartDeleteModal2<?php echo $cart->id; ?>" tabindex="-1" role="dialog" aria-labelledby="cartDeleteModal2" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-body">
                      <p>
                      <center> Do you really want to delete this product from your cart ? </center> 
                      </p>
                  </div> 
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary cart-delete" product_id="<?php echo $cart->id; ?>" data-dismiss="modal">
                        Delete
                    </button>
                  </div> 
                </div>
              </div>
          </div>



            <?php }  ?>

          

            
            <div class="col-md-4 col-md-offset-4">
              <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'index/shoppingcart/';?>">

                Checkout
              </a>


          </div>  <?php } ?>
        </div><?php } ?>
          </div>

        


        </div>
      </div>
    </div>
  </div>
  <!-- search part end -->
  

  <!-- logo part -->
  <div class="logo container container-custom">
    <div class="row">
      <div class="col-md-3">
        <a href=<?php echo $this->url->get("index/"); ?>>
          <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>icon.png"></img>
        </a>
      </div>
    </div>
  </div>
  <!-- logo part ends -->

  <script type="text/javascript">
  
    $(document).ready(function() {

     $('.five').hover(
         function () {
           //$(this).addClass("open");
            $('.five-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.five-menu').css({"display":"none"});
         }
     );

     $('.cartMenu').hover(
         function () {
           //$(this).addClass("open");
            $('.six-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.six-menu').css({"display":"none"});
         }
     );

     $('.one').hover(
         function () {
           //$(this).addClass("open");
            $('.one-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.one-menu').css({"display":"none"});
         }
     );

     $('.two').hover(
         function () {
           //$(this).addClass("open");
            $('.two-menu').css({"display":"block"});
         },
         function () {
           //$(this).addClass("open");
            $('.two-menu').css({"display":"none"});
         }
         
     );
     $('.three').hover(
         function () {
           //$(this).addClass("open");
            $('.three-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.three-menu').css({"display":"none"});
         }
     );

     $('.four').hover(
         function () {
           //$(this).addClass("open");
            $('.four-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.four-menu').css({"display":"none"});
         }
     );



   });




   
  </script>

  <style type="text/css">
    .top-menu .item:first-child{
      border: 0px;
    }
  </style>
 

  <!-- main menu part -->
  <div class="main-menu container container-custom">
    <div class="btn-group one">
        <span data-toggle="dropdown" class="dropdown-toggle">Category 1</span>
            <ul class="one-menu dropdown-menu" style="width : 250%; margin: 0; padding-top: 0px;">
              <div class="col-md-12">
              
               
              <?php 
              use Biz_mela\Models\ProductCategory as ProductCategory;
              use Biz_mela\Models\ProductMaster as ProductMaster;
              use Biz_mela\Models\ProductImage as ProductImage;
              
              $categories = ProductCategory::findFirst(1);
              $cat_id=$categories->id;
              //$product_data = ProductMaster::find("cat_id="."'".$cat_id."'");

               //echo "<table><tr>";
               //foreach ($product_data as $entry){

                $relatedProducts = $this->modelsManager->createBuilder()
                  ->from('Biz_mela\Models\ProductMaster')
                  ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
                  ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
                  ->where('Biz_mela\Models\ProductMaster.cat_id = :name:', array('name' => $cat_id))
                  ->orderBy('Biz_mela\Models\ProductMaster.id desc')
                 
                  ->limit(4)
                  ->getQuery()
                  ->execute();

                foreach ($relatedProducts as $product) {?>
                  <div class="col-md-3 hover" id="prod_pic">
                    <div class="item">
                      <div class="text">
                        <p class="top_text" style="color:#fff;"><?php echo $product->product_name?></p>
                        <p style="color:#fff;">Price:<?php echo $product->price?></p>
                          <a href="<?php echo $this->url->get().'index/productdetails/'.$product->id;?>"><font color="white">
                            Details
                          </font>
                          </a>
                    
          
                      </div>
                    </div>
              
                <img  src="<?php echo $this->url->get().$product->picture;?>" width="100px" style="height:200px; padding:15px; "></img>
                 <div class="price">Price:<?php echo $product->price; ?> </div>
                  </div>

             <?php } ?>

            </div>

            <div class="col-md-5 col-md-offset-7" id="all_cat">

              <?php
              $categories = ProductCategory::findFirst(1);
              $cat_id=$categories->id;
              ?>
                <a href="<?php echo $this->url->get().'category/index/'.$cat_id;?>">
                  <font color="#cd2027" size="2px" float="right">
                           Related Products
                  </font>
                </a>


            </div>
            
          </ul>
    </div>

    <div class="btn-group two">
        <span data-toggle="dropdown" class="dropdown-toggle">Category 2</span>
            <ul class="two-menu dropdown-menu" style="width : 250%; margin: 0; padding-top: 0px;">
              <div class="col-md-12">
              
               
              <?php 
              
              
              $categories = ProductCategory::findFirst(2);
              $cat_id=$categories->id;
              //$product_data = ProductMaster::find("cat_id="."'".$cat_id."'");

               //echo "<table><tr>";
               //foreach ($product_data as $entry){

                $relatedProducts = $this->modelsManager->createBuilder()
                  ->from('Biz_mela\Models\ProductMaster')
                  ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
                  ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
                  ->where('Biz_mela\Models\ProductMaster.cat_id = :name:', array('name' => $cat_id))
                 
                  ->limit(4)
                  ->getQuery()
                  ->execute();

                foreach ($relatedProducts as $product) {?>
                  <div class="col-md-3 hover" id="prod_pic">
                    <div class="item">
                      <div class="text">
                        <p class="top_text" style="color:#fff;"><?php echo $product->product_name?></p>
                        <p style="color:#fff;">Price:<?php echo $product->price?></p>
                          <a href="<?php echo $this->url->get().'index/productdetails/'.$product->id;?>"><font color="white">
                            Details
                          </font>
                          </a>
                    
          
                      </div>
                    </div>
              
                <img  src="<?php echo $this->url->get().$product->picture;?>" width="100px" style="height:200px; padding:15px;"></img>
                <div class="price" style="color:#000">Price:<?php echo $product->price; ?> </div>
                  </div>

             <?php } ?>

            </div>
            <div class="col-md-5 col-md-offset-7" id="all_cat">

              <?php
              $categories = ProductCategory::findFirst(2);
              $cat_id=$categories->id;
              ?>
                <a href="<?php echo $this->url->get().'category/index/'.$cat_id;?>">
                  <font color="#cd2027" size="2px" float="right">
                           Related Products
                  </font>
                </a>


            </div>
          </ul>
    </div>

    <div class="btn-group three">
        <span data-toggle="dropdown" class="dropdown-toggle">Category 3</span>
            <ul class="three-menu dropdown-menu" style="width : 250%; margin: 0; padding-top: 0px;">
              <div class="col-md-12">
              
               
              <?php 
              
              
              $categories = ProductCategory::findFirst(3);
              $cat_id=$categories->id;
              //$product_data = ProductMaster::find("cat_id="."'".$cat_id."'");

               //echo "<table><tr>";
               //foreach ($product_data as $entry){

                $relatedProducts = $this->modelsManager->createBuilder()
                  ->from('Biz_mela\Models\ProductMaster')
                  ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
                  ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
                  ->where('Biz_mela\Models\ProductMaster.cat_id = :name:', array('name' => $cat_id))
                 
                  ->limit(4)
                  ->getQuery()
                  ->execute();

                foreach ($relatedProducts as $product) {?>
                  <div class="col-md-3 hover" id="prod_pic">
                    <div class="item">
                      <div class="text">
                        <p class="top_text" style="color:#fff;"><?php echo $product->product_name?></p>
                        <p style="color:#fff;">Price:<?php echo $product->price?></p>
                          <a href="<?php echo $this->url->get().'index/productdetails/'.$product->id;?>"><font color="white">
                            Details
                          </font>
                          </a>
                    
          
                      </div>
                    </div>
              
                <img  src="<?php echo $this->url->get().$product->picture;?>" width="100px" style="height:200px; padding:15px;"></img>
                <div class="price" style="color:#000">Price:<?php echo $product->price; ?> </div>
                  </div>

             <?php } ?>

            </div>

            <div class="col-md-5 col-md-offset-7" id="all_cat">

              <?php
              $categories = ProductCategory::findFirst(3);
              $cat_id=$categories->id;
              ?>
                <a href="<?php echo $this->url->get().'category/index/'.$cat_id;?>">
                  <font color="#cd2027" size="2px" float="right">
                            Related Products
                  </font>
                </a>


            </div>
            
          </ul>
    </div>
     <div class="btn-group four">
        <span data-toggle="dropdown" class="dropdown-toggle">Category 4</span>
            <ul class="four-menu dropdown-menu" style="width : 250%; margin: 0; padding-top: 0px;">
              <div class="col-md-12">
              
               
              <?php 
              
              
              $categories = ProductCategory::findFirst(4);
              $cat_id=$categories->id;
              //$product_data = ProductMaster::find("cat_id="."'".$cat_id."'");

               //echo "<table><tr>";
               //foreach ($product_data as $entry){

                $relatedProducts = $this->modelsManager->createBuilder()
                  ->from('Biz_mela\Models\ProductMaster')
                  ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
                  ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
                  ->where('Biz_mela\Models\ProductMaster.cat_id = :name:', array('name' => $cat_id))
                 
                  ->limit(4)
                  ->getQuery()
                  ->execute();

                foreach ($relatedProducts as $product) {?>
                  <div class="col-md-3 hover" id="prod_pic">
                    <div class="item">
                      <div class="text">
                        <p class="top_text" style="color:#fff;"><?php echo $product->product_name?></p>
                        <p style="color:#fff;">Price:<?php echo $product->price?></p>
                          <a href="<?php echo $this->url->get().'index/productdetails/'.$product->id;?>"><font color="white">
                            Details
                          </font>
                          </a>
                    
          
                      </div>
                    </div>
              
                <img  src="<?php echo $this->url->get().$product->picture;?>" width="100px" style="height:200px; padding:15px;"></img>
                <div class="price" style="color:#000">Price:<?php echo $product->price; ?> </div>
                  </div>

             <?php } ?>

            </div>

            <div class="col-md-5 col-md-offset-7" id="all_cat">

              <?php
              $categories = ProductCategory::findFirst(4);
              $cat_id=$categories->id;
              ?>
                <a href="<?php echo $this->url->get().'category/index/'.$cat_id;?>">
                  <font color="#cd2027" size="2px" float="right">
                            Related Products
                  </font>
                </a>


            </div>
            
          </ul>
    </div>
    <div class="btn-group five">
            <span data-toggle="dropdown" class="dropdown-toggle">All</span>
            <ul class="dropdown-menu five-menu" style="width : 200%; margin: 0; padding-top: 5px;">
              
              <table class="table"><tr>
              <?php 
              
              $categories = ProductCategory::find();

               $count = 0;

               //echo "<table><tr>";
               foreach ($categories as $entry){
                $product_data = ProductMaster::find("cat_id="."'".$entry->id."'");
                echo '<td><a href="'.$this->url->get()."category/index/".$entry->id.'">'.$entry->cat_name.'&ensp;<span class="badge">'.count($product_data).'</span>'.'</a></td>';
                $count++;
                if ($count%3 == 0){
                    if($count >= count($categories))
                      echo "</tr>";

                    else
                      echo "</tr><tr>";
                }
               }

               echo "</tr></table>";

              ?>
           
            </ul>
    </div>
    
    
    
  </div>
  <!-- main menu part ends here -->

  <div class="seperator marg-top"></div>


  

  <?php echo $this->getContent() ?>


  
  <!-- subscription area -->
  <div class="subscribe">
    <div class="container">
      <form action="<?php echo $this->url->get("newsletter/subscription/") ?>" method="post">
      <div class="col-md-5">
        <div class="subs-text">Subscribe to our newsletter</div>
      </div>
      
      <div class="col-md-5">
        <input type="text" id="email" name="email" class="form-control input-lg" placeholder="Your mail address here..">        
      </div>
      <div class="col-md-2">
          
          <div class="btn-group btn-group-justified button-element">
                      <div class="btn-group">
                          <button type="submit" name="submit" value="publish" class="form-control input-lg btn bg-red">Submit</button>
                      </div>        
                  </div>
              
      </div>
    </form>
      
    </div>
  </div>
  <!-- subscription area ends -->
  

  <!-- payment section -->
  <div class="payment">
    <div class="container">
      <div class="col-md-12">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card1.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card2.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card3.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card4.jpg"></img>
      </div>
    </div>
  </div>
  <!-- payment section ends here -->


  <!-- footer area -->
  <div class="footer">
    <div class="container">
      <div class="col-md-3 item">
        <h3>Links</h3>
        <div><a href="<?php echo $this->url->get("sitemap/index/"); ?>" class="about">Site Map</a></div>
        <div><a href="<?php echo $this->url->get("footer/index/"); ?>" class="about">About Us</a></div>
        <div>Advanced Search</div>
        <div><a href="<?php echo $this->url->get("policy/index/"); ?>" class="about">Order and Return</a></div>
        <div><a href="<?php echo $this->url->get("contact/contact/"); ?>" class="about">Contact Us</a></div>
        
      </div>
      <div class="col-md-2 item">
        <h3>Information</h3>
        <div>New Products</div>
        <div>Top Seller</div>
        <div>Specials</div>
        <div>Manufacturers</div>
        <div>Our Store</div>
      </div>
      <div class="col-md-3 item">
        <h3>Latest Tweets : <span><img src="<?php echo $this->url->get().'main/images/';?>twitter_icon.png" class="img-responsive"></span></h3>
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua</div>
       
        
      </div>
      <div class="col-md-4 item">
        <h3>Facebook: <span><img src="<?php echo $this->url->get().'main/images/';?>facebook_icon.png" class="img-responsive"></span></h3>
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua</div>
       
        
      </div>
    </div>


    <div class="footer-seperator"></div>

    <div class="bottom-footer container">
      <div class="col-md-4 col-md-offset-1">
        <div class="item"><i class="fa fa-facebook"></i></div>
        <div class="item"><i class="fa fa-twitter"></i></div>
        <div class="item"><i class="fa fa-stack-overflow"></i></div>
        <div class="item"><i class="fa fa-css3"></i></div>
        <div class="item"><i class="fa fa-apple"></i></div>
        <div class="item"><i class="fa fa-android"></i></div>
      </div>
      <div class="col-md-7 text-center copyright">
        ©2014 Biz-mela All rights reserved.Designed and Developed By Atomix System Limited
      </div>
    </div>


  </div>
  <!-- footer area ends here -->




  </body>
</html>
