<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bizmela</title>

    <!-- bootstrap integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("bootstrap/css/bootstrap.min.css"); ?>

    <!-- font-awesome integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("font-awesome/css/font-awesome.min.css"); ?>

    <!-- common css integration -->
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/main.css"); ?>
	
	  <?php echo \Phalcon\Tag::stylesheetLink("main/css/common.css"); ?>
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/start.css"); ?>
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/cart.css"); ?>
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/modal.css"); ?>
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/topmenu.css"); ?>

    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    


    <script type="text/javascript">
	    var baseUrl = "<?php echo $this->url->get(); ?>"
	    // alert(baseUrl);

    </script>

    <!-- jquery integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("jquery/jquery-1.11.1.min.js"); ?>
    
    <?php echo \Phalcon\Tag::javascriptInclude("jquery/jquery-migrate-1.2.1.min.js"); ?>

    <!-- bootstrap integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("bootstrap/js/bootstrap.min.js"); ?>

    <!-- common js integration -->
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/main.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.maskedinput.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.als-1.7.min.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery-ui.min.js"); ?>
    <?php echo \Phalcon\Tag::javascriptInclude("main/js/imagezoom.js"); ?>

    <!--CSS for range slider-->
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.css"); ?>
    <?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.blue.css"); ?>

    <?php echo \Phalcon\Tag::stylesheetLink("main/css/jslider.plastic.css"); ?>

<!--Scripts for range slider -->



<?php echo \Phalcon\Tag::javascriptInclude("main/js/jshashtable-2.1_src.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.numberformatter-1.2.3.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/tmpl.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.dependClass-0.1.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/draggable-0.1.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("main/js/jquery.slider.js"); ?>


  </head>
  <body>
<style>

#logo{
  width:25%;
}

.sticky {
    position:fixed;
    top:-5px;
    
    z-index: 100;
    margin-left: 250px;
     margin-right: 20px;
    background-color: #fff;
    box-shadow: 0 3px 6px gray;
}



.shopping-cart-button{
    background-color: #cd2027;
    color: black;
    opacity: 1;
    padding: 10px;
    position: fixed;
    right: 0;
    
    z-index: 100;
    /*margin-right: -350px;*/
    margin-top: 194px;
    font-size: 12px;
    border-radius-left:16px;

}


.shopping-cart-button:hover{
  cursor: pointer;
  text-decoration: none;
}

.shopping-cart-details{
  width:450px;
}

.shopping-cart-details{
  background-color: #fff;
    color: #000;
    padding: 0px;
    position: fixed;
    z-index: 100;
   /*margin-right: -350px;*/
    margin-top: 194px;
    font-size: 12px;
    overflow-y: scroll;

    max-height: 490px;
    width:345px;

}

.fa-user{
  color:#106e96;
}

.hover:hover{
  opacity:0.50;
}

.price {
    background-color: #bcbcbc;
    
    color: #717171;
    display: table;
    font-size: 12px;
    height: 20px;
    margin: 1px auto auto;
    padding: 5px;
    width: 100px;
}

</style>

<script>

$(function(){
$('.glyphicon-remove-circle').on('click', function() {
    var base_url =<?php echo $this->url->get(); ?>;

      //$(this).parent('div').parent('div').slideUp('slow');
      var pId = $(this).attr('product_id');
      console.log(pId);

      

      $.ajax({

        type: "POST",
        url: base_url+"index/updateCookie",
        data: { data1 : pId, },
        success: function(the_result)
        {
            //$("#sub_cat_id").html(html);
             the_result = the_result.split(",");
            count = the_result[0];
            console.log("count is"+count);
            stotal = the_result[1];
            console.log("total is"+stotal);
            $("#my_count").html(count);
            //$("#my_count").html(html);
        }
      });

      //$(this).parent('div').parent('div').slideUp('slow');
      var pace_area_id = pId.toString().concat("pace");
      $('#'+pace_area_id).parent('div').parent('div').slideUp('slow');;
  

  });
});



</script>

  <!-- upper part -->
  <div class="top" >
    
    <div class="container container-custom">
      <div class="shopping-cart-button" style="right:0px;opacity:1;">

              <span class="glyphicon glyphicon-shopping-cart"></span> 
              <span class="shopping-count arrow_box" id="my_count">
                  <?php 
                  if (!isset($_COOKIE['product'])) {
                  # code...
                  echo "0";
                  }
                  else{
                  $cookie_count = unserialize($_COOKIE['product']); 
                  //print_r($cookie_count);
                  echo count($cookie_count); 
                  }
                
                  ?>  
              </span>


      </div>        <!--Shopping-cart-button Ends Here -->


      <div class="shopping-cart-details"  style="right:-350px;opacity:1;" >
          <div class="scrollable" id="scroll_cart">
            <?php

             if (isset($_COOKIE['product'])) {
              $cookie_array = unserialize($_COOKIE['product']);

      //echo count($cookie_array); 
              if (count($cookie_array) > 0) {
               
              

              $keysHolder = array_keys($cookie_array);

              $cResult = $this->modelsManager->createBuilder()
              ->from('Biz_mela\Models\ProductMaster')
              ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
              ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
              ->inWhere('Biz_mela\Models\ProductMaster.id', $keysHolder)
              ->getQuery()
              ->execute();
              
             foreach ($cResult as $cart) {?>

              <div class="col-md-12" id="cart_data">


                <div class="col-md-4" id="checkout" style="width:30%;">

                  <img  src="<?php echo $this->url->get().$cart->picture;?>" width="100%" style="height:120px; width:75px;" ></img>

                </div>
                
                 
                
                <div class="col-md-6" id="cart_name" style="width:40%;">
                  <div>
                    <?php echo '<a href="'.$this->url->get()."index/productdetails/".$cart->id.'" class="cart_prod">'.$cart->product_name.'</a>'?>
                  </div>
                  <div>
                    <?php echo $cart->product_description;?>
                  </div>
                  <div>
                    <p>Quantity:<?php echo $cookie_array[$cart->id];?></p>
                    
                    <a href="#" data-toggle="modal" style="color:#000000;">
                      <span class="glyphicon glyphicon-remove-circle" product_id="<?php echo $cart->id; ?>"> </span>
                    </a>
                  </div>
                  


                </div>    <!-- col-md-6 end here Here -->

                <div class="col-md-2" id="cart_price"style="width:30%;">

                 <p>Price:<?php echo $cart->price;?></p>
                 <p>Total:<?php echo intval($cart->price)*intval($cookie_array[$cart->id]); ?></p>
                 <span class="pace" id="<?php echo $cart->id."pace"; ?>"></span>

                </div>

                
            </div>        <!-- col-md-12  Ends Here -->

          


            <?php }  ?>

          

            
            <div class="col-md-4 col-md-offset-4">
              <a class="btn btn-md btn-primary" href="<?php echo $this->url->get().'index/shoppingcart/';?>">

                Checkout
              </a>


          </div>  <?php } else if (count($cookie_array) == 0) {echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There is No item in Your Bag";} ?>
        </div><?php } ?>
                <!-- Scroll Ends Here -->
    </div> 
      <div class="row">
        <div class="col-md-8 top-date top-pad bottom-pad">
          <?php $today = date("F j, Y, g:i a"); 
            echo "$today";
          ?>
        </div>
        <div class="col-md-4">
          <div class="top-menu">
            
            <div class="item top-pad bottom-pad">
                            <?php
                            $auth = $this->session->get('auth');
                            if(!$auth){?>
                              <a href="<?php echo $this->url->get().'session/index/';?>">SignIn</a>
                            <?php }
                            else { ?>

                              
                           <?php } ?>
                            
            </div>
            <div class="item top-pad bottom-pad">
              

              <?php
                            $auth = $this->session->get('auth');
                            if(!$auth){?>
                              <a href="<?php echo $this->url->get().'help/index/';?>">Help & Support</a>
                            <?php }
                            else { ?>

                              <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle text-right" data-toggle="dropdown" style="border:0px;">

                                  <div>
                                    <?php
                                      $auth = $this->session->get('auth');
                                      ?>
                                     <?php echo $auth['name'];?>


                                     <i class="fa fa-user"> <span class="caret"></span></i></div>
                                  
                                   
                                   
                                </button>
                                <ul class="dropdown-menu" role="menu">


                                  <li><a href="<?php echo $this->url->get("accdashboard/dashinfo/"); ?>">Profile</a></li>

                                  
                                  <li><a href="<?php echo $this->url->get("home/logout/"); ?>">Logout</a></li>
                                  <li><a href="<?php echo $this->url->get("help/index/"); ?>">Help & Support</a></li>
                                </ul>
                              </div>
                            

                              
                           <?php } ?>



            </div>    <!-- Top Part Ends Here -->

            
    
          </div> <!-- Top Menu Ends Here -->
        </div>   <!-- col-md-4 Ends Here -->
      </div>     <!-- div class 'row ' end here -->
    </div>       <!-- custome container  Ends Here -->
  </div>          <!-- Top div ends here-->
  <!-- upper part end -->
  


  <!-- search part -->
  <div class="top-search container container-custom">
    <div class="row"> 
      <div class="col-md-3" id="logo">
        <a href=<?php echo $this->url->get("index/"); ?>>
          <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>icon.png" ></img>
        </a>
      </div>
      <form action="<?php echo $this->url->get().'search/search/';?>" method="post">
        <div class="col-md-6 ">
          <div class="input-group">
            <input type="text" id="key" name="key" class="form-control" placeholder="Enter keyword ">
            <span class="input-group-addon" ><span class="glyphicon glyphicon-search" ></span></span>
          </div>
        </div>
      </form>
      
    </div>
  </div>
  <!-- search part end -->
  

  <!-- logo part -->
  
  <!-- logo part ends -->

  <script type="text/javascript">
  
    $(document).ready(function() {

     $('.five').hover(
         function () {
           //$(this).addClass("open");
            $('.five-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.five-menu').css({"display":"none"});
         }
     );

     $('.cartMenu').hover(
         function () {
           //$(this).addClass("open");
            $('.six-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.six-menu').css({"display":"none"});
         }
     );

     

     $('.one').hover(
         function () {
           //$(this).addClass("open");
            $('.one-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.one-menu').css({"display":"none"});
         }
     );

     $('.two').hover(
         function () {
           //$(this).addClass("open");
            $('.two-menu').css({"display":"block"});
         },
         function () {
           //$(this).addClass("open");
            $('.two-menu').css({"display":"none"});
         }
         
     );
     $('.three').hover(
         function () {
           //$(this).addClass("open");
            $('.three-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.three-menu').css({"display":"none"});
         }
     );

     $('.four').hover(
         function () {
           //$(this).addClass("open");
            $('.four-menu').css({"display":"block"});
         }, 
         function () {
           //$(this).removeClass("open");
            $('.four-menu').css({"display":"none"});
         }
     );






   });


$(document).ready(function () {

    var menu = $('.main-menu');
    var origOffsetY = menu.offset().top;
    

    function scroll() {
        if ($(window).scrollTop() >= origOffsetY) {
            $('.main-menu').addClass('sticky');   
            
        } else {
            $('.main-menu').removeClass('sticky');
           
        }

    }

    document.onscroll = scroll;

});




$(document).ready(function(){

  $('.shopping-cart-button').click(function(){
  
            
           //$(this).addClass("open");
              //console.log($(this).css('right'));
             if($(this).css('right')=='345px'){
                
                $(this).animate({'right':'0px'});
                $(".shopping-cart-details").animate({
                  'right':'-345px',
                });
             }else{

                   $(".shopping-cart-button").animate({
                  'right':'345px',
                });

                $(".shopping-cart-details").animate({
                  'right':'0px',
                });

             }

           
  }


  );
});
      
             
            // $(".shopping-cart-details").animate({
            //   'right': .shopping-cart-details.offset().right + 450,
            // });
            
             

        




   
  </script>

  <style type="text/css">
    .top-menu .item:first-child{
      border: 0px;
    }
  </style>
 

  <!-- main menu part -->
  <div class="main-menu container container-custom">
    <div class="btn-group one">
        <span data-toggle="dropdown" class="dropdown-toggle">Category 1</span>
            <ul class="one-menu dropdown-menu" style="width : 285%; margin: 0; padding-top: 0px;">
              <div class="col-md-12" style="width:575px;">
              
               
              <?php 
              use Biz_mela\Models\ProductCategory as ProductCategory;
              use Biz_mela\Models\ProductMaster as ProductMaster;
              use Biz_mela\Models\ProductImage as ProductImage;
              
              $categories = ProductCategory::findFirst(1);
              $cat_id=$categories->id;
              //$product_data = ProductMaster::find("cat_id="."'".$cat_id."'");

               //echo "<table><tr>";
               //foreach ($product_data as $entry){

                $relatedProducts = $this->modelsManager->createBuilder()
                  ->from('Biz_mela\Models\ProductMaster')
                  ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
                  ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
                  ->where('Biz_mela\Models\ProductMaster.cat_id = :name:', array('name' => $cat_id))
                  ->orderBy('Biz_mela\Models\ProductMaster.id desc')
                 
                  ->limit(4)
                  ->getQuery()
                  ->execute();

                foreach ($relatedProducts as $product) {?>
                  <div class="col-md-3 hover" id="prod_pic">
                    <div class="item">
                      <div class="text2">
                        <p class="top_text" style="color:#fff;"><?php echo $product->product_name?></p>
                        <p style="color:#fff;">Price:<?php echo $product->price?></p>
                          <a href="<?php echo $this->url->get().'index/productdetails/'.$product->id;?>"><font color="white">
                            Details
                          </font>
                          </a>
                    
          
                      </div>
                    </div>
              
                    <img  src="<?php echo $this->url->get().$product->picture;?>" width="110px" style="height:215px; padding:15px; "></img>
                    <div class="price" id="ind_price" >Price:<?php echo $product->price; ?> </div>
                  </div>

             <?php } ?>

            </div>

            <div class="col-md-5 col-md-offset-7" id="all_cat">

              <?php
              $categories = ProductCategory::findFirst(1);
              $cat_id=$categories->id;
              ?>
                <a href="<?php echo $this->url->get().'category/index/'.$cat_id;?>">
                  <font color="#cd2027" size="2px" float="right">
                           Related Products
                  </font>
                </a>


            </div>
            
          </ul>
    </div>

    <div class="btn-group two">
        <span data-toggle="dropdown" class="dropdown-toggle">Category 2</span>
            <ul class="two-menu dropdown-menu" style="width : 270%; margin: 0; padding-top: 0px;">
              <div class="col-md-12" style="width:575px;">
              
               
              <?php 
              
              
              $categories = ProductCategory::findFirst(2);
              $cat_id=$categories->id;
              //$product_data = ProductMaster::find("cat_id="."'".$cat_id."'");

               //echo "<table><tr>";
               //foreach ($product_data as $entry){

                $relatedProducts = $this->modelsManager->createBuilder()
                  ->from('Biz_mela\Models\ProductMaster')
                  ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
                  ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
                  ->where('Biz_mela\Models\ProductMaster.cat_id = :name:', array('name' => $cat_id))
                 
                  ->limit(4)
                  ->getQuery()
                  ->execute();

                foreach ($relatedProducts as $product) {?>
                  <div class="col-md-3 hover" id="prod_pic">
                    <div class="item">
                      <div class="text2">
                        <p class="top_text" style="color:#fff;"><?php echo $product->product_name?></p>
                        <p style="color:#fff;">Price:<?php echo $product->price?></p>
                          <a href="<?php echo $this->url->get().'index/productdetails/'.$product->id;?>"><font color="white">
                            Details
                          </font>
                          </a>
                    
          
                      </div>
                    </div>
              
                <img  src="<?php echo $this->url->get().$product->picture;?>" width="110px" style="height:215px; padding:15px;"></img>
                <div class="price" style="color:#000">Price:<?php echo $product->price; ?> </div>
                  </div>

             <?php } ?>

            </div>
            <div class="col-md-5 col-md-offset-7" id="all_cat_else">

              <?php
              $categories = ProductCategory::findFirst(2);
              $cat_id=$categories->id;
              ?>
                <a href="<?php echo $this->url->get().'category/index/'.$cat_id;?>">
                  <font color="#cd2027" size="2px" float="right">
                           Related Products
                  </font>
                </a>


            </div>
          </ul>
    </div>

    <div class="btn-group three">
        <span data-toggle="dropdown" class="dropdown-toggle">Category 3</span>
            <ul class="three-menu dropdown-menu" style="width : 270%; margin: 0; padding-top: 0px;">
              <div class="col-md-12" style="width:575px;">
              
               
              <?php 
              
              
              $categories = ProductCategory::findFirst(3);
              $cat_id=$categories->id;
              //$product_data = ProductMaster::find("cat_id="."'".$cat_id."'");

               //echo "<table><tr>";
               //foreach ($product_data as $entry){

                $relatedProducts = $this->modelsManager->createBuilder()
                  ->from('Biz_mela\Models\ProductMaster')
                  ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
                  ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
                  ->where('Biz_mela\Models\ProductMaster.cat_id = :name:', array('name' => $cat_id))
                 
                  ->limit(4)
                  ->getQuery()
                  ->execute();

                foreach ($relatedProducts as $product) {?>
                  <div class="col-md-3 hover" id="prod_pic">
                    <div class="item">
                      <div class="text2">
                        <p class="top_text" style="color:#fff;"><?php echo $product->product_name?></p>
                        <p style="color:#fff;">Price:<?php echo $product->price?></p>
                          <a href="<?php echo $this->url->get().'index/productdetails/'.$product->id;?>"><font color="white">
                            Details
                          </font>
                          </a>
                    
          
                      </div>
                    </div>
              
                <img  src="<?php echo $this->url->get().$product->picture;?>" width="110px" style="height:215px; padding:15px;"></img>
                <div class="price" style="color:#000">Price:<?php echo $product->price; ?> </div>
                  </div>

             <?php } ?>

            </div>

            <div class="col-md-5 col-md-offset-7" id="all_cat_else">

              <?php
              $categories = ProductCategory::findFirst(3);
              $cat_id=$categories->id;
              ?>
                <a href="<?php echo $this->url->get().'category/index/'.$cat_id;?>">
                  <font color="#cd2027" size="2px" float="right">
                            Related Products
                  </font>
                </a>


            </div>
            
          </ul>
    </div>
     <div class="btn-group four">
        <span data-toggle="dropdown" class="dropdown-toggle">Category 4</span>
            <ul class="four-menu dropdown-menu" style="width : 270%; margin: 0; padding-top: 0px;">
              <div class="col-md-12" style="width:575px;">
              
               
              <?php 
              
              
              $categories = ProductCategory::findFirst(4);
              $cat_id=$categories->id;
              //$product_data = ProductMaster::find("cat_id="."'".$cat_id."'");

               //echo "<table><tr>";
               //foreach ($product_data as $entry){

                $relatedProducts = $this->modelsManager->createBuilder()
                  ->from('Biz_mela\Models\ProductMaster')
                  ->columns('Biz_mela\Models\ProductMaster.id, Biz_mela\Models\ProductMaster.price, Biz_mela\Models\ProductMaster.product_name, Biz_mela\Models\ProductMaster.product_description, p.picture')
                  ->leftJoin('Biz_mela\Models\ProductImage', 'p.product_id = Biz_mela\Models\ProductMaster.id', 'p')
                  ->where('Biz_mela\Models\ProductMaster.cat_id = :name:', array('name' => $cat_id))
                 
                  ->limit(4)
                  ->getQuery()
                  ->execute();

                foreach ($relatedProducts as $product) {?>
                  <div class="col-md-3 hover" id="prod_pic">
                    <div class="item">
                      <div class="text2">
                        <p class="top_text" style="color:#fff;"><?php echo $product->product_name?></p>
                        <p style="color:#fff;">Price:<?php echo $product->price?></p>
                          <a href="<?php echo $this->url->get().'index/productdetails/'.$product->id;?>"><font color="white">
                            Details
                          </font>
                          </a>
                    
          
                      </div>
                    </div>
              
                <img  src="<?php echo $this->url->get().$product->picture;?>" width="110px" style="height:215px; padding:15px; "></img>
                <div class="price" style="color:#000">Price:<?php echo $product->price; ?> </div>
                  </div>

             <?php } ?>

            </div>

            <div class="col-md-5 col-md-offset-7" id="all_cat_else">

              <?php
              $categories = ProductCategory::findFirst(4);
              $cat_id=$categories->id;
              ?>
                <a href="<?php echo $this->url->get().'category/index/'.$cat_id;?>">
                  <font color="#cd2027" size="2px" float="right">
                            Related Products
                  </font>
                </a>


            </div>
            
          </ul>
    </div>
    <div class="btn-group five">
            <span data-toggle="dropdown" class="dropdown-toggle">All</span>
            <ul class="dropdown-menu five-menu" style="width : 200%; margin: 0; padding-top: 5px;">
              
              <table class="table"><tr>
              <?php 
              
              $categories = ProductCategory::find();

               $count = 0;

               //echo "<table><tr>";
               foreach ($categories as $entry){
                $product_data = ProductMaster::find("cat_id="."'".$entry->id."'");
                echo '<td><a class="fifth_menu" href="'.$this->url->get()."category/index/".$entry->id.'">'.$entry->cat_name.'&ensp;<span class="badge">'.count($product_data).'</span>'.'</a></td>';
                $count++;
                if ($count%3 == 0){
                    if($count >= count($categories))
                      echo "</tr>";

                    else
                      echo "</tr><tr>";
                }
               }

               echo "</tr></table>";

              ?>
           
            </ul>
    </div>
    
    
    
  </div>
  <!-- main menu part ends here -->

  <div class="seperator marg-top"></div>


  

  <?php echo $this->getContent() ?>


  
  <!-- subscription area -->
  <div class="subscribe">
    <div class="container">
      <form action="<?php echo $this->url->get("newsletter/subscription/") ?>" method="post" class="ajax" id="subs_form">
        <div class="col-md-5">
          <div class="subs-text">Subscribe to our newsletter</div>
        </div>
      
        <div class="col-md-5">
          <input type="text" id="news_email" name="news_email" class="form-control input-lg" placeholder="Your mail address here..">        
        </div>
        <div class="col-md-2">
            
            <div class="btn-group btn-group-justified button-element">
                        <div class="btn-group">
                            <a href="#" id="subscribe" name="subscribe"value="publish" class="form-control input-lg btn bg-red">Submit</a>
                        </div>        
                    </div>
                
        </div>
    </form>
      
    </div>
  </div>
  <!-- subscription area ends -->
  <script type="text/javascript">
  $(document).ready(function(){
    $('[name="subscribe"]').click(function (e) {
      // alert('clicked');
    
    var emailval = $('[name="news_email"]').val();
    console.log(emailval);
        if (emailval !== "") {
        $.ajax({
           
            url: "http://localhost/biz_mela/newsletter/subscription", 
            type: 'POST', // request method
           
            data: {
                news_email: emailval // here the email
            },
            success: function (data) {
               //alert(data);
               console.log("in success funvcc");
               console.log(data);
                
            },
           
        })


      .done(function(result) {
       //alert(result);

       console.log("done");

       

       if (result=="1") { 
          $('#shopfail').modal('show');
           setTimeout( "jQuery('#shopfail').modal('hide');",3000 );
           $("#subs_form")[0].reset();
           console.log("1");


       }
       else if (result=="2") { 
         $('#shopsubs').modal('show');
          setTimeout( "jQuery('#shopsubs').modal('hide');",3000 );
          $("#subs_form")[0].reset();
          console.log("2");

       }
       else if (result=="3") { 

          $('#generalfail').modal('show');
           setTimeout( "jQuery('#generalfail').modal('hide');",3000 );
           $("#subs_form")[0].reset();

           console.log("3");
       }

        else if (result=="4") { 
         $('#generalsubscribtion').modal('show');
          setTimeout( "jQuery('#generalsubscribtion').modal('hide');",3000 );
          $("#subs_form")[0].reset();
          console.log("4");
          
        }

        else if (result=="5") { 
         $('#noemail').modal('show');
          setTimeout( "jQuery('#noemail').modal('hide');",3000 );
          $("#subs_form")[0].reset();
          console.log("5");
          
        }

        else if (result=="10") { 
         
          console.log("10");
          
        }

        else if (result=="11") { 
         
          console.log("11");
          
        }

        else if (result=="14") { 
         $('#generalsubscribtion').modal('show');
          setTimeout( "jQuery('#generalsubscribtion').modal('hide');",3000 );
          $("#subs_form")[0].reset();
          console.log("4");
          
        }

        else {

          console.log("home page failure");
              //console.log(result);
            }


    });
    } else {
         //alert("Type Your Mail");
         $('#noemail').modal('show');
         setTimeout( "jQuery('#noemail').modal('hide');",3000 );

    }
  });

  })
  

</script>

  <!-- payment section -->
  <div class="payment">
    <div class="container">
      <div class="col-md-12">
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card1.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card2.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card3.jpg"></img>
        <img class="img-responsive" src="<?php echo $this->url->get().'main/images/';?>card4.jpg"></img>
      </div>
    </div>
  </div>
  <!-- payment section ends here -->


  <!-- footer area -->
  <div class="footer">
    <div class="container">
      <div class="col-md-3 item">
        <h3>Links</h3>
        <div><a href="<?php echo $this->url->get("sitemap/index/"); ?>" class="about">Site Map</a></div>
        <div><a href="<?php echo $this->url->get("footer/index/"); ?>" class="about">About Us</a></div>
        <div>Advanced Search</div>
        <div><a href="<?php echo $this->url->get("policy/index/"); ?>" class="about">Order and Return</a></div>
        <div><a href="<?php echo $this->url->get("contact/contact/"); ?>" class="about">Contact Us</a></div>
        
      </div>
      <div class="col-md-2 item">
        <h3>Information</h3>
        <div>New Products</div>
        <div>Top Seller</div>
        <div>Specials</div>
        <div>Manufacturers</div>
        <div>Our Store</div>
      </div>
      <div class="col-md-3 item">
        <h3>Latest Tweets : <span><img src="<?php echo $this->url->get().'main/images/';?>twitter_icon.png" class="img-responsive"></span></h3>
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua</div>
       
        
      </div>
      <div class="col-md-4 item">
        <h3>Facebook: <span><img src="<?php echo $this->url->get().'main/images/';?>facebook_icon.png" class="img-responsive"></span></h3>
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua</div>
       
        
      </div>
    </div>


    <div class="footer-seperator"></div>

    <div class="bottom-footer container">
      <div class="col-md-4 col-md-offset-1">
        <div class="item"><i class="fa fa-facebook"></i></div>
        <div class="item"><i class="fa fa-twitter"></i></div>
        <div class="item"><i class="fa fa-stack-overflow"></i></div>
        <div class="item"><i class="fa fa-css3"></i></div>
        <div class="item"><i class="fa fa-apple"></i></div>
        <div class="item"><i class="fa fa-android"></i></div>
      </div>
      <div class="col-md-7 text-center copyright">
        ©2014 Biz-mela All rights reserved.Designed and Developed By Atomix System Limited
      </div>
    </div>


  </div>
  <!-- footer area ends here -->

  <div class="modal fade" id="generalsubscribtion" tabindex="-1" role="dialog" aria-labelledby="generalsubscribtionModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> General Subscriptions Successful. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="generalfail" tabindex="-1" role="dialog" aria-labelledby="generalfailModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> You are already subscribed to general subscription. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="shopfail" tabindex="-1" role="dialog" aria-labelledby="shopfailModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> You are already Subscribed. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="noemail" tabindex="-1" role="dialog" aria-labelledby="noemailModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> Insert An Email </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>

<div class="modal fade" id="shopsubs" tabindex="-1" role="dialog" aria-labelledby="shopsubsModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-margin-top">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true"><img src="<?php echo $this->url->get().'main/images/';?>cancel_btn.png"></span>
                <span class="sr-only">Close</span>
              </button>
        
            </div>
            <div class="modal-body">
                <p>
                <center> You have successfully subscribed to our newsletter. </center> 
                </p>
            </div>
            
    </div>
  </div>
</div>






  </body>
</html>
