<style>
h4{
    color:#660099;

}

p > a:hover{

    background-color: #52575F;
    color: white;
}

</style>
<div class="row">

    <div class="item-area">

        <div class="col-md-8 col-md-offset-2">

            <div class="info">
                <Strong> Product Id.: </strong><?php echo $product_id;?>
            </div>
            
            <div class="info">
                <Strong> Product Name: </strong><?php echo $product_name;?>
            </div>
            <div class="info">
                <Strong> Price: </strong><?php echo $price;?>
            </div>

            <div class="info">
                <Strong> Quantity: </strong><?php echo $quantity;?>
            </div>



            
        </div>


    </div>
    

</div>