<style>

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 558px;
    width: 95%;
}

.product{

    padding-top: 0px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px; 
    border:1px solid #ECECEC ;
    border-radius: 4px;   

}


.gray{

	background-color:#FFFFFF;
	color:#042C51;

}

.gray:hover{
	background-color:#F7FAFC;
	color:#84660A;
}
.navbar {
	background-color: #FFFFFF;
}

a{

	text-decoration: none;
	color:#870415;
    font-size: 15px;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
 
    
}

strong > a:hover{


    background-color: #52575F;
    color: white;
}


.col-md-3{
	position: inherit;
}

p{
	font-size: 18px;
}

.intro{
	color:#870415;
    font-size: 15px;
    padding-top: 3px;
}

strong > a{

    color:#A8A8A8;
    font-size: 15px;
    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px;
}

strong>p{
    font-size: 15px;
}


.pager{
    color:#000000;
}

li>a{
    color: #106E96;
}

.order>h2{
	padding-left: 5px;
    color: #106E96;
}

.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height:49px;
}

.red{
    color: #9E0423;

}

.row {
    margin-left: 3px;
    margin-right: -15px;
}
.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}



</style>


<div class="row-cell">
	
	<nav class="navbar navbar-default" role="navigation">
		
      		
   		
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/list/')?>" class="btn btn-lg btn-custom gray" id="list"><p>View Order List</p></a>
			</div>
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/purchase/')?>" class="btn btn-lg btn-custom gray" id="purchase"><p>Purchase History</p></a>
			</div>
			
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/pending/')?>" class="btn btn-lg btn-custom gray" id="pending"><p>&ensp; Pending List &ensp;</p></a>
			</div>
			
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/reject/')?>" class="btn btn-lg btn-custom gray" id="reject"><p>Reject History &ensp; </p></a>
			</div>
			
		</div>
	
	</nav>

	

    <?php foreach ($Order->items as $record){?>
    <div class="product">

        <strong><p>Order Number:</p> <a href="<?php echo $this->url->get("order/details/" . $record->id); ?>"> <?php echo $record->order_no; ?>
        </a>
        </strong>


    </div>
    <?php }?>    

    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Order->current, " of ", $Order->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("Order/order" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->last); ?>">Last</a></li>            
        </ul>

    </div>
</div>


<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[3];

    console.log(choice);

    if(choice=='order')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#list").addClass("red");
    }

    </script>