<style>
h3{
    text-align:center;
}



.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 805px;
    width: 95%;


}


a {
    color: #870415;
	text-decoration: none;
    font-size: 15px;
    
}


a:hover{
    color:#CD2027;
    text-decoration: none;
}





.seperator-dotted{
    width: 100%;
    border-bottom: 1px solid #ECECEC;
    margin: 3px 0px 3px 0px;
    padding-left: 20px;
    padding-right: 10px;
}


strong > a{

    color:#A8A8A8;
    font-size: 15px;
    padding-top: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px;



}

strong > a:hover{


    background-color: #52575F;
    color: white;
}


i{

    font-size:20px;

}


p{

    font-size: 18px;

}

.gray{

    background-color:#F7FAFC;
    color:#042C51;

    

}
.navbar {
    background-color: #F7FAFC;
}

h2{
    padding-left: 5px;
    color: #043868;
}

.intro{
    color:#870415;
    font-size: 15px;
    padding-top: 3px;
}

.info{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 55px;
    width: 95%;
    padding-top: 15px;
    padding-right: 10px;
    padding-bottom: 15px;
    padding-left: 10px;
    text-align: center;


}

</style>


<div class="row-cell">


    <nav class="navbar navbar-default" role="navigation">
        
            
        
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('order/list/')?>" class="btn btn-lg btn-custom gray"><p>View Order List</p></a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('order/purchase/')?>" class="btn btn-lg btn-custom gray"><p>Purchase History</p></a>
            </div>
            
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('order/pending/')?>" class="btn btn-lg btn-custom gray"><p>&ensp; Pending List &ensp;</p></a>
            </div>
            
        </div>
        <div class="col-md-3">
            <div class="btn-group">
                <a href="<?php echo $this->url->get('order/reject/')?>" class="btn btn-lg btn-custom gray"><p>Reject History &ensp; </p></a>
            </div>
            
        </div>
    
    </nav>

     
        <div class="col-md-8 col-md-offset-2">

            <div class="info">
                <Strong> Product Id.: </strong><?php echo $product_id;?>
            </div>
            

            <div class="info">
                <Strong> Price: </strong><?php echo $price;?>
            </div>

            <div class="info">
                <Strong> Quantity: </strong><?php echo $quantity;?>
            </div>
        </div>
    

</div>
