<style>
h3{
    text-align:center;
}

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 805px;
    width: 95%;
}



p{
    font-size: 18px;
}


h2{
    padding-left: 5px;
    color: #043868;
}

.col-md-8 {
    padding-top: 100px;
    padding-left: 20px;
    padding-right: 20px;
}

.info {
    border: 1px solid #ececec;
    border-radius: 4px;
    height: 55px;
    padding: 15px 10px;
    width: 95%;
}

.col-md-8>.info{
    text-align: center;
}

</style>


<div class="row-cell">
 
    <div class="col-md-8 col-md-offset-2">

        <div class="info">
            <Strong> Product Id.: </strong><?php echo $product_id;?>
        </div>
            
        <div class="info">
            <Strong> Product Name: </strong><?php echo $product_name;?>
        </div>
        <div class="info">
            <Strong> Price: </strong><?php echo $price;?>
        </div>

        <div class="info">
            <Strong> Quantity: </strong><?php echo $quantity;?>
        </div>
    </div>
    

</div>
