<style>

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 558px;
    width: 95%;
}

.product{

    padding-top: 0px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px; 
    border:1px solid #ECECEC ; 

}

.col-md-3{
	position: inherit;
}

p{
	font-size: 18px;
}


strong>p{
    font-size: 15px;
}

.order>h2{
	padding-left: 5px;
    color: #106E96;
}


.red{
    color: #9E0423;

}

</style>


<div class="row-cell">
	
	<nav class="navbar navbar-default" role="navigation">
		
      		
   		
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/list/')?>" class="btn btn-lg btn-custom gray" id="list"><p>View Order List</p></a>
			</div>
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/purchase/')?>" class="btn btn-lg btn-custom gray" id="purchase"><p>Purchase History</p></a>
			</div>
			
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/pending/')?>" class="btn btn-lg btn-custom gray" id="pending"><p>&ensp; Pending List &ensp;</p></a>
			</div>
			
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/reject/')?>" class="btn btn-lg btn-custom gray" id="reject"><p>Reject History &ensp; </p></a>
			</div>
			
		</div>
	
	</nav>

	

    <?php foreach ($Order->items as $record){?>
    <div class="product">

        <strong><p>Order Number:</p> <a href="<?php echo $this->url->get("order/details/" . $record->id); ?>"> <?php echo $record->order_no; ?>
        </a>
        </strong>


    </div>
    <?php }?>    

    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Order->current, " of ", $Order->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("Order/order" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->last); ?>">Last</a></li>            
        </ul>

    </div>
</div>


<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[3];

    console.log(choice);

    if(choice=='order')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#list").addClass("red");
    }

    </script>