<style>

.row-cell{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 558px;
    width: 95%;
}

.product{

    padding-top: 0px;
    padding-right: 5px;
    padding-bottom: 5px;
    padding-left: 5px; 
    border:1px solid #ECECEC ; 

}

.col-md-3{
	position: inherit;
}

p{
	font-size: 18px;
}


strong>p{
    font-size: 15px;
}

.order>h2{
	padding-left: 5px;
    color: #106E96;
}


.red{
    color: #9E0423;

}

td{
    font-size: 15px;
}

</style>

<?php echo \Phalcon\Tag::stylesheetLink("main/css/order.css"); ?>
<div class="row-cell">
	
	<nav class="navbar navbar-default" role="navigation">
		
      		
   		
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/list/')?>" class="btn btn-lg btn-custom gray" id="list"><p>View Order List</p></a>
			</div>
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/purchase/')?>" class="btn btn-lg btn-custom gray" id="purchase"><p>Purchase History</p></a>
			</div>
			
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/pending/')?>" class="btn btn-lg btn-custom gray" id="pending"><p>&ensp; Pending List &ensp;</p></a>
			</div>
			
		</div>
		<div class="col-md-3">
			<div class="btn-group">
				<a href="<?php echo $this->url->get('order/reject/')?>" class="btn btn-lg btn-custom gray" id="reject"><p>Reject History &ensp; </p></a>
			</div>
			
		</div>
	
	</nav>

	

   <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading" id="heading">
                My Orders
            </div>
            <div class="panel-body">
                <div class="table-responsive">

                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Order Number</th>
                                            <th>Product Name</th>
                                            
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Total</th>
                                             <th>Status</th>
                                            
                                        </tr>
                                    </thead>
                                     <?php 
                                     $count=0;
                                     foreach ($Order->items as $record) { 
                                            $count++;
                                        ?>
                                     <tbody>
                                        <tr>
                                            <td><?php echo $count; ?></td>
                                            <td>
                                                
                                                <?php echo $record->order_no; ?>
                                                    
                                            </td>
                                            <td>
                                                <?php echo $record->product_name; ?>
                                            </td>
                                            <td>
                                                 <?php echo $record->price;?>
                                            </td>
                                            <td>
                                                 <?php echo $record->quantity; ?>
                                            </td>

                                            <td>
                                                 <?php echo $record->total; ?>
                                            </td>

                                            <td>
                                                 <?php echo $record->status; ?>
                                            </td>



                                             
                                            
                                            
                                            
                                        </tr>
                                    </tbody>
                                     <?php } ?>
                        </table>

                    </div>
                </div>

            </div>
        </div>
</div> 

    <div class="col-md-12">

        <ul class="pager">
                <li><?php echo "You are in page ", $Order->current, " of ", $Order->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("Order/order" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("Order/order?page=" . $Order->last); ?>">Last</a></li>            
        </ul>

    </div>
</div>


<script type="text/javascript">
    var pathname = window.location.pathname;
    var patharray = pathname.split("/");
    console.log("path arrray ");
    console.log(patharray);

    var choice=patharray[3];

    console.log(choice);

    if(choice=='order')
    {
        //$("#list").html("<font color="red"> View Order List </font>");
        $("#list").addClass("red");
    }

    </script>