<style>
h3.a{
color:#DF013A;
padding-top: 25px;
    padding-right: 25px;
    padding-bottom: 25px;
    padding-left: 25px;
}

.settings-area {
    font-size: 13px;
    position: absolute;
    right: 60px;
    text-align: right;
    top: 10px;
}
</style>

<div class="container">
</hr>
<div class="row-cell">
<div class="col-md-3">

<h3 class="a"> Account Information </h3>
<div class="seperator-dotted"></div>
<p><b>User Name</b>       : <?php echo $data['value']->username;?></p>
<p><b>Email Address</b>   : <?php echo $data['value']->email;?></p>
<p><b>Cell Phone</b>    : <?php echo $data['value']->contact_no;?></p>
<p><b>Address</b>        : <?php echo $data['value']->address;?></p>
<p><b>Account Creation</b>: <?php echo $data['value']->created_at;?></p>
<p><b>Profile Picture</b> : <?php echo $data['value']->picture;?></p>

</br>
</br>
</div>


</div>
</div>