<style>
.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}
a{
    color:#870415;
    text-decoration: none;
    font-size: 15px;
}
a:hover{
    color:#CD2027;
    text-decoration: none;
}
.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height:49px;
}

.row {
    margin-left: 3px;
    margin-right: -15px;
}

.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 10px;

}
</style>
<div class="row-cell">
    <div class="item-area">
	
        <div class="form-area">

            <?php echo $this->getContent(); ?>

            <form action="" method="post">
                    <!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
				<div class="col-md-10 col-md-offset-1">
				<div class="row cell">
    				<?php echo $form->render("accountholder"); ?>
    				<?php echo $form->render("accountno"); ?>
    				<?php echo $form->render("bank"); ?>
    				<?php echo $form->render("branch"); ?>
                    <?php echo $form->render("swiftcode"); ?>
				    </br>

                <div class="btn-group btn-group-justified button-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="publish" class="btn btn-lg btn-custom green">Update Account</button>
                    </div>			  
                </div>
				<div class="btn-group btn-group-justified form-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="cancel" class="btn btn-lg btn-custom btn-danger">Cancel</button>
                    </div>		  
                </div>
                
			</div>
				</div>
            </form>
        </div>

    </div>
    <script type="text/javascript">
        
    </script>
</div>
