
<div class="row-cell">

    <div class="item-area">

        <div class="col-md-8 col-md-offset-2">
            <div class="info">
                <Strong> Product Name: </strong><?php echo $heading;?>
            </div>
            <div class="info">
                <Strong> Description: </strong><?php echo $description;?>
            </div>

            <div class="info">
                <Strong> Price: </strong><?php echo $price;?>
            </div>

            <div class="info">
                <Strong> Creation: </strong><?php echo $created_at;?>
            </div>

            <div class="info">
                <Strong> Stock Quantity: </strong><?php echo $in_stock;?>
            </div>

            <div class="info">
                <Strong> Discount Rate: </strong><?php echo $discount;?>
            </div>
            <div class="info">
                <Strong>Least Orders To be served:</strong> <?php echo $minimum_order_level; ?>
            </div>

            
        </div>


    </div>
    

</div>