<style>
h4{
color:#660099;

}

.info{

    border:1px solid #ECECEC ;
    border-radius: 4px;
    height: 55px;
    width: 95%;
    padding-top: 15px;
    padding-right: 10px;
    padding-bottom: 15px;
    padding-left: 10px;


}

.item-area{

    text-align: center;

}

p > a:hover{

    background-color: #52575F;
    color: white;
}
a{

    text-decoration: none;
    color:#870415;
    font-size: 15px;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}

.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}

.title{
    padding:8px;
}

.panel-default > .panel-heading {
    background-color: #FFFFFF;
    border-color: #ddd;
    color: #333;
    height: 49px;
}
.row {
    margin-left: 3px;
    margin-right: -15px;
}
.main-menu-title>h2{
    font-size: 25px;   
    padding-top: 6px;

}


</style>
<div class="row-cell">

    <div class="item-area">

        <div class="col-md-8 col-md-offset-2">
            <div class="info">
                <Strong> Product Name: </strong><?php echo $heading;?>
            </div>
            <div class="info">
                <Strong> Description: </strong><?php echo $description;?>
            </div>

            <div class="info">
                <Strong> Price: </strong><?php echo $price;?>
            </div>

            <div class="info">
                <Strong> Creation: </strong><?php echo $created_at;?>
            </div>

            <div class="info">
                <Strong> Stock Quantity: </strong><?php echo $in_stock;?>
            </div>

            <div class="info">
                <Strong> Discount Rate: </strong><?php echo $discount;?>
            </div>
            <div class="info">
                <Strong>Least Orders To be served:</strong> <?php echo $minimum_order_level; ?>
            </div>

            
        </div>


    </div>
    

</div>