<style>
.form-element {
    margin-top: 10px;
}

.input-lg {
    border-radius: 4px;
    font-size: 15px;
    height: 46px;
    line-height: 1.33;
    padding: 10px 16px;
}


</style>
<div class="row-cell">
    <div class="item-area">
	
        <div class="form-area">

            <?php echo $this->getContent(); ?>

            <form action="" method="post">
                    <!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
				<div class="col-md-10 col-md-offset-1">
				<div class="row cell">
                    <?php echo $form->render("product_name"); ?>
    				<?php echo $form->render("description"); ?>
    				<?php echo $form->render("price"); ?>
                    <?php echo $form->render("in_stock"); ?>
    				<?php echo $form->render("discount"); ?>
    				<?php echo $form->render("minimum_order_level"); ?>
                    <?php echo $form->render("price"); ?>
				
                

				</br>

                <div class="btn-group btn-group-justified button-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="publish" class="btn btn-lg btn-custom green">Update Product</button>
                    </div>			  
                </div>
				<div class="btn-group btn-group-justified form-element">
                    <div class="btn-group">
                        <button type="submit" name="submit" value="cancel" class="btn btn-lg btn-custom btn-danger">Cancel</button>
                    </div>		  
                </div>
                
			</div>
				</div>
            </form>
        </div>

    </div>
    <script type="text/javascript">
        
    </script>
</div>
