<style>


.des{
	text-align: left;
	margin-left: 50px;
	margin-right: 40px;
}

ul{
	margin-left: 50px;
	margin-right: 40px;
}

.heading{
	color:#000;
	text-align: center;
}

</style>


<div class="row">
	<div class="container">
		<h3 class="heading">Bizmela.com</h3>
	</div>

	<div class="container">
		<p class="des"><highlight>Bizmela.com </highlight>  is a E-commerce site like it trading in products or services using computer networks, such as the Internet.
			Bizmela.com provides some and usually all facilities:</p>
			<ul>
				<li>Buy or sell on websites or online marketplaces.</li>
				<li>Gather and use demographic data through web contacts and social media.</li>
				<li>Use electronic data interchange, the business-to-business exchange of data.</li>
				<li>Reach prospective and established customers by e-mail or fax (for example, with newsletters).</li>
				<li>Use business-to-business buying and selling.</li>
				<li>Provide secure business transactions</li>
			</ul>
		
	</div>
</div>