
<style>
.seperator-dotted {
    border-bottom: 1px dotted #000;
    margin: 5px 0;
    width: 100%;
}
</style>

<!--<div class="row">
    <h3>Group:Admin<a href="<?php echo $this->url->get('user/new/')?>"><span class="glyphicon glyphicon-plus pull-right" style="background-color: #FFFFFF;padding: 5px;border-radius: 10px;cursor:pointer;"></span></a></h3>
</div>-->
<script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable();
    });
    </script>
<!--<div class="row">
    <h3>Group:Admin<a href="<?php echo $this->url->get('user/new/')?>"><span class="glyphicon glyphicon-plus pull-right" style="background-color: #FFFFFF;padding: 5px;border-radius: 10px;cursor:pointer;"></span></a></h3>
</div>-->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Admin Mangement</h1>
        </div>
</div>
<div class="row">
                <div class="col-md-12">
                     <div class="panel panel-default">
                        <div class="panel-heading">
                            Admin List
                        </div>
                     <div class="panel-body">
                     <div class="table-responsive">
                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row">
                                
                                <div class="col-sm-12">
                                    <div id="dataTables-example_filter" class="dataTables_filter">
                                        <label>
                                        Search:
                                        <input class="form-control input-sm" type="search" aria-controls="dataTables-example">
                                        </label>
                                    </div>
                                </div>
                            </div>
                                <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer" aria-describedby="dataTables-example_info">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>User Name</th>
                                            <th>Created At</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                     <?php 
                                     $count=0;

                                     foreach ($user->items as $aa) { 

                                            $count++;
                                        ?>
                                     <tbody>
                                        <tr>
                                            <td><?php echo $count; ?></td>
                                            <td><?php echo $aa->name; ?></td>
                                            <td><?php echo date('M d , Y H:i', strtotime($aa->created_at)); ?></td>
                                            <td><a href="<?php echo $this->url->get('admin/admin/update/'.$aa->id);?>"><i class="fa fa-pencil fa-lg " element_id="<?php echo $aa->id; ?>"></i></a></td>
                                            <td><a href="<?php echo $this->url->get('admin/admin/delete/'.$aa->id);?>"><i class="fa fa-trash-o fa-lg delete" element_id="<?php echo $aa->id; ?>"></i></a></td>
                                            <?php if($aa->status==1){?>
                                                <td><a href="<?php echo $this->url->get('admin/admin/changestatus/'.$aa->id);?>"><img src="<?php echo $this->url->get('main/admin/img/OK.png')?>"></a></td>
                                            <?php } else{?>
                                                <td><a href="<?php echo $this->url->get('admin/admin/changestatus/'.$aa->id);?>"><img src="<?php echo $this->url->get('main/admin/img/cancel-icon.png')?>"></a></td>
                                            <?php } ?>
                                        </tr>
                                    </tbody>
                                     <?php } ?>
                                </table>

        <div>

            <ul class="pager">
                <li><?php echo "You are in page ", $user->current, " of ", $user->total_pages; ?></li>
                <li><a href="<?php echo $this->url->get("admin/admin/" ); ?>">First</a></li>
                <li><a href="<?php echo $this->url->get("admin/admin/?page=" . $user->before); ?>">Previous</a></li>
                <li><a href="<?php echo $this->url->get("admin/admin/?page=" . $user->next); ?>">Next</a></li>
                <li><a href="<?php echo $this->url->get("admin/admin/?page=" . $user->last); ?>">Last</a></li>            
            </ul>





        </div>
                    </div>
       </div>           


<div class="text-center new-button">
            <a href="<?php echo $this->url->get('admin/admin/new/')?>"><i class="fa fa-plus-square-o fa-5x"></i></a>
            <h3>New User</h3>
        </div>






