<style>

.des{
	text-align: left;
	margin-left: 50px;
	margin-right: 40px;
}

.heading{
	color:#000;
	text-align: center;
}

.policy{
	margin-left: 50px;
	margin-right: 40px;
}

.policy>b{
	text-align: center;
}

ul{
	list-style-type: none;

}
ul>li{
	padding-left: 20px;
}

</style>


<div class="row">
	<div class="container">
		<h3 class="heading">BizMela SiteMap</h3>
	</div>

	<div class="container">
		<p class="policy">
			<b >What is a SiteMap??</b></br>
			For the purposes of this tutorial we will focus on Sitemap Protocol 0.9 introduced by SiteMaps.org which is a standard, validated and used by Google and most other search engines.

			A Sitemap allows you to create a file hosted among the other files in your account that informs the search engines of all pages your website contains. In other words, it provides the search engine with detailed information about the content of your website.

			Although Sitemaps are mainly used to improve the index process of your website by search engines, they can be used to provide accessibility to certain pages as well. For example, pages that are not accessible via your menus, can be indexed by the search engine if you want.. </p>
		<p class="policy">
			<b>Our Sitemap Covers...</b></br>
			<ul>
				<li>Account Information</li>
				<li>Shopping Cart</li>
				<li>Wishlist</li>
				<li>Detailed Shop Description</li>
				<li>Detailed Product Description</li>
				<li>Update products</li>
				<li>User Account creation and modification</li>



			</ul>
			</p>
		
		
	</div>
</div>