
<style>
.seperator-dotted {
    border-bottom: 1px dotted #000;
    margin: 5px 0;
    width: 100%;
}
</style>

<!--<div class="row">
    <h3>Group:Admin<a href="<?php echo $this->url->get('user/new/')?>"><span class="glyphicon glyphicon-plus pull-right" style="background-color: #FFFFFF;padding: 5px;border-radius: 10px;cursor:pointer;"></span></a></h3>
</div>-->
<script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable();
    });
    </script>
<!--<div class="row">
    <h3>Group:Admin<a href="<?php echo $this->url->get('user/new/')?>"><span class="glyphicon glyphicon-plus pull-right" style="background-color: #FFFFFF;padding: 5px;border-radius: 10px;cursor:pointer;"></span></a></h3>
</div>-->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User Mangement</h1>
        </div>
</div>
<div class="row">
                <div class="col-md-12">
                     <div class="panel panel-default">
                        <div class="panel-heading">
                            User List
                        </div>
                     <div class="panel-body">
                     <div class="table-responsive">
                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row">
                                
                                <div class="col-sm-12">
                                    <div id="dataTables-example_filter" class="dataTables_filter">
                                        <label>
                                        Search:
                                        <input class="form-control input-sm" type="search" aria-controls="dataTables-example">
                                        </label>
                                    </div>
                                </div>
                            </div>
                                <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer" aria-describedby="dataTables-example_info">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>User Name</th>
                                            <th>Email</th>
                                            <th>Adress</th>
                                            <th>Contact No</th>
                                            <th>Image</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                     <?php 
                                     $count=0;
                                     foreach ($user->items as $aa) { 
                                            $count++;
                                        ?>
                                     <tbody>
                                        <tr>
                                            <td><?php echo $count; ?></td>
                                            <td><?php echo $aa->first_name; ?></td>
                                            <td><?php echo $aa->last_name; ?></td>
                                            <td><?php echo $aa->username; ?></td>
                                            <td><?php echo $aa->email; ?></td>
                                            <td><?php echo $aa->address; ?></td>
                                            <td><?php echo $aa->contact_no; ?></td>
                                            <td><img   src="<?php echo $this->url->get().$aa->picture; ?>" class="img-responsive img-rounded"></td>
                                            <?php if($aa->status==1){?>
                                                <td><a href="<?php echo $this->url->get('admin/user/changestatus/'.$aa->id);?>"><img src="<?php echo $this->url->get('main/admin/img/OK.png')?>"></a></td>
                                            <?php } else{?>
                                                <td><a href="<?php echo $this->url->get('admin/user/changestatus/'.$aa->id);?>"><img src="<?php echo $this->url->get('main/admin/img/cancel-icon.png')?>"></a></td>
                                            <?php } ?>
                                            <td><a href="<?php echo $this->url->get('admin/user/shop/'.$aa->id);?>">Shop</a></td>
                                        </tr>
                                    </tbody>
                                     <?php } ?>
                                </table>
                                 <div>
                                        <ul class="pager">
                                            <li><?php echo "You are in page ", $user->current, " of ", $user->total_pages; ?></li>
                                            <li><a href="<?php echo $this->url->get("admin/user" ); ?>">First</a></li>
                                            <li><a href="<?php echo $this->url->get("admin/user?page=" . $user->before); ?>">Previous</a></li>
                                            <li><a href="<?php echo $this->url->get("admin/user?page=" . $user->next); ?>">Next</a></li>
                                            <li><a href="<?php echo $this->url->get("admin/user?page=" . $user->last); ?>">Last</a></li>            
                                        </ul>
                    </div>
                    </div>
       </div>           









