
<style>
.seperator-dotted {
    border-bottom: 1px dotted #000;
    margin: 5px 0;
    width: 100%;
}
</style>

<!--<div class="row">
    <h3>Group:Admin<a href="<?php echo $this->url->get('user/new/')?>"><span class="glyphicon glyphicon-plus pull-right" style="background-color: #FFFFFF;padding: 5px;border-radius: 10px;cursor:pointer;"></span></a></h3>
</div>-->
<script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable();
    });
    </script>
<!--<div class="row">
    <h3>Group:Admin<a href="<?php echo $this->url->get('user/new/')?>"><span class="glyphicon glyphicon-plus pull-right" style="background-color: #FFFFFF;padding: 5px;border-radius: 10px;cursor:pointer;"></span></a></h3>
</div>-->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User Mangement</h1>
        </div>
</div>
<div class="row">
                <div class="col-md-12">
                     <div class="panel panel-default">
                        <div class="panel-heading">
                            Product List
                        </div>
                     <div class="panel-body">
                     <div class="table-responsive">
                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                        <div class="row">
                                
                                <div class="col-sm-12">
                                    <div id="dataTables-example_filter" class="dataTables_filter">
                                        <label>
                                        Search:
                                        <input class="form-control input-sm" type="search" aria-controls="dataTables-example">
                                        </label>
                                    </div>
                                </div>
                            </div>
                                <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer" aria-describedby="dataTables-example_info">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Product Name</th>
                                            <th>Price</th>
                                            <th>In stock</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                     <?php 
                                     $count=0;
                                     foreach ($product as $aa) { 
                                            $count++;
                                        ?>
                                     <tbody>
                                        <tr>
                                            <td><?php echo $count; ?></td>
                                            <td><?php echo $aa->product_name; ?></td>
                                            <td><?php echo $aa->price; ?></td>
                                            <td><?php echo $aa->in_stock; ?></td>
                                            <td><a href="<?php echo $this->url->get('admin/product/detail/'.$aa->id);?>">Detail</a></td>
                                            <td><a href="<?php echo $this->url->get('admin/product/update/'.$aa->id);?>">Block</a></td>
                                        </tr>
                                    </tbody>
                                     <?php } ?>
                                </table>
                    </div>
       </div>           









