
<style>
.seperator-dotted {
    border-bottom: 1px dotted #000;
    margin: 5px 0;
    width: 100%;
}
</style>


<!--<div class="row">
    <h3>Group:Admin<a href="<?php echo $this->url->get('user/new/')?>"><span class="glyphicon glyphicon-plus pull-right" style="background-color: #FFFFFF;padding: 5px;border-radius: 10px;cursor:pointer;"></span></a></h3>
</div>-->

<div class="row">
        <div class="col-xs-4">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">

    <?php $count=0;?>
    <?php foreach ($product as $aa) { ?>
    <?php if ($count==0){?>

            <div class="item active">
                <img   src="<?php echo $this->url->get().$aa->picture; ?>" class="img-responsive img-rounded">
            </div>
            <?php $count++; }else{?>
            <div class="item ">
                <img   src="<?php echo $this->url->get().$aa->picture; ?>" class="img-responsive img-rounded">
            </div>
            <?php }?>

    <?php } ?>

    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
        </div>
        <div class="col-xs-8">
            <table class="table table-striped">
                <tr><td><strong>Product Name: </strong></td><td><?php echo $product[0]->product_name; ?></td></tr>
                <tr><td><strong>Product Description: </strong></td><td><?php echo $product[0]->product_description; ?></td></tr>
                <tr><td><strong>Shop Name: </strong></td><td><?php echo $product[0]->shop_name; ?></td></tr>
                <tr><td><strong>Price: </strong></td><td><?php echo $product[0]->price; ?></td></tr>
                <tr><td><strong>Discount: </strong></td><td><?php echo $product[0]->discount; ?></td></tr>
                <tr><td><strong>In Stock: </strong></td><td><?php echo $product[0]->in_stock; ?></td></tr>
  
            </table>

                                <!-- <p><strong>Product Name: </strong><?php echo $product[0]->product_name; ?></p>
                                <p><strong>Product Description: </strong><?php echo $product[0]->product_description; ?></p>
                                <p><strong>Shop Name: </strong><?php echo $product[0]->shop_name; ?></p>
                                <p><strong>Price: </strong><?php echo $product[0]->price; ?></p>
                                <p><strong>Discount: </strong><?php echo $product[0]->discount; ?>%</p>
                                <p><strong>In Stock: </strong><?php echo $product[0]->in_stock; ?></p> -->
                            
        </div>
</div>

