<style>

.abc{
  color:#106e96;
  font-size: 18px;
  padding-top: 20px;
  padding-left: 25px;
  
}

.top-menu .item {
    border-right: 0px solid #c8c8c8;
    color: #de3e3e;
    float: left;
    padding: 0 10px;
}

.top-menu .item:first-child {
    border-left: 0px solid #c8c8c8;
}
a{
    color:#870415;
    font-size: 15px;
    text-decoration: none;
}

a:hover{
    color:#CD2027;
    text-decoration: none;
}

.intro{
    color:#870415;
    padding-top: 3px;
    font-size: 15px;
}

.shopping-text{
	text-decoration: none;
}


</style>




<div>



<div class="col-md-9 col-md-offset-2">

  <h3 class="abc"><?php  echo $data['value']; ?></h3>
</div>

</div>