<style>

}

</style>

<div class="container ">
	<div class="row">
		<h2>Change Password</h2>
	</div>
	<div class="container ">
		<div class="item-area">
			<div class="form-area">
						
				<?php echo $this->getContent(); ?>

				<form action="" method="post">
					<!-- <input class="form-control input-lg" type="text" name="username" placeholder="username" /> -->
					<?php echo $form->render("current_pass"); ?>
						<?php $message = $form->getMessagesFor('current_pass');
						foreach ($message as $m) {?>
							<div class="alert alert-danger form-element"><?php echo $m; ?></div>
						<?php }?>
					
					<?php echo $form->render("new_pass"); ?>
						<?php $message = $form->getMessagesFor('new_pass');
						foreach ($message as $m) {?>
							<div class="alert alert-danger form-element"><?php echo $m; ?></div>
						<?php }?>

					<?php echo $form->render("confirm_pass"); ?>
						<?php $message = $form->getMessagesFor('confirm_pass');
						foreach ($message as $m) {?>
							<div class="alert alert-danger form-element"><?php echo $m; ?></div>
						<?php }?>

					</br>

				    <div class="btn-group btn-group-justified button-element">
					  <div class="btn-group">
					    <button type="submit" class="btn btn-lg btn-custom green">Change Password</button>
					  </div>
					  
					</div>

				</form>
			</div>
			

		</div>
	</div>
</div>